// backend/src/modules/wfm/__tests__/attendance-source-rule-resolver.property.test.ts
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import {
  resolveRule,
  DIMENSION_PRIORITY_ORDER,
  type DimensionScopedRule,
  type EmployeeAttributes,
  type RuleDimension,
} from '../attendance-source-rule-resolver.js';

type TestRule = DimensionScopedRule & { attendanceSource: 'biometric' | 'dialler' };

// Small alphabets so generated rules and employees collide often enough to exercise
// specificity/priority/tie-break, not just the trivial "nothing matches" case.
// A local, independently-declared copy of the dimension priority order — deliberately NOT
// the same reference as the resolver's own DIMENSION_PRIORITY_ORDER import, so a mutant that
// silently reorders the resolver's constant cannot also silently reorder this file's oracle.
const TEST_DIMENSION_PRIORITY_ORDER: readonly RuleDimension[] = [
  'cost_centre',
  'process',
  'branch',
  'department',
  'designation',
  'employment_profile',
];

const VALUE_ALPHABET = ['A', 'B'] as const;

const employeeAttrsArb: fc.Arbitrary<EmployeeAttributes> = fc.record({
  costCentreId: fc.option(fc.constantFrom(...VALUE_ALPHABET), { nil: null }),
  processId: fc.option(fc.constantFrom(...VALUE_ALPHABET), { nil: null }),
  branchId: fc.option(fc.constantFrom(...VALUE_ALPHABET), { nil: null }),
  departmentId: fc.option(fc.constantFrom(...VALUE_ALPHABET), { nil: null }),
  designationId: fc.option(fc.constantFrom(...VALUE_ALPHABET), { nil: null }),
  employmentProfile: fc.option(fc.constantFrom(...VALUE_ALPHABET), { nil: null }),
});

function dimensionValueArb(): fc.Arbitrary<Set<string> | undefined> {
  return fc.oneof(
    fc.constant(undefined), // unconstrained
    fc.uniqueArray(fc.constantFrom(...VALUE_ALPHABET), { minLength: 1, maxLength: 2 }).map(
      (vs) => new Set(vs),
    ),
  );
}

// id is generated by fc.uuid() as part of the record itself, not by a shared mutable counter —
// a mutable counter makes generated ids depend on how many times the arbitrary has already run
// in the process rather than on the fast-check seed alone, which breaks shrink/replay fidelity
// (a failing case could shrink to a DIFFERENT case than the one that actually failed).
const testRuleArb: fc.Arbitrary<TestRule> = fc
  .record({
    id: fc.uuid(),
    cost_centre: dimensionValueArb(),
    process: dimensionValueArb(),
    branch: dimensionValueArb(),
    department: dimensionValueArb(),
    designation: dimensionValueArb(),
    employment_profile: dimensionValueArb(),
    effectiveFrom: fc.constantFrom('2026-01-01', '2026-06-01', '2026-08-01'),
    createdAtOffset: fc.integer({ min: 0, max: 1000 }),
    attendanceSource: fc.constantFrom<'biometric' | 'dialler'>('biometric', 'dialler'),
  })
  .map((r) => {
    const dimensionValues: Partial<Record<RuleDimension, Set<string>>> = {};
    for (const dim of DIMENSION_PRIORITY_ORDER) {
      const v = (r as any)[dim] as Set<string> | undefined;
      if (v) dimensionValues[dim] = v;
    }
    return {
      id: r.id,
      dimensionValues,
      effectiveFrom: r.effectiveFrom,
      createdAt: `2026-01-01T00:00:${String(r.createdAtOffset % 2).padStart(2, '0')}.000Z`,
      attendanceSource: r.attendanceSource,
    } satisfies TestRule;
  });

function systemDefaultRule(): TestRule {
  return {
    id: 'system-default',
    dimensionValues: {},
    effectiveFrom: '2026-01-01',
    createdAt: '2026-01-01T00:00:00.000Z',
    attendanceSource: 'biometric',
  };
}

// Independent test-side re-implementation of matching/specificity, deliberately NOT imported
// from the resolver under test — used as an oracle so Property 3 does not validate the
// implementation's own labels against themselves. Aligned to the implementation's actual
// truthiness check (`size > 0`, not merely "is the Set present") per review finding.
function testEmployeeAttributeFor(dim: RuleDimension, attrs: EmployeeAttributes): string | null {
  switch (dim) {
    case 'cost_centre':
      return attrs.costCentreId;
    case 'process':
      return attrs.processId;
    case 'branch':
      return attrs.branchId;
    case 'department':
      return attrs.departmentId;
    case 'designation':
      return attrs.designationId;
    case 'employment_profile':
      return attrs.employmentProfile;
  }
}

function testRuleMatches(rule: TestRule, attrs: EmployeeAttributes): boolean {
  for (const dim of TEST_DIMENSION_PRIORITY_ORDER) {
    const constraint = rule.dimensionValues[dim];
    if (!constraint || constraint.size === 0) continue;
    const empValue = testEmployeeAttributeFor(dim, attrs);
    if (empValue === null) return false;
    if (!constraint.has(empValue)) return false;
  }
  return true;
}

function testSpecificity(rule: TestRule): number {
  return TEST_DIMENSION_PRIORITY_ORDER.filter((d) => {
    const c = rule.dimensionValues[d];
    return c !== undefined && c.size > 0;
  }).length;
}

function testConstrains(rule: TestRule, dim: RuleDimension): boolean {
  const c = rule.dimensionValues[dim];
  return c !== undefined && c.size > 0;
}

describe('resolveRule — Property 1: Resolution totality', () => {
  it('always returns exactly one winner when the System_Default_Rule is present', () => {
    // Feature: payroll-attendance-source-rules, Property 1: Resolution totality
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const result = resolveRule(rules, attrs);
          expect(result.winner).not.toBeNull();
        },
      ),
      { numRuns: 200 },
    );
  });
});

describe('resolveRule — Property 2: Resolution determinism', () => {
  it('two consecutive resolutions over an unchanged store return the same winner', () => {
    // Feature: payroll-attendance-source-rules, Property 2: Resolution determinism
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const first = resolveRule(rules, attrs);
          const second = resolveRule(rules, attrs);
          expect(second.winner?.id).toBe(first.winner?.id);
        },
      ),
      { numRuns: 200 },
    );
  });

  it('the winner is independent of the input array order', () => {
    // Feature: payroll-attendance-source-rules, Property 2: Resolution determinism
    // (order-independence, not merely "same array called twice" — a stronger check per review)
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const forward = resolveRule(rules, attrs);
          const reversed = resolveRule([...rules].reverse(), attrs);
          expect(reversed.winner?.id).toBe(forward.winner?.id);
        },
      ),
      { numRuns: 200 },
    );
  });
});

describe('resolveRule — Property 3: Specificity and priority ordering govern selection', () => {
  it('the winner has the maximum specificity among independently-computed matching rules', () => {
    // Feature: payroll-attendance-source-rules, Property 3: Specificity and priority ordering govern selection
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const result = resolveRule(rules, attrs);
          const matchingRules = rules.filter((r) => testRuleMatches(r, attrs));
          const maxSpec = Math.max(...matchingRules.map(testSpecificity));
          expect(testSpecificity(result.winner!)).toBe(maxSpec);
        },
      ),
      { numRuns: 200 },
    );
  });

  it('at max specificity, the winner constrains the first priority-order dimension that splits the tied survivors', () => {
    // Feature: payroll-attendance-source-rules, Property 3: Specificity and priority ordering govern selection
    // This directly guards the priority-walk step: a reversed walk order, a deleted priority
    // step, or an off-by-one on the "some but not all" boundary would each produce a winner
    // that fails this assertion on some generated case.
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const result = resolveRule(rules, attrs);
          const matchingRules = rules.filter((r) => testRuleMatches(r, attrs));
          const maxSpec = Math.max(...matchingRules.map(testSpecificity));
          const tiedAtMax = matchingRules.filter((r) => testSpecificity(r) === maxSpec);

          if (tiedAtMax.length <= 1) return; // no tie to break

          for (const dim of DIMENSION_PRIORITY_ORDER) {
            const constrainedBy = tiedAtMax.filter((r) => testConstrains(r, dim));
            if (constrainedBy.length > 0 && constrainedBy.length < tiedAtMax.length) {
              // dim is the FIRST dimension in priority order that splits the tied survivors —
              // the winner must be on the constraining side of that split.
              expect(testConstrains(result.winner!, dim)).toBe(true);
              return;
            }
          }
          // no dimension discriminates among the tied survivors — tail-break governs instead,
          // covered by the deterministic-tail property below.
        },
      ),
      { numRuns: 200 },
    );
  });
});

describe('resolveRule — Property: deterministic tail breaks a specificity-and-priority tie', () => {
  it('among survivors indistinguishable by specificity and priority order, the winner has the latest effective_from, then latest created_at, then lowest id', () => {
    // Feature: payroll-attendance-source-rules, Property 3 (deterministic-tail component,
    // requirements.md criterion 2.5). Independently recomputes the full selection (matching ->
    // max specificity -> priority walk -> tail) without importing the resolver's own logic, so
    // an inverted tail (earliest-wins, or highest-id-wins) fails this assertion.
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const result = resolveRule(rules, attrs);
          const matchingRules = rules.filter((r) => testRuleMatches(r, attrs));
          const maxSpec = Math.max(...matchingRules.map(testSpecificity));
          let tied = matchingRules.filter((r) => testSpecificity(r) === maxSpec);

          for (const dim of DIMENSION_PRIORITY_ORDER) {
            const constrainedBy = tied.filter((r) => testConstrains(r, dim));
            if (constrainedBy.length > 0 && constrainedBy.length < tied.length) {
              tied = constrainedBy;
              break;
            }
          }

          if (tied.length <= 1) return; // no tail-break needed for this generated case

          const maxEffectiveFrom = tied.reduce(
            (a, b) => (b.effectiveFrom > a ? b.effectiveFrom : a),
            tied[0].effectiveFrom,
          );
          const atMaxDate = tied.filter((r) => r.effectiveFrom === maxEffectiveFrom);
          const maxCreatedAt = atMaxDate.reduce(
            (a, b) => (b.createdAt > a ? b.createdAt : a),
            atMaxDate[0].createdAt,
          );
          const atMaxCreated = atMaxDate.filter((r) => r.createdAt === maxCreatedAt);
          const expectedWinnerId = atMaxCreated.reduce(
            (a, b) => (b.id < a ? b.id : a),
            atMaxCreated[0].id,
          );

          expect(result.winner!.id).toBe(expectedWinnerId);
        },
      ),
      { numRuns: 200 },
    );
  });
});

describe('resolveRule — Property 4: A missing dimension value never matches a rule constraining it', () => {
  it('a rule constraining a dimension the employee has no value for is never the winner', () => {
    // Feature: payroll-attendance-source-rules, Property 4: A missing dimension value never matches a rule constraining it
    fc.assert(
      fc.property(
        fc.array(testRuleArb, { maxLength: 8 }),
        employeeAttrsArb,
        (extraRules, attrs) => {
          const rules = [systemDefaultRule(), ...extraRules];
          const result = resolveRule(rules, attrs);

          for (const dim of DIMENSION_PRIORITY_ORDER) {
            const empValue = testEmployeeAttributeFor(dim, attrs);

            if (empValue === null) {
              expect(result.unresolvedDimensions).toContain(dim);
              const winnerConstrainsDim = result.winner!.dimensionValues[dim];
              if (winnerConstrainsDim && winnerConstrainsDim.size > 0) {
                throw new Error(
                  `winner ${result.winner!.id} constrains unresolved dimension ${dim}`,
                );
              }
            }
          }
        },
      ),
      { numRuns: 200 },
    );
  });
});

describe('resolveRule — hand-traced example scenarios (review-verified)', () => {
  it('scenario A: specificity tie broken by dimension priority order', () => {
    const employee: EmployeeAttributes = {
      costCentreId: 'CC1',
      processId: 'P1',
      branchId: 'B1',
      departmentId: 'D1',
      designationId: null,
      employmentProfile: 'EP1',
    };
    const rules: TestRule[] = [
      { id: 'default', dimensionValues: {}, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'biometric' },
      { id: 'r_process', dimensionValues: { process: new Set(['P1']) }, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
      { id: 'r_branch', dimensionValues: { branch: new Set(['B1']) }, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
      { id: 'r_desig', dimensionValues: { designation: new Set(['DG1']) }, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
      { id: 'r_cc_miss', dimensionValues: { cost_centre: new Set(['CC2']) }, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
    ];

    const result = resolveRule(rules, employee);

    expect(result.winner?.id).toBe('r_process');
    expect(result.specificityCount).toBe(1);
    expect(result.unresolvedDimensions).toEqual(['designation']);
    expect(
      result.candidates.find((c) => c.rule.id === 'r_branch')?.eliminatedAtStep,
    ).toBe('priority_order');
    expect(
      result.candidates.find((c) => c.rule.id === 'default')?.eliminatedAtStep,
    ).toBe('below_max_specificity');
  });

  it('scenario B: a missing employee attribute excludes the most specific rule, and the tail picks the later effective_from', () => {
    const employee: EmployeeAttributes = {
      costCentreId: null,
      processId: 'P1',
      branchId: 'B1',
      departmentId: null,
      designationId: null,
      employmentProfile: null,
    };
    const rules: TestRule[] = [
      { id: 'default', dimensionValues: {}, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'biometric' },
      { id: 'r_spec3', dimensionValues: { cost_centre: new Set(['CC1']), process: new Set(['P1']), branch: new Set(['B1']) }, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
      { id: 'r_mid_old', dimensionValues: { process: new Set(['P1']), branch: new Set(['B1']) }, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
      { id: 'r_mid_new', dimensionValues: { process: new Set(['P1']), branch: new Set(['B1']) }, effectiveFrom: '2026-06-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' },
    ];

    const result = resolveRule(rules, employee);

    expect(result.winner?.id).toBe('r_mid_new');
    expect(result.specificityCount).toBe(2);
    expect(result.unresolvedDimensions).toEqual([
      'cost_centre',
      'department',
      'designation',
      'employment_profile',
    ]);
    expect(
      result.candidates.find((c) => c.rule.id === 'r_spec3')?.eliminatedAtStep,
    ).toBe('not_candidate');
    expect(
      result.candidates.find((c) => c.rule.id === 'r_mid_old')?.eliminatedAtStep,
    ).toBe('deterministic_tail');
  });

  it('duplicate rule ids: the winner is identified by object reference, not by id, so exactly one candidate reports eliminatedAtStep: null', () => {
    const employee: EmployeeAttributes = {
      costCentreId: null,
      processId: null,
      branchId: null,
      departmentId: null,
      designationId: null,
      employmentProfile: null,
    };
    const ruleA: TestRule = { id: 'dup', dimensionValues: {}, effectiveFrom: '2026-01-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'biometric' };
    const ruleB: TestRule = { id: 'dup', dimensionValues: {}, effectiveFrom: '2026-06-01', createdAt: '2026-01-01T00:00:00.000Z', attendanceSource: 'dialler' };

    const result = resolveRule([ruleA, ruleB], employee);

    const winners = result.candidates.filter((c) => c.eliminatedAtStep === null);
    expect(winners).toHaveLength(1);
    expect(winners[0].rule).toBe(ruleB); // later effective_from wins the tail
    expect(result.winner).toBe(ruleB);
  });

  it('tail id tier: when effective_from and created_at both tie, the lowest id wins', () => {
    // Kills a tail comparator inverted to "highest id wins" deterministically — the property
    // test covering this reaches the id-comparison tier in only ~0.03% of generated cases at
    // the shipped generator settings, so this example does not depend on that probability.
    const employee: EmployeeAttributes = {
      costCentreId: 'CC1',
      processId: null,
      branchId: null,
      departmentId: null,
      designationId: null,
      employmentProfile: null,
    };
    const ruleHigh: TestRule = {
      id: 'zzz-high',
      dimensionValues: { cost_centre: new Set(['CC1']) },
      effectiveFrom: '2026-06-01',
      createdAt: '2026-01-01T00:00:00.000Z',
      attendanceSource: 'biometric',
    };
    const ruleLow: TestRule = {
      id: 'aaa-low',
      dimensionValues: { cost_centre: new Set(['CC1']) },
      effectiveFrom: '2026-06-01',
      createdAt: '2026-01-01T00:00:00.000Z',
      attendanceSource: 'dialler',
    };

    const result = resolveRule([ruleHigh, ruleLow], employee);

    expect(result.winner?.id).toBe('aaa-low');
  });

  it('priority-split boundary: a dimension constrained by ALL tied survivors does not split them, but the next one that splits some-but-not-all does', () => {
    // Kills an inverted split-boundary condition deterministically — the property test
    // covering this shape is seed-dependent (caught in only 4 of 5 runs against an
    // unmutated seed in review testing) because no fast-check seed is pinned in this file.
    // cost_centre is constrained by BOTH r1 and r2 (all survivors) and must NOT split them;
    // process is constrained by r1 only (some but not all) and must split them, so r1 wins.
    const employee: EmployeeAttributes = {
      costCentreId: 'CC1',
      processId: 'P1',
      branchId: 'B1',
      departmentId: null,
      designationId: null,
      employmentProfile: null,
    };
    const r1: TestRule = {
      id: 'z-correct',
      dimensionValues: { cost_centre: new Set(['CC1']), process: new Set(['P1']) },
      effectiveFrom: '2026-01-01',
      createdAt: '2026-01-01T00:00:00.000Z',
      attendanceSource: 'biometric',
    };
    const r2: TestRule = {
      id: 'a-wrong',
      dimensionValues: { cost_centre: new Set(['CC1']), branch: new Set(['B1']) },
      effectiveFrom: '2026-01-01',
      createdAt: '2026-01-01T00:00:00.000Z',
      attendanceSource: 'dialler',
    };

    const result = resolveRule([r1, r2], employee);

    // r1 and r2 both constrain cost_centre (ALL survivors) — must not split on it.
    // Only r1 constrains process (SOME but not all) — must split there, so r1 wins.
    // r2's id ('a-wrong') sorts before r1's ('z-correct'), so if the boundary condition
    // incorrectly breaks out of the walk at cost_centre instead of continuing to process,
    // the tail's id tier would wrongly hand the win to r2.
    expect(result.winner?.id).toBe('z-correct');
  });

  it('no candidate matches at all: winner is null and specificityCount is the -1 sentinel', () => {
    const employee: EmployeeAttributes = {
      costCentreId: 'CC1',
      processId: null,
      branchId: null,
      departmentId: null,
      designationId: null,
      employmentProfile: null,
    };
    // No System_Default_Rule in this array on purpose — every rule constrains a dimension
    // the employee doesn't match, so nothing is a candidate. This should never happen once
    // the System_Default_Rule invariant is enforced at write time, but the pure function must
    // still degrade to winner: null rather than throw or pick something arbitrary.
    const rules: TestRule[] = [
      {
        id: 'r1',
        dimensionValues: { cost_centre: new Set(['CC2']) },
        effectiveFrom: '2026-01-01',
        createdAt: '2026-01-01T00:00:00.000Z',
        attendanceSource: 'biometric',
      },
    ];

    const result = resolveRule(rules, employee);

    expect(result.winner).toBeNull();
    expect(result.specificityCount).toBe(-1);
    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0].eliminatedAtStep).toBe('not_candidate');
  });
});

describe('DIMENSION_PRIORITY_ORDER contract', () => {
  it('the resolver module exports the exact six-dimension order this spec requires', () => {
    // Feature: payroll-attendance-source-rules, decision A1: cost centre, process, branch,
    // department, designation, employment profile. Pinned explicitly so a change to the
    // resolver's exported order is caught here even though the oracle above no longer shares
    // the same reference.
    expect(DIMENSION_PRIORITY_ORDER).toEqual([
      'cost_centre',
      'process',
      'branch',
      'department',
      'designation',
      'employment_profile',
    ]);
  });
});
