import { Router, type Response } from "express";
import { randomUUID } from "crypto";
import type { RowDataPacket } from "mysql2";
import { db } from "../../db/mysql.js";
import { requireAuth, type AuthenticatedRequest } from "../../middleware/authMiddleware.js";
import { requireRole } from "../../middleware/requireRole.js";
import { calculateMetricScore } from "./kpi-score-engine.js";
import { tableExists } from "../../shared/dbHelpers.js";

const router = Router();
const h = (fn: (req: AuthenticatedRequest, res: Response) => Promise<unknown>) =>
  (req: AuthenticatedRequest, res: Response, next: (err?: unknown) => void) => fn(req, res).catch(next);

router.use(requireAuth);

type EmployeeRow = RowDataPacket & { id: string; user_id?: string | null; process_id?: string | null; branch_id?: string | null; reporting_manager_id?: string | null; designation_name?: string | null; department_name?: string | null };

async function getRoles(userId: string): Promise<string[]> {
  const [rows] = await db.execute<RowDataPacket[]>("SELECT role_key FROM user_roles WHERE user_id=? AND active_status=1", [userId]);
  return rows.map((r) => String(r.role_key));
}
function has(roles: string[], allowed: string[]) { return allowed.some((r) => roles.includes(r) || (r === "manager" && roles.includes("process_manager")) || (r === "tl" && roles.includes("team_leader"))); }
async function me(userId: string): Promise<EmployeeRow | null> { const [rows] = await db.execute<EmployeeRow[]>("SELECT * FROM employees WHERE user_id=? AND active_status=1 LIMIT 1", [userId]); return rows[0] ?? null; }
async function emp(id: string): Promise<EmployeeRow | null> { const [rows] = await db.execute<EmployeeRow[]>("SELECT e.*, d.designation_name, dep.department_name FROM employees e LEFT JOIN designations d ON d.id=e.designation_id LEFT JOIN departments dep ON dep.id=e.department_id WHERE e.id=? LIMIT 1", [id]); return rows[0] ?? null; }
async function canAccessEmployee(req: AuthenticatedRequest, employeeId: string) {
  const roles = await getRoles(req.authUser!.id);
  if (has(roles, ["admin", "hr", "ceo"])) return true;
  const target = await emp(employeeId); const caller = await me(req.authUser!.id);
  if (!target || !caller) return false;
  if (target.id === caller.id) return true;
  if (has(roles, ["manager", "process_manager", "tl", "team_leader"])) return target.reporting_manager_id === caller.id || (!!caller.process_id && target.process_id === caller.process_id);
  if (has(roles, ["branch_head"])) return !!caller.branch_id && target.branch_id === caller.branch_id;
  return false;
}
function inferRoleCodes(row: EmployeeRow): string[] {
  const text = `${row.designation_name ?? ""} ${row.department_name ?? ""}`.toLowerCase(); const roles = new Set<string>(["employee"]);
  if (text.includes("quality") || text.includes("qa")) roles.add("qa"); if (text.includes("trainer") || text.includes("training")) roles.add("trainer"); if (text.includes("wfm")) roles.add("wfm"); if (text.includes("payroll")) roles.add("payroll"); if (text.includes("finance")) roles.add("finance"); if (text.includes("branch head")) roles.add("branch_head"); if (text.includes("manager")) roles.add("process_manager"); if (text.includes("tl") || text.includes("team leader")) roles.add("team_leader"); if (text.includes("analyst")) roles.add("analyst"); if (text.includes("executive") || text.includes("agent")) roles.add("agent"); return Array.from(roles);
}
async function inbox(roleKey: string, title: string, description: string, priority = "normal") { try { const [users] = await db.execute<RowDataPacket[]>("SELECT DISTINCT user_id FROM user_roles WHERE role_key=? AND active_status=1 LIMIT 25", [roleKey]); for (const u of users) await db.execute("INSERT INTO work_inbox_item (id,user_id,type,title,description,entity_type,action_url,priority) VALUES (?,?, 'KPI_ACTION', ?, ?, 'kpi', '/kpi-config', ?)", [randomUUID(), u.user_id, title, description, priority]); } catch {} }
async function journey(employeeId: string, eventType: string, description: string, userId?: string) { try { await db.execute("INSERT INTO employee_journey_log (id,employee_id,event_type,event_date,description,module,triggered_by,metadata) VALUES (?,?,?,CURDATE(),?,'KPI',?,?)", [randomUUID(), employeeId, eventType, description, userId ?? null, JSON.stringify({})]); } catch {} }
function json(v: unknown) { if (!v) return null; if (typeof v === "object") return v as Record<string, unknown>; try { return JSON.parse(String(v)); } catch { return null; } }

router.get("/process-templates", requireRole("admin", "hr", "manager", "process_manager"), h(async (req, res) => {
  const { process_id, status } = req.query as { process_id?: string; status?: string }; const conds: string[] = []; const params: unknown[] = [];
  if (process_id) { conds.push("process_id=?"); params.push(process_id); } if (status) { conds.push("status=?"); params.push(status); }
  const [rows] = await db.execute<RowDataPacket[]>(`SELECT * FROM kpi_process_template ${conds.length ? `WHERE ${conds.join(" AND ")}` : ""} ORDER BY effective_from DESC`, params);
  res.json({ success: true, data: rows });
}));
router.post("/process-templates", requireRole("admin", "hr", "process_manager"), h(async (req, res) => {
  const { template_name, process_id, branch_id, process_type, effective_from, effective_to } = req.body; if (!template_name || !process_id || !effective_from) return res.status(400).json({ success: false, error: "template_name, process_id and effective_from required" });
  const id = randomUUID(); await db.execute("INSERT INTO kpi_process_template (id,template_name,process_id,branch_id,process_type,effective_from,effective_to,created_by) VALUES (?,?,?,?,?,?,?,?)", [id, template_name, process_id, branch_id ?? null, process_type ?? null, effective_from, effective_to ?? null, req.authUser!.id]); res.status(201).json({ success: true, data: { id } });
}));
router.post("/process-templates/:id/activate", requireRole("admin", "hr", "process_manager"), h(async (req, res) => {
  const [roles] = await db.execute<RowDataPacket[]>("SELECT id, role_code FROM kpi_role_template WHERE process_template_id=? AND status <> 'inactive'", [req.params.id]);
  for (const r of roles) { const [sum] = await db.execute<RowDataPacket[]>("SELECT COALESCE(SUM(weightage),0) AS total FROM kpi_role_template_metric WHERE role_template_id=? AND active_status=1", [r.id]); const total = Number(sum[0]?.total ?? 0); if (Math.round(total * 100) / 100 !== 100) return res.status(400).json({ success: false, error: `Role ${r.role_code} weightage must equal 100`, total }); }
  await db.execute("UPDATE kpi_process_template SET status='active', approved_by=?, updated_at=NOW() WHERE id=?", [req.authUser!.id, req.params.id]); res.json({ success: true });
}));
router.post("/process-templates/:id/archive", requireRole("admin", "hr"), h(async (req, res) => { await db.execute("UPDATE kpi_process_template SET status='archived', updated_at=NOW() WHERE id=?", [req.params.id]); res.json({ success: true }); }));
router.get("/role-templates", requireRole("admin", "hr", "manager", "process_manager"), h(async (req, res) => { const { process_template_id, role_code } = req.query as { process_template_id?: string; role_code?: string }; const conds: string[] = []; const params: unknown[] = []; if (process_template_id) { conds.push("process_template_id=?"); params.push(process_template_id); } if (role_code) { conds.push("role_code=?"); params.push(role_code); } const [rows] = await db.execute<RowDataPacket[]>(`SELECT * FROM kpi_role_template ${conds.length ? `WHERE ${conds.join(" AND ")}` : ""} ORDER BY role_code`, params); res.json({ success: true, data: rows }); }));
router.post("/role-templates", requireRole("admin", "hr", "process_manager"), h(async (req, res) => { const { process_template_id, role_code, role_name, eligibility_rule_json, new_joiner_rule_json, transfer_rule_json } = req.body; if (!process_template_id || !role_code) return res.status(400).json({ success: false, error: "process_template_id and role_code required" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_role_template (id,process_template_id,role_code,role_name,eligibility_rule_json,new_joiner_rule_json,transfer_rule_json) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE role_name=VALUES(role_name), eligibility_rule_json=VALUES(eligibility_rule_json), updated_at=NOW()", [id, process_template_id, role_code, role_name ?? role_code, JSON.stringify(eligibility_rule_json ?? {}), JSON.stringify(new_joiner_rule_json ?? {}), JSON.stringify(transfer_rule_json ?? {})]); res.status(201).json({ success: true, data: { id } }); }));
router.post("/role-templates/:id/metrics", requireRole("admin", "hr", "process_manager"), h(async (req, res) => { const { metric_id, target_type, target_value, min_value, max_value, weightage, fatal_rule_json, threshold_rule_json, display_order } = req.body; if (!metric_id || weightage === undefined) return res.status(400).json({ success: false, error: "metric_id and weightage required" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_role_template_metric (id,role_template_id,metric_id,target_type,target_value,min_value,max_value,weightage,fatal_rule_json,threshold_rule_json,display_order) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE target_type=VALUES(target_type), target_value=VALUES(target_value), min_value=VALUES(min_value), max_value=VALUES(max_value), weightage=VALUES(weightage), fatal_rule_json=VALUES(fatal_rule_json), threshold_rule_json=VALUES(threshold_rule_json), display_order=VALUES(display_order), updated_at=NOW()", [id, req.params.id, metric_id, target_type ?? "higher_better", target_value ?? null, min_value ?? null, max_value ?? null, weightage, JSON.stringify(fatal_rule_json ?? {}), JSON.stringify(threshold_rule_json ?? {}), display_order ?? 0]); res.status(201).json({ success: true, data: { id } }); }));
router.get("/source-mappings", requireRole("admin", "hr", "manager", "process_manager"), h(async (_req, res) => { const [rows] = await db.execute<RowDataPacket[]>("SELECT * FROM kpi_data_source_mapping WHERE active_status=1 ORDER BY process_id, role_code"); res.json({ success: true, data: rows }); }));
router.post("/source-mappings", requireRole("admin", "hr", "process_manager"), h(async (req, res) => { const { metric_id, process_id, role_code, source_type, source_database, source_table, source_field, join_key, formula_sql, api_endpoint, upload_template_code, refresh_frequency } = req.body; if (!metric_id || !source_type) return res.status(400).json({ success: false, error: "metric_id and source_type required" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_data_source_mapping (id,metric_id,process_id,role_code,source_type,source_database,source_table,source_field,join_key,formula_sql,api_endpoint,upload_template_code,refresh_frequency) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", [id, metric_id, process_id ?? null, role_code ?? null, source_type, source_database ?? null, source_table ?? null, source_field ?? null, join_key ?? null, formula_sql ?? null, api_endpoint ?? null, upload_template_code ?? null, refresh_frequency ?? "monthly"]); res.status(201).json({ success: true, data: { id } }); }));

router.post("/assignments/auto-assign", requireRole("admin", "hr"), h(async (req, res) => {
  const [employees] = await db.execute<EmployeeRow[]>("SELECT e.*, d.designation_name, dep.department_name FROM employees e LEFT JOIN designations d ON d.id=e.designation_id LEFT JOIN departments dep ON dep.id=e.department_id WHERE e.active_status=1 AND e.process_id IS NOT NULL"); let assigned = 0; let missing = 0;
  for (const e of employees) { const roles = inferRoleCodes(e); const ph = roles.map(() => "?").join(","); const [templates] = await db.execute<RowDataPacket[]>(`SELECT rt.id, rt.role_code FROM kpi_role_template rt JOIN kpi_process_template pt ON pt.id=rt.process_template_id WHERE pt.process_id=? AND pt.status='active' AND rt.status='active' AND rt.role_code IN (${ph}) ORDER BY FIELD(rt.role_code, ${ph}), pt.effective_from DESC LIMIT 1`, [e.process_id, ...roles, ...roles]); if (!templates[0]) { missing++; await inbox("hr", "KPI role template missing", `No active KPI role template found for employee ${e.id} / process ${e.process_id}.`, "high"); continue; } await db.execute("INSERT INTO kpi_employee_assignment (id,employee_id,process_id,role_template_id,effective_from,assignment_type,created_by) VALUES (UUID(),?,?,?,CURDATE(),'auto',?) ON DUPLICATE KEY UPDATE effective_to=NULL", [e.id, e.process_id, templates[0].id, req.authUser!.id]); await journey(e.id, "kpi_assignment_created", `KPI template assigned: ${templates[0].role_code}`, req.authUser!.id); assigned++; }
  res.json({ success: true, data: { assigned, missing } });
}));
router.post("/assignments/manual", requireRole("admin", "hr", "process_manager"), h(async (req, res) => { const { employee_id, process_id, role_template_id, effective_from, effective_to } = req.body; if (!employee_id || !process_id || !role_template_id || !effective_from) return res.status(400).json({ success: false, error: "employee_id, process_id, role_template_id and effective_from required" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_employee_assignment (id,employee_id,process_id,role_template_id,effective_from,effective_to,assignment_type,created_by) VALUES (?,?,?,?,?,?,'manual',?)", [id, employee_id, process_id, role_template_id, effective_from, effective_to ?? null, req.authUser!.id]); await journey(employee_id, "kpi_assignment_created", "Manual KPI template assignment created", req.authUser!.id); res.status(201).json({ success: true, data: { id } }); }));
router.post("/score-periods", requireRole("admin", "hr", "manager"), h(async (req, res) => { const { period_type, period_start, period_end } = req.body; if (!period_start || !period_end) return res.status(400).json({ success: false, error: "period_start and period_end required" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_score_period (id,period_type,period_start,period_end) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE status=status", [id, period_type ?? "monthly", period_start, period_end]); res.status(201).json({ success: true, data: { id } }); }));
router.get("/score-periods", requireRole("admin", "hr", "manager", "employee"), h(async (_req, res) => { const [rows] = await db.execute<RowDataPacket[]>("SELECT * FROM kpi_score_period ORDER BY period_start DESC LIMIT 100"); res.json({ success: true, data: rows }); }));
router.post("/score-periods/:id/calculate", requireRole("admin", "hr", "manager"), h(async (req, res) => {
  const [periodRows] = await db.execute<RowDataPacket[]>("SELECT * FROM kpi_score_period WHERE id=? AND status <> 'locked' LIMIT 1", [req.params.id]); if (!periodRows[0]) return res.status(404).json({ success: false, error: "Open score period not found" }); const legacyScoreExists = await tableExists("kpi_score");
  const [rows] = await db.execute<RowDataPacket[]>("SELECT ea.employee_id, ea.process_id, rt.role_code, rtm.metric_id, rtm.target_type, rtm.target_value, rtm.min_value, rtm.max_value, rtm.weightage, rtm.fatal_rule_json, rtm.threshold_rule_json FROM kpi_employee_assignment ea JOIN kpi_role_template rt ON rt.id=ea.role_template_id JOIN kpi_role_template_metric rtm ON rtm.role_template_id=rt.id AND rtm.active_status=1 WHERE ea.effective_from <= ? AND (ea.effective_to IS NULL OR ea.effective_to >= ?)", [periodRows[0].period_end, periodRows[0].period_start]); let calculated = 0; let missing = 0;
  for (const row of rows) { let actual: number | null = null; if (legacyScoreExists) { const [sr] = await db.execute<RowDataPacket[]>("SELECT actual_value FROM kpi_score WHERE employee_id=? AND metric_id=? AND period=DATE_FORMAT(?, '%Y-%m') LIMIT 1", [row.employee_id, row.metric_id, periodRows[0].period_start]); actual = sr[0]?.actual_value ?? null; } const score = calculateMetricScore({ scoringType: row.target_type, actualValue: actual, targetValue: row.target_value, minValue: row.min_value, maxValue: row.max_value, weightage: row.weightage, fatalRule: json(row.fatal_rule_json), thresholdRule: json(row.threshold_rule_json) }); if (score.status === "missing_source") { missing++; await inbox("hr", "KPI source data missing", `Actual KPI value missing for employee ${row.employee_id}, metric ${row.metric_id}.`, "high"); } await db.execute("INSERT INTO kpi_score_detail (id,period_id,employee_id,process_id,role_code,metric_id,target_value,actual_value,metric_score,weighted_score,calculation_note,status,calculated_at) VALUES (UUID(),?,?,?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE actual_value=VALUES(actual_value), metric_score=VALUES(metric_score), weighted_score=VALUES(weighted_score), calculation_note=VALUES(calculation_note), status=VALUES(status), calculated_at=NOW()", [req.params.id, row.employee_id, row.process_id, row.role_code, row.metric_id, row.target_value, actual, score.metricScore, score.weightedScore, score.note, score.status]); calculated++; }
  await db.execute("INSERT INTO kpi_score_summary (id,period_id,employee_id,process_id,role_code,final_score,rating,status) SELECT UUID(), period_id, employee_id, process_id, role_code, ROUND(SUM(weighted_score),2), '', 'draft' FROM kpi_score_detail WHERE period_id=? GROUP BY period_id, employee_id, process_id, role_code ON DUPLICATE KEY UPDATE final_score=VALUES(final_score), status='draft'", [req.params.id]); await db.execute("UPDATE kpi_score_summary SET rating = CASE WHEN final_score >= 95 THEN 'Outstanding' WHEN final_score >= 85 THEN 'Exceeds' WHEN final_score >= 75 THEN 'Meets' WHEN final_score >= 60 THEN 'Needs Improvement' ELSE 'Critical' END WHERE period_id=?", [req.params.id]); await db.execute("UPDATE kpi_score_period SET status='calculated' WHERE id=?", [req.params.id]); res.json({ success: true, data: { calculated, missing } });
}));
router.post("/score-periods/:id/review", requireRole("admin", "hr", "manager"), h(async (req, res) => { await db.execute("UPDATE kpi_score_period SET status='reviewed' WHERE id=? AND status <> 'locked'", [req.params.id]); await db.execute("UPDATE kpi_score_summary SET status='reviewed', reviewed_by=?, reviewed_at=NOW() WHERE period_id=? AND status <> 'locked'", [req.authUser!.id, req.params.id]); res.json({ success: true }); }));
router.post("/score-periods/:id/lock", requireRole("admin", "hr"), h(async (req, res) => { const [pending] = await db.execute<RowDataPacket[]>("SELECT COUNT(*) AS total FROM kpi_manual_adjustment WHERE period_id=? AND status='pending'", [req.params.id]); if (Number(pending[0]?.total ?? 0) > 0) return res.status(400).json({ success: false, error: "Pending manual adjustments must be resolved before locking" }); await db.execute("UPDATE kpi_score_period SET status='locked', locked_by=?, locked_at=NOW() WHERE id=?", [req.authUser!.id, req.params.id]); await db.execute("UPDATE kpi_score_summary SET status='locked', locked_at=NOW() WHERE period_id=?", [req.params.id]); res.json({ success: true }); }));
router.get("/scorecards/my", requireRole("employee", "admin", "hr", "manager"), h(async (req, res) => { const caller = await me(req.authUser!.id); if (!caller) return res.json({ success: true, data: [] }); const [rows] = await db.execute<RowDataPacket[]>("SELECT * FROM kpi_score_summary WHERE employee_id=? ORDER BY locked_at DESC, reviewed_at DESC", [caller.id]); res.json({ success: true, data: rows }); }));
router.get("/scorecards/employee/:employeeId", requireRole("admin", "hr", "manager", "process_manager", "branch_head", "employee"), h(async (req, res) => { if (!(await canAccessEmployee(req, req.params.employeeId))) return res.status(403).json({ success: false, message: "Forbidden: employee KPI out of scope" }); const [rows] = await db.execute<RowDataPacket[]>("SELECT * FROM kpi_score_summary WHERE employee_id=? ORDER BY locked_at DESC, reviewed_at DESC", [req.params.employeeId]); res.json({ success: true, data: rows }); }));
router.get("/scorecards/process", requireRole("admin", "hr", "manager", "process_manager"), h(async (req, res) => { const processId = req.query.process_id as string | undefined; const roles = await getRoles(req.authUser!.id); const caller = await me(req.authUser!.id); const conds: string[] = []; const params: unknown[] = []; if (processId) { conds.push("kss.process_id=?"); params.push(processId); } if (!has(roles, ["admin", "hr", "ceo"])) { if (!caller?.process_id) return res.json({ success: true, data: [] }); conds.push("kss.process_id=?"); params.push(caller.process_id); } const [rows] = await db.execute<RowDataPacket[]>(`SELECT process_id, role_code, AVG(final_score) AS avg_score, COUNT(*) AS employees FROM kpi_score_summary kss ${conds.length ? `WHERE ${conds.join(" AND ")}` : ""} GROUP BY process_id, role_code`, params); res.json({ success: true, data: rows }); }));
router.post("/manual-adjustments", requireRole("admin", "hr", "manager"), h(async (req, res) => { const { period_id, employee_id, metric_id, old_actual_value, new_actual_value, reason } = req.body; if (!period_id || !employee_id || !metric_id || new_actual_value === undefined || !reason) return res.status(400).json({ success: false, error: "period_id, employee_id, metric_id, new_actual_value and reason required" }); if (!(await canAccessEmployee(req, employee_id))) return res.status(403).json({ success: false, message: "Forbidden: adjustment out of scope" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_manual_adjustment (id,period_id,employee_id,metric_id,old_actual_value,new_actual_value,reason,requested_by) VALUES (?,?,?,?,?,?,?,?)", [id, period_id, employee_id, metric_id, old_actual_value ?? null, new_actual_value, reason, req.authUser!.id]); await inbox("hr", "KPI manual adjustment pending", reason); res.status(201).json({ success: true, data: { id } }); }));
router.post("/manual-adjustments/:id/approve", requireRole("admin", "hr"), h(async (req, res) => { await db.execute("UPDATE kpi_manual_adjustment SET status='approved', approved_by=?, approved_at=NOW() WHERE id=? AND status='pending'", [req.authUser!.id, req.params.id]); res.json({ success: true }); }));
router.post("/review-actions", requireRole("admin", "hr", "manager"), h(async (req, res) => { const { period_id, employee_id, action_type, title, description, owner_user_id, due_date } = req.body; if (!employee_id || !action_type || !title) return res.status(400).json({ success: false, error: "employee_id, action_type and title required" }); if (!(await canAccessEmployee(req, employee_id))) return res.status(403).json({ success: false, message: "Forbidden: review action out of scope" }); const id = randomUUID(); await db.execute("INSERT INTO kpi_review_action (id,period_id,employee_id,action_type,title,description,owner_user_id,due_date,created_by) VALUES (?,?,?,?,?,?,?,?,?)", [id, period_id ?? null, employee_id, action_type, title, description ?? null, owner_user_id ?? null, due_date ?? null, req.authUser!.id]); await journey(employee_id, `kpi_${action_type}`, title, req.authUser!.id); res.status(201).json({ success: true, data: { id } }); }));

export { router as kpiProcessRoleRouter };
