import path from "path";
import { createFillableEpfTemplateFromBase } from "../src/modules/employees/pdfAcroFormFill.service.js";

const inputPath = process.env.EPF_BASE_PDF_PATH ?? path.resolve(process.cwd(), "..", ".codex-tmp", "original-docs", "EPF_Declaration_Form.pdf-1.pdf");
const outputPath = process.env.EPF_ACROFORM_OUTPUT_PATH ?? path.resolve(process.cwd(), "private-storage", "document-templates", "epf-form-11-acroform-master.pdf");

// Initial master-template field rectangles. These are used only to create named AcroForm fields once.
// Runtime generation fills by field name and does not use coordinate drawText for EPF.
const fields = [
  { field_key: "employee_name", pdf_field_name: "employee_name", field_type: "text", page_no: 1, x: 168, y: 550, width: 405, height: 16 },
  { field_key: "father_or_spouse_name", pdf_field_name: "father_or_spouse_name", field_type: "text", page_no: 1, x: 168, y: 434, width: 405, height: 16 },
  { field_key: "relationship_father", pdf_field_name: "relationship_father", field_type: "checkbox", page_no: 1, x: 246, y: 373, width: 10, height: 10 },
  { field_key: "relationship_husband", pdf_field_name: "relationship_husband", field_type: "checkbox", page_no: 1, x: 318, y: 373, width: 10, height: 10 },
  { field_key: "dob_day", pdf_field_name: "dob_day", field_type: "text", page_no: 1, x: 187, y: 500, width: 45, height: 15 },
  { field_key: "dob_month", pdf_field_name: "dob_month", field_type: "text", page_no: 1, x: 232, y: 500, width: 45, height: 15 },
  { field_key: "dob_year_1", pdf_field_name: "dob_year_1", field_type: "text", page_no: 1, x: 278, y: 500, width: 22, height: 15 },
  { field_key: "dob_year_2", pdf_field_name: "dob_year_2", field_type: "text", page_no: 1, x: 301, y: 500, width: 22, height: 15 },
  { field_key: "dob_year_3", pdf_field_name: "dob_year_3", field_type: "text", page_no: 1, x: 324, y: 500, width: 22, height: 15 },
  { field_key: "dob_year_4", pdf_field_name: "dob_year_4", field_type: "text", page_no: 1, x: 347, y: 500, width: 22, height: 15 },
  { field_key: "gender_male", pdf_field_name: "gender_male", field_type: "checkbox", page_no: 1, x: 214, y: 313, width: 10, height: 10 },
  { field_key: "gender_female", pdf_field_name: "gender_female", field_type: "checkbox", page_no: 1, x: 280, y: 313, width: 10, height: 10 },
  { field_key: "gender_other", pdf_field_name: "gender_other", field_type: "checkbox", page_no: 1, x: 342, y: 313, width: 10, height: 10 },
  { field_key: "mobile_number", pdf_field_name: "mobile_number", field_type: "text", page_no: 1, x: 139, y: 265, width: 340, height: 16 },
  { field_key: "email", pdf_field_name: "email", field_type: "text", page_no: 1, x: 139, y: 210, width: 435, height: 16 },
  { field_key: "previous_pf_member_yes", pdf_field_name: "previous_pf_member_yes", field_type: "checkbox", page_no: 1, x: 294, y: 154, width: 10, height: 10 },
  { field_key: "previous_pf_member_no", pdf_field_name: "previous_pf_member_no", field_type: "checkbox", page_no: 1, x: 400, y: 154, width: 10, height: 10 },
  { field_key: "previous_eps_member_yes", pdf_field_name: "previous_eps_member_yes", field_type: "checkbox", page_no: 1, x: 294, y: 122, width: 10, height: 10 },
  { field_key: "previous_eps_member_no", pdf_field_name: "previous_eps_member_no", field_type: "checkbox", page_no: 1, x: 400, y: 122, width: 10, height: 10 },
  { field_key: "uan", pdf_field_name: "uan", field_type: "text", page_no: 2, x: 201, y: 715, width: 315, height: 16 },
  { field_key: "previous_pf_account_number", pdf_field_name: "previous_pf_account_number", field_type: "text", page_no: 2, x: 191, y: 686, width: 350, height: 16 },
  { field_key: "date_of_exit_previous_day", pdf_field_name: "date_of_exit_previous_day", field_type: "text", page_no: 2, x: 207, y: 655, width: 45, height: 15 },
  { field_key: "date_of_exit_previous_month", pdf_field_name: "date_of_exit_previous_month", field_type: "text", page_no: 2, x: 252, y: 655, width: 45, height: 15 },
  { field_key: "date_of_exit_previous_year", pdf_field_name: "date_of_exit_previous_year", field_type: "text", page_no: 2, x: 297, y: 655, width: 90, height: 15 },
  { field_key: "scheme_certificate_number", pdf_field_name: "scheme_certificate_number", field_type: "text", page_no: 2, x: 345, y: 612, width: 145, height: 14 },
  { field_key: "ppo_number", pdf_field_name: "ppo_number", field_type: "text", page_no: 2, x: 322, y: 598, width: 165, height: 14 },
  { field_key: "international_worker_yes", pdf_field_name: "international_worker_yes", field_type: "checkbox", page_no: 2, x: 258, y: 522, width: 10, height: 10 },
  { field_key: "international_worker_no", pdf_field_name: "international_worker_no", field_type: "checkbox", page_no: 2, x: 330, y: 522, width: 10, height: 10 },
  { field_key: "country_of_origin", pdf_field_name: "country_of_origin", field_type: "text", page_no: 2, x: 184, y: 482, width: 160, height: 15 },
  { field_key: "passport_number", pdf_field_name: "passport_number", field_type: "text", page_no: 2, x: 185, y: 408, width: 160, height: 15 },
  { field_key: "passport_valid_from_day", pdf_field_name: "passport_valid_from_day", field_type: "text", page_no: 2, x: 208, y: 349, width: 45, height: 15 },
  { field_key: "passport_valid_from_month", pdf_field_name: "passport_valid_from_month", field_type: "text", page_no: 2, x: 253, y: 349, width: 45, height: 15 },
  { field_key: "passport_valid_from_year", pdf_field_name: "passport_valid_from_year", field_type: "text", page_no: 2, x: 298, y: 349, width: 90, height: 15 },
  { field_key: "passport_valid_to_day", pdf_field_name: "passport_valid_to_day", field_type: "text", page_no: 2, x: 208, y: 301, width: 45, height: 15 },
  { field_key: "passport_valid_to_month", pdf_field_name: "passport_valid_to_month", field_type: "text", page_no: 2, x: 253, y: 301, width: 45, height: 15 },
  { field_key: "passport_valid_to_year", pdf_field_name: "passport_valid_to_year", field_type: "text", page_no: 2, x: 298, y: 301, width: 90, height: 15 },
  { field_key: "education_illiterate", pdf_field_name: "education_illiterate", field_type: "checkbox", page_no: 2, x: 162, y: 251, width: 10, height: 10 },
  { field_key: "education_non_matric", pdf_field_name: "education_non_matric", field_type: "checkbox", page_no: 2, x: 226, y: 251, width: 10, height: 10 },
  { field_key: "education_matric", pdf_field_name: "education_matric", field_type: "checkbox", page_no: 2, x: 278, y: 251, width: 10, height: 10 },
  { field_key: "education_senior_secondary", pdf_field_name: "education_senior_secondary", field_type: "checkbox", page_no: 2, x: 347, y: 251, width: 10, height: 10 },
  { field_key: "education_graduate", pdf_field_name: "education_graduate", field_type: "checkbox", page_no: 2, x: 407, y: 251, width: 10, height: 10 },
  { field_key: "education_post_graduate", pdf_field_name: "education_post_graduate", field_type: "checkbox", page_no: 2, x: 464, y: 251, width: 10, height: 10 },
  { field_key: "education_doctor", pdf_field_name: "education_doctor", field_type: "checkbox", page_no: 2, x: 516, y: 251, width: 10, height: 10 },
  { field_key: "education_technical_professional", pdf_field_name: "education_technical_professional", field_type: "checkbox", page_no: 2, x: 558, y: 251, width: 10, height: 10 },
  { field_key: "marital_status_married", pdf_field_name: "marital_status_married", field_type: "checkbox", page_no: 2, x: 169, y: 198, width: 10, height: 10 },
  { field_key: "marital_status_unmarried", pdf_field_name: "marital_status_unmarried", field_type: "checkbox", page_no: 2, x: 238, y: 198, width: 10, height: 10 },
  { field_key: "marital_status_widow_widower", pdf_field_name: "marital_status_widow_widower", field_type: "checkbox", page_no: 2, x: 325, y: 198, width: 10, height: 10 },
  { field_key: "marital_status_divorcee", pdf_field_name: "marital_status_divorcee", field_type: "checkbox", page_no: 2, x: 395, y: 198, width: 10, height: 10 },
  { field_key: "specially_abled_yes", pdf_field_name: "specially_abled_yes", field_type: "checkbox", page_no: 2, x: 162, y: 145, width: 10, height: 10 },
  { field_key: "specially_abled_no", pdf_field_name: "specially_abled_no", field_type: "checkbox", page_no: 2, x: 213, y: 145, width: 10, height: 10 },
  { field_key: "disability_locomotive", pdf_field_name: "disability_locomotive", field_type: "checkbox", page_no: 2, x: 356, y: 113, width: 10, height: 10 },
  { field_key: "disability_visual", pdf_field_name: "disability_visual", field_type: "checkbox", page_no: 2, x: 424, y: 113, width: 10, height: 10 },
  { field_key: "disability_hearing", pdf_field_name: "disability_hearing", field_type: "checkbox", page_no: 2, x: 493, y: 113, width: 10, height: 10 },
  { field_key: "kyc_bank_account_number", pdf_field_name: "kyc_bank_account_number", field_type: "text", page_no: 3, x: 365, y: 755, width: 100, height: 14 },
  { field_key: "kyc_bank_ifsc", pdf_field_name: "kyc_bank_ifsc", field_type: "text", page_no: 3, x: 485, y: 755, width: 80, height: 14 },
  { field_key: "kyc_aadhaar_name", pdf_field_name: "kyc_aadhaar_name", field_type: "text", page_no: 3, x: 244, y: 717, width: 120, height: 14 },
  { field_key: "kyc_aadhaar_number", pdf_field_name: "kyc_aadhaar_number", field_type: "text", page_no: 3, x: 365, y: 717, width: 100, height: 14 },
  { field_key: "kyc_pan_name", pdf_field_name: "kyc_pan_name", field_type: "text", page_no: 3, x: 244, y: 693, width: 120, height: 14 },
  { field_key: "kyc_pan_number", pdf_field_name: "kyc_pan_number", field_type: "text", page_no: 3, x: 365, y: 693, width: 100, height: 14 },
  { field_key: "place", pdf_field_name: "place", field_type: "text", page_no: 3, x: 90, y: 377, width: 120, height: 14 },
  { field_key: "signature_date_day", pdf_field_name: "signature_date_day", field_type: "text", page_no: 3, x: 90, y: 394, width: 18, height: 14 },
  { field_key: "signature_date_month", pdf_field_name: "signature_date_month", field_type: "text", page_no: 3, x: 112, y: 394, width: 18, height: 14 },
  { field_key: "signature_date_year", pdf_field_name: "signature_date_year", field_type: "text", page_no: 3, x: 134, y: 394, width: 36, height: 14 },
  { field_key: "employee_signature", pdf_field_name: "employee_signature", field_type: "text", page_no: 3, x: 475, y: 394, width: 90, height: 14 },
  { field_key: "employer_name", pdf_field_name: "employer_name", field_type: "text", page_no: 3, x: 195, y: 337, width: 170, height: 14 },
  { field_key: "employer_signature", pdf_field_name: "employer_signature", field_type: "text", page_no: 3, x: 340, y: 102, width: 180, height: 14 },
  { field_key: "doj_day", pdf_field_name: "doj_day", field_type: "text", page_no: 3, x: 360, y: 337, width: 18, height: 14 },
  { field_key: "doj_month", pdf_field_name: "doj_month", field_type: "text", page_no: 3, x: 382, y: 337, width: 18, height: 14 },
  { field_key: "doj_year", pdf_field_name: "doj_year", field_type: "text", page_no: 3, x: 404, y: 337, width: 36, height: 14 },
];

await createFillableEpfTemplateFromBase({ inputPath, outputPath, fieldMaps: fields });
console.log(JSON.stringify({ success: true, inputPath, outputPath, fieldCount: fields.length }, null, 2));
