/**
 * Generates the role_page_access seed for the 12 role dashboards, mechanically derived
 * from the dashboard access registry. READ-ONLY: it writes a .sql file, it does not
 * touch the database.
 *
 * Why generated rather than hand-written: a role must pass BOTH the code registry
 * (ProtectedRoute / requireDashboardEntitlement) and role_page_access
 * (WorkforcePageGate). Those two drifted apart until they disagreed for 14 of 27 roles
 * — branch_head, for instance, ended up with an empty intersection and could open
 * nothing at all. Deriving one from the other removes the drift by construction.
 *
 * Usage:  npx tsx scripts/generate-dashboard-page-grants.ts
 * Output: backend/sql/600_role_dashboard_page_grants.sql   (NOT executed)
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  DASHBOARD_ACCESS_REGISTRY,
  canAccessDashboard,
  type DashboardCode,
} from "../src/shared/dashboardAccessRegistry.js";
import { WORKFORCE_ROLE_CATALOG } from "../src/shared/workforceRoleCatalog.js";

const OUT = resolve(import.meta.dirname, "../sql/600_role_dashboard_page_grants.sql");

function main() {
  const rows: Array<{ role: string; page: string }> = [];

  // Iterate assignable roles x dashboards and ask canAccessDashboard — the SAME function
  // ProtectedRoute and requireDashboardEntitlement use. Testing literal membership in
  // allowedRoleKeys instead misses alias-based entitlement: payroll_admin is entitled to
  // PAYROLL_HR_DASHBOARD via the payroll alias but appears in no allowedRoleKeys list, so
  // it was left blocked by the page gate on the first run of this generator.
  //
  // Roles absent from workforce_role_catalog are skipped: user_roles.role_key is FK-bound
  // to that table, so a grant for an unassignable key is a dead row.
  for (const role of WORKFORCE_ROLE_CATALOG) {
    for (const code of Object.keys(DASHBOARD_ACCESS_REGISTRY) as DashboardCode[]) {
      if (!canAccessDashboard(code, [role])) continue;
      rows.push({ role, page: DASHBOARD_ACCESS_REGISTRY[code].pageCode });
    }
  }

  rows.sort((a, b) => a.role.localeCompare(b.role) || a.page.localeCompare(b.page));

  // Deliberately does NOT set can_export. An earlier revision derived it from
  // registry.permissions.export, which on a dry run turned out to grant export rights to
  // 15 roles that did not have them and to REMOVE super_admin's export on the self
  // dashboard. Export is a separate permission decision; this migration exists only to
  // make the page gate agree with the role registry about who can VIEW a dashboard.
  const values = rows
    .map((r) => `  (UUID(), '${r.role}', '${r.page}', 1, 1)`)
    .join(",\n");

  const sql = `-- 600_role_dashboard_page_grants.sql
-- GENERATED by scripts/generate-dashboard-page-grants.ts — do not edit by hand.
-- Regenerate after changing allowedRoleKeys in shared/dashboardAccessRegistry.ts.
--
-- Purpose: align role_page_access (enforced by WorkforcePageGate) with the dashboard
-- access registry (enforced by ProtectedRoute and requireDashboardEntitlement). Both
-- gates must pass; they had drifted until 14 of 27 roles disagreed and several roles —
-- branch_head among them — could open no dashboard at all.
--
-- Additive and idempotent: upserts on uq_role_page (role_key, page_code).
-- Grants only. Revokes nothing, deletes nothing, and touches no page outside the
-- ${Object.keys(DASHBOARD_ACCESS_REGISTRY).length} role-dashboard page codes.
--
-- Covers ${rows.length} (role, page) pairs for ${new Set(rows.map((r) => r.role)).size} assignable roles.
--
-- NOT EXECUTED AUTOMATICALLY. Review, then run against the target schema.

-- can_export is intentionally untouched: this migration decides VIEW access only.
INSERT INTO role_page_access (id, role_key, page_code, can_view, active_status)
VALUES
${values}
ON DUPLICATE KEY UPDATE
  can_view      = VALUES(can_view),
  active_status = VALUES(active_status);
`;

  writeFileSync(OUT, sql, "utf8");
  console.log(`Wrote ${rows.length} grants to ${OUT}`);
  console.log(`Roles covered: ${[...new Set(rows.map((r) => r.role))].sort().join(", ")}`);
}

main();
