/**
 * Generates the dashboard_metric_catalog / dashboard_role_metric_config seed.
 *
 * Both tables are empty in production, which is why `/metrics` returns [] and no tile can
 * show a target or a status. Rather than hand-writing 100+ INSERTs that would drift the
 * moment a metric is added, this emits them from the same METRICS / DASHBOARD_METRICS
 * constants the dashboards execute — the technique already used for the page-grant seed.
 *
 *   npx tsx scripts/generate-dashboard-metric-catalog.ts          # print
 *   npx tsx scripts/generate-dashboard-metric-catalog.ts --write  # write the migration
 *
 * Emits no target values. A target is a business commitment ("attendance should be 92%"),
 * not something derivable from code, and inventing one would put a fabricated number
 * behind a red/green tile. Targets are set through the API added alongside this.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  getMetricCatalogEntries,
  getRoleMetricConfigEntries,
} from "../src/modules/dashboards/dashboard-definition.service.js";
import { DASHBOARD_ACCESS_REGISTRY } from "../src/shared/dashboardAccessRegistry.js";

const sqlString = (value: string | null): string =>
  value === null ? "NULL" : `'${value.replace(/'/g, "''")}'`;

/**
 * Registry scope vocabulary -> the vocabulary dashboard_role_metric_config.scope_level and
 * DashboardScope.level already use. Kept explicit rather than lower-casing, so an
 * unmapped value falls back visibly instead of writing a string nothing reads.
 */
const SCOPE_LEVEL: Readonly<Record<string, string>> = {
  ORGANISATION: "ORG_ALL",
  BRANCH: "BRANCH_ALL",
  PROCESS: "PROCESS_ALL",
  TEAM: "TEAM_ONLY",
  SELF: "SELF_ONLY",
};

const catalog = getMetricCatalogEntries();
const roleConfig = getRoleMetricConfigEntries();

/**
 * Role rows are expanded from each dashboard's allowed roles, so display order and
 * primacy are stored per (role, dashboard, metric) — matching the table's unique key.
 */
type RoleRow = {
  roleCode: string;
  dashboardCode: string;
  metricCode: string;
  displayOrder: number;
  isPrimary: boolean;
  scopeLevel: string;
};

const roleRows: RoleRow[] = [];
for (const entry of roleConfig) {
  const definition = DASHBOARD_ACCESS_REGISTRY[entry.dashboardCode];
  if (!definition) continue;
  for (const roleCode of definition.allowedRoleKeys) {
    roleRows.push({
      roleCode,
      dashboardCode: entry.dashboardCode,
      metricCode: entry.metricCode,
      displayOrder: entry.displayOrder,
      isPrimary: entry.isPrimary,
      // The NARROWEST scope the dashboard supports, not the widest. scopeTypes is ordered
      // widest-first (["ORGANISATION","BRANCH","PROCESS"]), and recording ORGANISATION here
      // would read as "this metric is org-wide for this role" — the opposite of true for a
      // branch-scoped viewer. Actual row filtering stays with resolveDashboardScope at
      // query time; this column is presentation metadata and must never be treated as an
      // authorisation decision.
      scopeLevel: SCOPE_LEVEL[definition.scopeTypes[definition.scopeTypes.length - 1]]
        ?? "BRANCH_ALL",
    });
  }
}

const lines: string[] = [];
lines.push("-- 602_dashboard_metric_catalog_seed.sql");
lines.push("--");
lines.push("-- Seeds dashboard_metric_catalog and dashboard_role_metric_config, both of which");
lines.push("-- are empty in production. While they are empty, /api/dashboards/:code/metrics");
lines.push("-- returns [] and every tile reports status 'unknown' with no target.");
lines.push("--");
lines.push("-- GENERATED by scripts/generate-dashboard-metric-catalog.ts from the METRICS and");
lines.push("-- DASHBOARD_METRICS constants. Re-run the generator instead of editing by hand.");
lines.push("--");
lines.push("-- Idempotent: ON DUPLICATE KEY UPDATE against the existing unique keys");
lines.push("-- (uq_metric_code, uq_role_dash_metric). Re-running refreshes metadata and");
lines.push("-- inserts nothing twice.");
lines.push("--");
lines.push("-- Sets no targets. A target is a business commitment, not a derivable value;");
lines.push("-- targets are entered through POST /api/dashboards/targets.");
lines.push("");
lines.push("START TRANSACTION;");
lines.push("");
lines.push(`-- ${catalog.length} metrics`);
lines.push(
  "INSERT INTO dashboard_metric_catalog\n" +
    "  (id, metric_code, metric_name, module_code, data_source, unit, higher_is_better, is_active)\n" +
    "VALUES",
);
lines.push(
  catalog
    .map(
      (entry) =>
        `  (UUID(), ${sqlString(entry.metricCode)}, ${sqlString(entry.metricName)}, ` +
        `${sqlString(entry.moduleCode)}, ${sqlString(entry.dataSource)}, ` +
        `${sqlString(entry.unit)}, ${entry.higherIsBetter ? 1 : 0}, 1)`,
    )
    .join(",\n"),
);
lines.push("ON DUPLICATE KEY UPDATE");
lines.push("  metric_name      = VALUES(metric_name),");
lines.push("  module_code      = VALUES(module_code),");
lines.push("  data_source      = VALUES(data_source),");
lines.push("  unit             = VALUES(unit),");
lines.push("  higher_is_better = VALUES(higher_is_better),");
lines.push("  is_active        = VALUES(is_active);");
lines.push("");
lines.push(`-- ${roleRows.length} role/dashboard/metric rows`);
lines.push(
  "INSERT INTO dashboard_role_metric_config\n" +
    "  (id, role_code, dashboard_code, metric_code, display_order, is_primary, scope_level, is_active)\n" +
    "VALUES",
);
lines.push(
  roleRows
    .map(
      (row) =>
        `  (UUID(), ${sqlString(row.roleCode)}, ${sqlString(row.dashboardCode)}, ` +
        `${sqlString(row.metricCode)}, ${row.displayOrder}, ${row.isPrimary ? 1 : 0}, ` +
        `${sqlString(row.scopeLevel)}, 1)`,
    )
    .join(",\n"),
);
lines.push("ON DUPLICATE KEY UPDATE");
lines.push("  display_order = VALUES(display_order),");
lines.push("  is_primary    = VALUES(is_primary),");
lines.push("  scope_level   = VALUES(scope_level),");
lines.push("  is_active     = VALUES(is_active);");
lines.push("");
lines.push("COMMIT;");
lines.push("");
lines.push("-- Rollback:");
lines.push("--   DELETE FROM dashboard_role_metric_config;");
lines.push("--   DELETE FROM dashboard_metric_catalog;");
lines.push("-- Both tables were empty before this seed, so a full delete restores the prior state.");
lines.push("");

const sql = lines.join("\n");

if (process.argv.includes("--write")) {
  const target = resolve(
    import.meta.dirname,
    "../sql/602_dashboard_metric_catalog_seed.sql",
  );
  writeFileSync(target, sql, "utf8");
  console.log(`wrote ${target}`);
  console.log(`  ${catalog.length} catalog rows, ${roleRows.length} role config rows`);
} else {
  console.log(sql);
}

// Importing the definition service pulls in db/mysql.js, whose pool keeps the event loop
// alive. This script only reads constants and never queries, so exit rather than hang.
process.exit(0);
