-- TRACES-issued Part A of the salary TDS certificate.
--
-- WHY
-- ---
-- A salary TDS certificate has two parts and only one of them can come from a
-- payroll system:
--
--   Part B — salary breakup, deductions, tax computed. The employer produces
--            it. This system now computes it from the year's actual payroll
--            lines (see the form16-data endpoint).
--   Part A — tax deposited, challan and BSR codes, TRACES verification. It is
--            generated BY TRACES from the quarterly return and downloaded by
--            the employer. No HRMS can mint it, and one that pretended to would
--            be issuing an unverifiable document.
--
-- So Part A is ingested, not generated. This table records which TRACES
-- document belongs to which employee for which tax year, and leaves the file
-- itself in document_vault_inventory, where access levels, download tokens and
-- access logging already apply — a tax certificate is exactly the kind of
-- document that should not become a bare file path.
--
-- FORM NUMBER
-- -----------
-- form_number is stored rather than derived at read time. The Income-tax Act,
-- 2025 renamed this certificate from Form 16 to Form 130 on 1 April 2026, so a
-- FY 2025-26 certificate is a Form 16 and a FY 2026-27 one is a Form 130. What
-- TRACES actually issued is a fact about the document; recomputing it later
-- from whatever rule the code holds risks relabelling a real document.
--
-- ADDITIVE AND UNEXECUTED
-- -----------------------
-- New table only. Nothing existing is altered, and this is not run against any
-- database by this change.

CREATE TABLE IF NOT EXISTS tds_certificate_part_a (
  id                CHAR(36)      NOT NULL DEFAULT (UUID()),
  employee_id       CHAR(36)      NOT NULL,

  -- Financial year the certificate covers, as the starting calendar year:
  -- 2026 means FY 2026-27 (1 Apr 2026 – 31 Mar 2027).
  financial_year    SMALLINT      NOT NULL,

  -- "16" under the 1961 Act, "130" from the 2025 Act. Recorded as issued.
  form_number       VARCHAR(8)    NOT NULL,

  -- TRACES certificate number, as printed on the document.
  certificate_number VARCHAR(64)  NULL,

  -- The stored file. document_vault_inventory owns the bytes, the access level
  -- and the download-token machinery; this only points at it.
  vault_document_id CHAR(36)      NOT NULL,

  -- Denormalised from the vault because the file is served as
  -- /api/files/<category>/<stored_filename>?token=..., and building that URL
  -- should not require a second lookup on every read. Both are immutable once
  -- written, so they cannot drift apart.
  stored_filename   VARCHAR(255)  NOT NULL,
  storage_category  VARCHAR(64)   NOT NULL DEFAULT 'tds-certificates',

  -- Quarters the certificate covers. Part A is normally issued for the full
  -- year once all four quarterly returns are filed, but a partial issue during
  -- the year is legitimate and must be distinguishable from a complete one.
  covers_quarters   VARCHAR(16)   NULL,

  uploaded_by       CHAR(36)      NOT NULL,
  uploaded_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Set when someone with payroll authority confirms the document matches the
  -- employee and year it is filed under. Unverified certificates are visible to
  -- payroll but must not be presented to an employee as their certificate.
  verified_by       CHAR(36)      NULL,
  verified_at       DATETIME      NULL,

  notes             VARCHAR(500)  NULL,
  created_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  -- One current Part A per employee per year. A reissue replaces the row rather
  -- than accumulating duplicates that later disagree about which is authentic.
  UNIQUE KEY uq_tcpa_employee_year (employee_id, financial_year),
  INDEX idx_tcpa_year (financial_year),
  INDEX idx_tcpa_verified (verified_at),
  CONSTRAINT fk_tcpa_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
-- COLLATE is explicit, not incidental. `DEFAULT CHARSET=utf8mb4` alone resolves
-- to utf8mb4_0900_ai_ci on MySQL 8.0, while employees.id is utf8mb4_unicode_ci,
-- and a foreign key between columns of different collations is rejected outright
-- (errno 3780). Migration 1028 exists because this same mismatch reached
-- production once already and broke a join with ERROR 1267.
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
