-- Migration 1646: Explicit role_report_permissions rows for HR-variant roles
-- hr_admin, ho_hr, process_hr, recruitment_hr
--
-- ROLE_ALIASES in reporting-access.ts already maps these roles to "hr" at
-- query time. This migration adds explicit rows as belt-and-suspenders for any
-- raw SQL path that bypasses the alias layer.

INSERT INTO role_report_permissions (role_key, report_code, can_view, can_export, granted_by)
VALUES
  -- hr_admin (full HR access)
  ('hr_admin','employee-directory',1,1,1),
  ('hr_admin','employee-master-data',1,1,1),
  ('hr_admin','headcount-trend',1,1,1),
  ('hr_admin','joining-report',1,1,1),
  ('hr_admin','attrition-report',1,1,1),
  ('hr_admin','exit-interview-summary',1,1,1),
  ('hr_admin','probation-status',1,1,1),
  ('hr_admin','confirmation-due',1,1,1),
  ('hr_admin','attendance-summary',1,1,1),
  ('hr_admin','attendance-day-detail',1,1,1),
  ('hr_admin','leave-balance-summary',1,1,1),
  ('hr_admin','leave-trend-monthly',1,1,1),
  ('hr_admin','leave-request-log',1,1,1),
  ('hr_admin','document-compliance',1,1,1),
  ('hr_admin','bgv-status',1,1,1),
  ('hr_admin','onboarding-tracker',1,1,1),
  ('hr_admin','employee-lifecycle-events',1,1,1),
  ('hr_admin','roster-vs-actual',1,0,1),
  ('hr_admin','late-arrival-report',1,1,1),
  ('hr_admin','overtime-report',1,0,1),
  -- ho_hr (HO-level HR — full access)
  ('ho_hr','employee-directory',1,1,1),
  ('ho_hr','employee-master-data',1,1,1),
  ('ho_hr','headcount-trend',1,1,1),
  ('ho_hr','joining-report',1,1,1),
  ('ho_hr','attrition-report',1,1,1),
  ('ho_hr','exit-interview-summary',1,1,1),
  ('ho_hr','probation-status',1,1,1),
  ('ho_hr','confirmation-due',1,1,1),
  ('ho_hr','attendance-summary',1,1,1),
  ('ho_hr','attendance-day-detail',1,1,1),
  ('ho_hr','leave-balance-summary',1,1,1),
  ('ho_hr','leave-trend-monthly',1,1,1),
  ('ho_hr','leave-request-log',1,1,1),
  ('ho_hr','document-compliance',1,1,1),
  ('ho_hr','bgv-status',1,1,1),
  ('ho_hr','onboarding-tracker',1,1,1),
  ('ho_hr','employee-lifecycle-events',1,1,1),
  ('ho_hr','roster-vs-actual',1,0,1),
  ('ho_hr','late-arrival-report',1,1,1),
  ('ho_hr','overtime-report',1,0,1),
  -- process_hr (process-scope HR — view only, no bulk export)
  ('process_hr','employee-directory',1,0,1),
  ('process_hr','employee-master-data',1,0,1),
  ('process_hr','headcount-trend',1,0,1),
  ('process_hr','joining-report',1,0,1),
  ('process_hr','attrition-report',1,0,1),
  ('process_hr','exit-interview-summary',1,0,1),
  ('process_hr','probation-status',1,0,1),
  ('process_hr','confirmation-due',1,0,1),
  ('process_hr','attendance-summary',1,0,1),
  ('process_hr','attendance-day-detail',1,0,1),
  ('process_hr','leave-balance-summary',1,0,1),
  ('process_hr','leave-trend-monthly',1,0,1),
  ('process_hr','leave-request-log',1,0,1),
  ('process_hr','document-compliance',1,0,1),
  ('process_hr','bgv-status',1,0,1),
  ('process_hr','onboarding-tracker',1,0,1),
  ('process_hr','employee-lifecycle-events',1,0,1),
  ('process_hr','roster-vs-actual',1,0,1),
  ('process_hr','late-arrival-report',1,0,1),
  ('process_hr','overtime-report',1,0,1),
  -- recruitment_hr (hiring pipeline HR — HR reports + export on recruitment-related codes)
  ('recruitment_hr','employee-directory',1,1,1),
  ('recruitment_hr','employee-master-data',1,1,1),
  ('recruitment_hr','headcount-trend',1,1,1),
  ('recruitment_hr','joining-report',1,1,1),
  ('recruitment_hr','attrition-report',1,1,1),
  ('recruitment_hr','exit-interview-summary',1,0,1),
  ('recruitment_hr','probation-status',1,0,1),
  ('recruitment_hr','confirmation-due',1,0,1),
  ('recruitment_hr','attendance-summary',1,0,1),
  ('recruitment_hr','attendance-day-detail',1,0,1),
  ('recruitment_hr','leave-balance-summary',1,0,1),
  ('recruitment_hr','leave-trend-monthly',1,0,1),
  ('recruitment_hr','leave-request-log',1,0,1),
  ('recruitment_hr','document-compliance',1,1,1),
  ('recruitment_hr','bgv-status',1,1,1),
  ('recruitment_hr','onboarding-tracker',1,1,1),
  ('recruitment_hr','employee-lifecycle-events',1,1,1),
  ('recruitment_hr','roster-vs-actual',1,0,1),
  ('recruitment_hr','late-arrival-report',1,0,1),
  ('recruitment_hr','overtime-report',1,0,1)
ON DUPLICATE KEY UPDATE
  can_view   = VALUES(can_view),
  can_export = VALUES(can_export);
