-- Registers upload_template_master entries for Clovia's 9 new upload
-- types (sql/1768's tables), per explicit user request. Required/optional
-- columns are the real headers confirmed directly against the files the
-- user supplied, not guesses.
INSERT INTO upload_template_master
  (id, upload_type_code, upload_type_name, target_table, description, required_columns, optional_columns, sample_row, active_status)
VALUES
  (UUID(), 'CL_APR_MASMIS', 'Clovia — cl_apr (writes to db_masmis.cl_apr)', 'db_masmis.cl_apr',
   'Clovia''s cl_apr export -- writes into a new table.',
   JSON_ARRAY('Unique ID'),
   JSON_ARRAY('Date','USER NAME','MAS ID','No. of Calls','LOGIN TIME','PARKS','PARK TIME','AVG PARK','PARKS/CALL','WAIT','TALK','DISPO','PAUSE','Bio','Lunch','OutCal','Qualit','Short','Traini','ACHT','Team Briefing AUX','Total Break','Actual Login Hrs','Downtime','Net Login Hrs+DN','Utilization','Attendance','Week 1','LOB','Chat Count','Email Count','Total Calls','CSAT'),
   JSON_OBJECT('Unique ID', 'SAMPLE'),
   1),
  (UUID(), 'CL_CHAT_MASMIS', 'Clovia — cl_chat (writes to db_masmis.cl_chat)', 'db_masmis.cl_chat',
   'Clovia''s cl_chat export -- writes into a new table.',
   JSON_ARRAY('Chat_Id'),
   JSON_ARRAY('Date','UID','Phone_Number','Chat','Username','Name','Surname','Channel','Dept','Chat Flow','Date & Time','chat_duration','accepted_time','wait_time','star_rating_value','issue_solved','Total Chat','WEB','WP','Rating Received (Yes/No)','Response Rcv','Issue Resolved (Yes)','Issue Resolved (No)','Actual Agent on Chat','TL Name','Week','Mas id','User Name','Hours','15 Min Slot'),
   JSON_OBJECT('Chat_Id', 'SAMPLE'),
   1),
  (UUID(), 'CL_DISPO_MASMIS', 'Clovia — cl_dispo (writes to db_masmis.cl_dispo)', 'db_masmis.cl_dispo',
   'Clovia''s cl_dispo export -- writes into a new table.',
   JSON_ARRAY('Ticket No'),
   JSON_ARRAY('Date','Order No','Agent Name','Sourece','Gender','Conduct Of Customer','Reason','Sub Reason','Comment','Action Taken','User State','Skill','Flag','AWB Number','Order Status','Courier Partner','Actual Date','Count of order','Repeat/FTR','FTR','EMP Name','Campaign','WEEKS','CON','QRC'),
   JSON_OBJECT('Ticket No', 'SAMPLE'),
   1),
  (UUID(), 'CL_EMAIL_RAW_MASMIS', 'Clovia — cl_email_raw (writes to db_masmis.cl_email_raw)', 'db_masmis.cl_email_raw',
   'Clovia''s cl_email_raw export -- writes into a new table.',
   JSON_ARRAY('Unique ID'),
   JSON_ARRAY('EMP ID','Week','Date','Agent Name','Open Email','In Process','Re-Open','Total Mail Assigned','Total Touched Email','Closed Email','JunkMail'),
   JSON_OBJECT('Unique ID', 'SAMPLE'),
   1),
  (UUID(), 'CL_FEEDBACK_MASMIS', 'Clovia — cl_feedback (writes to db_masmis.cl_feedback)', 'db_masmis.cl_feedback',
   'Clovia''s cl_feedback export -- writes into a new table.',
   JSON_ARRAY('Unique'),
   JSON_ARRAY('Date','Advisor Id','Phone Number','Language','Option','Call Date','C-SAT/D-SAT'),
   JSON_OBJECT('Unique', 'SAMPLE'),
   1),
  (UUID(), 'CL_IB_CDR_MASMIS', 'Clovia — cl_ib_cdr (writes to db_masmis.cl_ib_cdr)', 'db_masmis.cl_ib_cdr',
   'Clovia''s cl_ib_cdr export -- writes into a new table.',
   JSON_ARRAY('Agent Id'),
   JSON_ARRAY('CallDate','Time','CallTime','Name','Calltype','Campname','Phone Number','Disposition','Disconn.By','Callduration','Queue Duration','Hold Time','Acwduration (Wrapup or Dispo time)','Hours Slot','Total Handled Time','Call 20 Sec (SL)','End Time','Status','Count','Unique/Repeat','Call 10 Sec (SL)','Abn','Short Calls','Slot Time','Count1','15 Min Slot','Count_1','U/R'),
   JSON_OBJECT('Agent Id', 'SAMPLE'),
   1),
  (UUID(), 'CL_OUTBOUND_MASMIS', 'Clovia — cl_outbound (writes to db_masmis.cl_outbound)', 'db_masmis.cl_outbound',
   'Clovia''s cl_outbound export -- writes into a new table.',
   JSON_ARRAY('Agent'),
   JSON_ARRAY('Phone Number','Call Date','Call Code','Start Time','End Time','Length (Sec)','Length (Min)','Campaign','Reason','Status','UAN','Count','U/R'),
   JSON_OBJECT('Agent', 'SAMPLE'),
   1),
  (UUID(), 'CL_QUALITY_MASMIS', 'Clovia — cl_quality (writes to db_masmis.cl_quality)', 'db_masmis.cl_quality',
   'Clovia''s cl_quality export -- writes into a new table.',
   JSON_ARRAY('Unique'),
   JSON_ARRAY('Chat/Mail Date','Audit Date','Chat ID','Emp ID','Emp Name','TL','Chat Source','Cx Query','FRT shared within timeline','Correct Information Shared','Softs skills followed on chat','Reminder shared to cx','Cx''s Concern Resolved','Tagging/mail shared','AOI if any','LOB','Week','Count','CQ Score','Fatal','ACPT','ACPT Reason'),
   JSON_OBJECT('Unique', 'SAMPLE'),
   1),
  (UUID(), 'CL_RECHURN_CALL_MASMIS', 'Clovia — cl_rechurn_call (writes to db_masmis.cl_rechurn_call)', 'db_masmis.cl_rechurn_call',
   'Clovia''s cl_rechurn_call export -- writes into a new table.',
   JSON_ARRAY('Agent'),
   JSON_ARRAY('Phone Number','Call Date','Abandoned Date','Status','Date'),
   JSON_OBJECT('Agent', 'SAMPLE'),
   1);
