-- Creates 4 brand-new db_masmis tables for two new processes: Birlanu
-- (birlanu_sale, birlanu_apr) and Satya Retail (satya_allocation,
-- satya_cdr), per explicit user request. Columns confirmed directly
-- against the real files the user supplied
-- (C:\Users\MAS60358\Desktop\Clovia\Birlanu Sale.xlsx, Birlanu APR.xlsx,
-- Satya Allocation.xlsx, Satya CDR.xlsx) -- not guessed. Same convention
-- as sql/1768 (Clovia): loosely-typed VARCHAR staging columns, TEXT only
-- for genuinely long free-text fields.
--
-- This app's db_masmis user has no CREATE privilege (confirmed live,
-- same as sql/1766/1768) -- NOT applied by this session; the user is
-- running it themselves.

-- birlanu_sale: Birlanu Sale.xlsx / Birlanu APR.xlsx (Sale Raw sheet)
CREATE TABLE IF NOT EXISTS db_masmis.birlanu_sale (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  week_month VARCHAR(50) NULL,
  weeks VARCHAR(20) NULL,
  days VARCHAR(20) NULL,
  lead_register_month VARCHAR(20) NULL,
  report_date VARCHAR(50) NULL,
  lead_id VARCHAR(50) NULL,
  unique_id VARCHAR(100) NULL,
  customer_name VARCHAR(200) NULL,
  customer_type VARCHAR(100) NULL,
  calling_number VARCHAR(50) NULL,
  enquiry_type VARCHAR(100) NULL,
  enquiry_source VARCHAR(100) NULL,
  sub_enquiry_source VARCHAR(100) NULL,
  lead_register_date VARCHAR(50) NULL,
  lead_outcalled_date VARCHAR(50) NULL,
  call_type VARCHAR(50) NULL,
  calling_status VARCHAR(100) NULL,
  interested_status VARCHAR(100) NULL,
  sub_calling_status VARCHAR(100) NULL,
  sub_sub_calling_status VARCHAR(100) NULL,
  select_business VARCHAR(100) NULL,
  buyer_type VARCHAR(100) NULL,
  lead_status VARCHAR(100) NULL,
  construction_level VARCHAR(100) NULL,
  customer_name_2 VARCHAR(200) NULL,
  alternative_number VARCHAR(50) NULL,
  email_id VARCHAR(150) NULL,
  address VARCHAR(500) NULL,
  landmark VARCHAR(200) NULL,
  brand VARCHAR(150) NULL,
  product VARCHAR(150) NULL,
  sub_product VARCHAR(150) NULL,
  state VARCHAR(100) NULL,
  district VARCHAR(100) NULL,
  zone VARCHAR(100) NULL,
  pincode VARCHAR(20) NULL,
  agent_name VARCHAR(150) NULL,
  order_qty VARCHAR(50) NULL,
  order_description TEXT NULL,
  order_value VARCHAR(50) NULL,
  customer_type_select VARCHAR(100) NULL,
  registration_status VARCHAR(100) NULL,
  remark TEXT NULL,
  secure_url TEXT NULL,
  seller_email_id VARCHAR(150) NULL,
  seller_phone_no VARCHAR(50) NULL,
  lead_closer_status VARCHAR(100) NULL,
  lead_closer_status_new VARCHAR(100) NULL,
  merged_lead_closer_status VARCHAR(100) NULL,
  lead_close_date VARCHAR(50) NULL,
  final_lead_close_date VARCHAR(50) NULL,
  lead_upload_type VARCHAR(50) NULL,
  created_by VARCHAR(150) NULL,
  updated_by VARCHAR(150) NULL,
  created_at_src VARCHAR(50) NULL,
  updated_at_src VARCHAR(50) NULL,
  sale_mt VARCHAR(50) NULL,
  sale_inr VARCHAR(50) NULL,
  sale_team_remarks TEXT NULL,
  sale_lead_status VARCHAR(100) NULL,
  cc_fil_remarks_reformat TEXT NULL,
  sale_lead_category VARCHAR(100) NULL,
  sale_product VARCHAR(150) NULL,
  sale_product_value VARCHAR(50) NULL,
  sale_status VARCHAR(100) NULL,
  attempt VARCHAR(20) NULL,
  revised_source VARCHAR(100) NULL,
  lead_closer_month VARCHAR(20) NULL,
  organic_paid VARCHAR(50) NULL,
  partner VARCHAR(100) NULL,
  helper VARCHAR(100) NULL,
  closed VARCHAR(50) NULL,
  first_call_date_time VARCHAR(50) NULL,
  created_at_ist VARCHAR(50) NULL,
  frt VARCHAR(50) NULL,
  within_tat VARCHAR(50) NULL,
  bucket VARCHAR(100) NULL,
  for_fr_tat VARCHAR(50) NULL,
  created_at_ist_2 VARCHAR(50) NULL,
  uploaded_by INT NULL,
  upload_batch_id VARCHAR(36) NULL,
  inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_birlanu_sale_batch (upload_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- birlanu_apr: Birlanu APR.xlsx (APR sheet)
CREATE TABLE IF NOT EXISTS db_masmis.birlanu_apr (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  report_date VARCHAR(50) NULL,
  agent_name VARCHAR(150) NULL,
  mas_id VARCHAR(50) NULL,
  total_calls VARCHAR(20) NULL,
  time_clock VARCHAR(50) NULL,
  login_time VARCHAR(50) NULL,
  wait_time VARCHAR(50) NULL,
  wait_pct VARCHAR(50) NULL,
  talk_time VARCHAR(50) NULL,
  talk_time_pct VARCHAR(50) NULL,
  dispo_time VARCHAR(50) NULL,
  dispo_time_pct VARCHAR(50) NULL,
  pause_time VARCHAR(50) NULL,
  pause_time_pct VARCHAR(50) NULL,
  dead_time VARCHAR(50) NULL,
  dead_time_pct VARCHAR(50) NULL,
  customer_pct VARCHAR(50) NULL,
  login_pct VARCHAR(50) NULL,
  logout_count VARCHAR(50) NULL,
  acht VARCHAR(50) NULL,
  aom VARCHAR(50) NULL,
  bio VARCHAR(50) NULL,
  lagged VARCHAR(50) NULL,
  login_lagged VARCHAR(50) NULL,
  lunch VARCHAR(50) NULL,
  meet VARCHAR(50) NULL,
  tea VARCHAR(50) NULL,
  total_break VARCHAR(50) NULL,
  net_login VARCHAR(50) NULL,
  attendance VARCHAR(20) NULL,
  uploaded_by INT NULL,
  upload_batch_id VARCHAR(36) NULL,
  inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_birlanu_apr_batch (upload_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- satya_allocation: Satya Allocation.xlsx (Allocation sheet)
CREATE TABLE IF NOT EXISTS db_masmis.satya_allocation (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  roster VARCHAR(50) NULL,
  warehouse VARCHAR(100) NULL,
  beat_name VARCHAR(150) NULL,
  shop_name VARCHAR(200) NULL,
  shop_phone VARCHAR(50) NULL,
  mas_id VARCHAR(50) NULL,
  report_date VARCHAR(50) NULL,
  uid VARCHAR(100) NULL,
  number_val VARCHAR(50) NULL,
  unique_flag VARCHAR(20) NULL,
  all_date VARCHAR(50) NULL,
  agent_id VARCHAR(50) NULL,
  disposition VARCHAR(100) NULL,
  sub_disposition VARCHAR(150) NULL,
  attempt VARCHAR(20) NULL,
  dd_val VARCHAR(20) NULL,
  same_day_connected VARCHAR(50) NULL,
  agent_name VARCHAR(150) NULL,
  order_value VARCHAR(50) NULL,
  call_type VARCHAR(50) NULL,
  order_match_filtered VARCHAR(50) NULL,
  agent_name_2 VARCHAR(150) NULL,
  uploaded_by INT NULL,
  upload_batch_id VARCHAR(36) NULL,
  inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_satya_allocation_batch (upload_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- satya_cdr: Satya CDR.xlsx (Sheet1)
CREATE TABLE IF NOT EXISTS db_masmis.satya_cdr (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  number_val VARCHAR(50) NULL,
  in_call_from VARCHAR(50) NULL,
  call_id VARCHAR(50) NULL,
  scenario VARCHAR(100) NULL,
  sub_scenario_1 VARCHAR(150) NULL,
  amount VARCHAR(50) NULL,
  beat_name VARCHAR(150) NULL,
  shop_name VARCHAR(200) NULL,
  warehouse VARCHAR(100) NULL,
  remarks TEXT NULL,
  roster VARCHAR(50) NULL,
  call_date VARCHAR(50) NULL,
  call_action VARCHAR(100) NULL,
  call_sub_action VARCHAR(100) NULL,
  call_action_remarks TEXT NULL,
  closer_date VARCHAR(50) NULL,
  follow_up_date VARCHAR(50) NULL,
  case_close_by VARCHAR(150) NULL,
  tat VARCHAR(50) NULL,
  due_date VARCHAR(50) NULL,
  call_created VARCHAR(50) NULL,
  call_status VARCHAR(100) NULL,
  connected VARCHAR(50) NULL,
  closer_time VARCHAR(50) NULL,
  report_date VARCHAR(50) NULL,
  attempt VARCHAR(20) NULL,
  agent_name VARCHAR(150) NULL,
  uid VARCHAR(100) NULL,
  uploaded_by INT NULL,
  upload_batch_id VARCHAR(36) NULL,
  inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_satya_cdr_batch (upload_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
