-- Creates 1 brand-new db_masmis table for a new GNC uploader: GNC Chat
-- (gnc_chat), per explicit user request. Columns confirmed directly
-- against the real file the user supplied
-- (C:\Users\MAS60358\Desktop\Clovia\GNC Chat.xlsx) -- not guessed.
-- GNC's other uploaders (gnc_sale, gnc_apr, gnc_allocation) target
-- already-live production tables; no existing table matches this
-- chatbot/CS-ticket export schema (checked information_schema -- no
-- gnc_chat or equivalent exists), so this is a new table, same
-- convention as Clovia/Birlanu/Satya Retail/LP Feedback/LP Onboarding.
--
-- This app's db_masmis user has no CREATE privilege (confirmed live
-- repeatedly this session) -- NOT applied by this session; the user is
-- running it themselves.

-- gnc_chat: GNC Chat.xlsx
CREATE TABLE IF NOT EXISTS db_masmis.gnc_chat (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ticket_id VARCHAR(50) NULL,
  ticket_status VARCHAR(50) NULL,
  channel VARCHAR(50) NULL,
  inbox_name VARCHAR(100) NULL,
  agent_name VARCHAR(150) NULL,
  customer_email VARCHAR(150) NULL,
  customer_phone VARCHAR(50) NULL,
  customer_name VARCHAR(150) NULL,
  first_agent_name VARCHAR(150) NULL,
  first_assigned_at VARCHAR(50) NULL,
  first_agent_message_time VARCHAR(50) NULL,
  last_agent_message_time VARCHAR(50) NULL,
  first_bot_message_time VARCHAR(50) NULL,
  last_bot_message_time VARCHAR(50) NULL,
  first_customer_message_time VARCHAR(50) NULL,
  last_customer_message_time VARCHAR(50) NULL,
  last_resolution_agent_name VARCHAR(150) NULL,
  last_resolution_time VARCHAR(50) NULL,
  agent_frt_s VARCHAR(20) NULL,
  bot_frt_s VARCHAR(20) NULL,
  bot_turns VARCHAR(20) NULL,
  agent_turns VARCHAR(20) NULL,
  customer_turns VARCHAR(20) NULL,
  is_handled_by_bot VARCHAR(10) NULL,
  is_handoff VARCHAR(10) NULL,
  is_resolved VARCHAR(10) NULL,
  is_closed VARCHAR(10) NULL,
  is_escalated VARCHAR(10) NULL,
  ticket_closed_at VARCHAR(50) NULL,
  ticket_queued_at VARCHAR(50) NULL,
  first_queued_at VARCHAR(50) NULL,
  ticket_to_waiting_at VARCHAR(50) NULL,
  queue_time_s VARCHAR(20) NULL,
  wait_time_s VARCHAR(20) NULL,
  is_checkout_created VARCHAR(10) NULL,
  query_text VARCHAR(500) NULL,
  query_category VARCHAR(150) NULL,
  error_instance VARCHAR(300) NULL,
  error_at VARCHAR(50) NULL,
  code_error VARCHAR(150) NULL,
  tags VARCHAR(200) NULL,
  customer_tags VARCHAR(200) NULL,
  bot_failure_instances VARCHAR(300) NULL,
  query_resolved VARCHAR(20) NULL,
  company_resolution_time_min VARCHAR(20) NULL,
  customer_frt_min VARCHAR(20) NULL,
  customer_resolution_time_min VARCHAR(20) NULL,
  chat_flow VARCHAR(300) NULL,
  last_customer_message TEXT NULL,
  last_customer_intent VARCHAR(150) NULL,
  first_customer_message TEXT NULL,
  first_customer_intent VARCHAR(150) NULL,
  created_at_src VARCHAR(50) NULL,
  updated_at_src VARCHAR(50) NULL,
  response_time_hrs VARCHAR(20) NULL,
  reopen_count VARCHAR(20) NULL,
  contextualisation VARCHAR(10) NULL,
  contextualisation_category VARCHAR(150) NULL,
  follow_up_time_min VARCHAR(20) NULL,
  csat_rating VARCHAR(20) NULL,
  csat_review TEXT NULL,
  csat_created_at VARCHAR(50) NULL,
  csat_updated_at VARCHAR(50) NULL,
  overall_sentiment VARCHAR(50) NULL,
  primary_category VARCHAR(150) NULL,
  secondary_category VARCHAR(150) NULL,
  churn_risk VARCHAR(50) NULL,
  urgency_level VARCHAR(50) NULL,
  product_name VARCHAR(200) NULL,
  payment_method VARCHAR(100) NULL,
  order_amount VARCHAR(50) NULL,
  order_id VARCHAR(100) NULL,
  price_sensitivity VARCHAR(50) NULL,
  resolution_confidence VARCHAR(50) NULL,
  ai_summary TEXT NULL,
  ticket_link TEXT NULL,
  ticket_in_office_hours VARCHAR(10) NULL,
  phone_number VARCHAR(50) NULL,
  report_date VARCHAR(50) NULL,
  unique_flag VARCHAR(20) NULL,
  frt_in_tat VARCHAR(20) NULL,
  qrc VARCHAR(150) NULL,
  response_in_tat VARCHAR(20) NULL,
  uploaded_by INT NULL,
  upload_batch_id VARCHAR(36) NULL,
  inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_gnc_chat_batch (upload_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
