USE mas_hrms;

CREATE TABLE IF NOT EXISTS break_kiosk_devices (
  id                           CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  kiosk_code                   VARCHAR(100) NOT NULL,
  kiosk_name                   VARCHAR(255) NOT NULL,
  branch_id                    CHAR(36)     NULL,
  process_id                   CHAR(36)     NULL,
  token_hash                   VARCHAR(64)  NOT NULL,
  allowed_ip_list              JSON         NULL,
  allowed_device_fingerprints  JSON         NULL,
  is_active                    TINYINT(1)   NOT NULL DEFAULT 1,
  last_used_at                 DATETIME     NULL,
  created_by                   CHAR(36)     NULL,
  created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_break_kiosk_code (kiosk_code),
  INDEX idx_break_kiosk_branch (branch_id),
  INDEX idx_break_kiosk_process (process_id),
  FOREIGN KEY (branch_id) REFERENCES branch_master(id) ON DELETE SET NULL,
  FOREIGN KEY (process_id) REFERENCES process_master(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS break_settings (
  id                              CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  branch_id                       CHAR(36)     NULL,
  process_id                      CHAR(36)     NULL,
  mini_break_max_minutes          INT          NOT NULL DEFAULT 29,
  long_break_min_minutes          INT          NOT NULL DEFAULT 30,
  active_break_alert_minutes      INT          NOT NULL DEFAULT 30,
  daily_total_allowed_minutes     INT          NOT NULL DEFAULT 60,
  max_long_break_count            INT          NOT NULL DEFAULT 2,
  escalation_after_minutes        INT          NOT NULL DEFAULT 10,
  auto_close_on_biometric_punch_out TINYINT(1) NOT NULL DEFAULT 1,
  allow_break_without_biometric   TINYINT(1)   NOT NULL DEFAULT 0,
  require_exception_reason        TINYINT(1)   NOT NULL DEFAULT 1,
  alert_reporting_manager         TINYINT(1)   NOT NULL DEFAULT 1,
  alert_hr                        TINYINT(1)   NOT NULL DEFAULT 0,
  alert_wfm                       TINYINT(1)   NOT NULL DEFAULT 0,
  alert_cc_list_json              JSON         NULL,
  created_at                      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_break_settings_scope (branch_id, process_id),
  INDEX idx_break_settings_branch (branch_id),
  INDEX idx_break_settings_process (process_id),
  FOREIGN KEY (branch_id) REFERENCES branch_master(id) ON DELETE CASCADE,
  FOREIGN KEY (process_id) REFERENCES process_master(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS break_sessions (
  id                           CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  employee_id                  CHAR(36)     NOT NULL,
  employee_code                VARCHAR(100) NOT NULL,
  branch_id                    CHAR(36)     NULL,
  process_id                   CHAR(36)     NULL,
  department_id                CHAR(36)     NULL,
  manager_id                   CHAR(36)     NULL,
  shift_date                   DATE         NOT NULL,
  break_start_time             DATETIME     NOT NULL,
  break_end_time               DATETIME     NULL,
  duration_seconds             INT          NULL,
  duration_minutes             INT          NULL,
  break_type                   ENUM('MINI','LONG') NULL,
  break_reason                 VARCHAR(120) NOT NULL,
  status                       ENUM('ACTIVE','COMPLETED','AUTO_CLOSED','CANCELLED','EXCEPTION') NOT NULL DEFAULT 'ACTIVE',
  start_source                 ENUM('KIOSK','ADMIN','API') NOT NULL DEFAULT 'KIOSK',
  end_source                   ENUM('KIOSK','ADMIN','AUTO_BIOMETRIC_PUNCH_OUT','AUTO_SHIFT_END') NULL,
  kiosk_device_id              CHAR(36)     NULL,
  biometric_punch_in_time      DATETIME     NULL,
  biometric_punch_out_time     DATETIME     NULL,
  no_biometric_punch_flag      TINYINT(1)   NOT NULL DEFAULT 0,
  exception_reason             TEXT         NULL,
  manager_approval_required    TINYINT(1)   NOT NULL DEFAULT 0,
  manager_approved_by          CHAR(36)     NULL,
  manager_approved_at          DATETIME     NULL,
  created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_break_sessions_employee_date (employee_id, shift_date),
  INDEX idx_break_sessions_code_date (employee_code, shift_date),
  INDEX idx_break_sessions_status (status),
  INDEX idx_break_sessions_branch (branch_id),
  INDEX idx_break_sessions_process (process_id),
  INDEX idx_break_sessions_manager (manager_id),
  INDEX idx_break_sessions_start (break_start_time),
  INDEX idx_break_sessions_end (break_end_time),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (branch_id) REFERENCES branch_master(id) ON DELETE SET NULL,
  FOREIGN KEY (process_id) REFERENCES process_master(id) ON DELETE SET NULL,
  FOREIGN KEY (department_id) REFERENCES department_master(id) ON DELETE SET NULL,
  FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (kiosk_device_id) REFERENCES break_kiosk_devices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS break_daily_summary (
  id                           CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  employee_id                  CHAR(36)     NOT NULL,
  employee_code                VARCHAR(100) NOT NULL,
  shift_date                   DATE         NOT NULL,
  branch_id                    CHAR(36)     NULL,
  process_id                   CHAR(36)     NULL,
  manager_id                   CHAR(36)     NULL,
  biometric_punch_in_time      DATETIME     NULL,
  biometric_punch_out_time     DATETIME     NULL,
  roster_status                VARCHAR(50)  NULL,
  attendance_status            VARCHAR(50)  NOT NULL DEFAULT 'NO_PUNCH_FOUND',
  total_break_seconds          INT          NOT NULL DEFAULT 0,
  total_break_minutes          INT          NOT NULL DEFAULT 0,
  mini_break_count             INT          NOT NULL DEFAULT 0,
  long_break_count             INT          NOT NULL DEFAULT 0,
  exceeded_break_count         INT          NOT NULL DEFAULT 0,
  exception_count              INT          NOT NULL DEFAULT 0,
  first_break_start            DATETIME     NULL,
  last_break_end               DATETIME     NULL,
  active_break_id              CHAR(36)     NULL,
  final_status                 VARCHAR(50)  NOT NULL DEFAULT 'NO_PUNCH_FOUND',
  created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_break_daily_summary_emp_date (employee_id, shift_date),
  INDEX idx_break_daily_summary_shift (shift_date),
  INDEX idx_break_daily_summary_branch (branch_id),
  INDEX idx_break_daily_summary_process (process_id),
  INDEX idx_break_daily_summary_manager (manager_id),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (branch_id) REFERENCES branch_master(id) ON DELETE SET NULL,
  FOREIGN KEY (process_id) REFERENCES process_master(id) ON DELETE SET NULL,
  FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (active_break_id) REFERENCES break_sessions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS break_alert_logs (
  id                           CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  break_session_id             CHAR(36)     NOT NULL,
  employee_id                  CHAR(36)     NOT NULL,
  manager_id                   CHAR(36)     NULL,
  alert_type                   VARCHAR(100) NOT NULL,
  alert_level                  ENUM('WARNING','ESCALATION','FINAL') NOT NULL DEFAULT 'WARNING',
  threshold_minutes            INT          NOT NULL DEFAULT 0,
  actual_minutes               INT          NOT NULL DEFAULT 0,
  exceeded_by_minutes          INT          NOT NULL DEFAULT 0,
  email_to                     VARCHAR(255) NULL,
  email_cc                     TEXT         NULL,
  email_subject                VARCHAR(500) NULL,
  email_status                 VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
  sent_at                      DATETIME     NULL,
  error_message                TEXT         NULL,
  created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_break_alert_session (break_session_id),
  INDEX idx_break_alert_employee (employee_id),
  INDEX idx_break_alert_type (alert_type),
  FOREIGN KEY (break_session_id) REFERENCES break_sessions(id) ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS break_audit_logs (
  id                           CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  entity_type                  VARCHAR(100) NOT NULL,
  entity_id                    CHAR(36)     NOT NULL,
  action                       VARCHAR(100) NOT NULL,
  employee_id                  CHAR(36)     NULL,
  performed_by_type            ENUM('KIOSK','ADMIN','SYSTEM') NOT NULL DEFAULT 'SYSTEM',
  performed_by_id              CHAR(36)     NULL,
  kiosk_device_id              CHAR(36)     NULL,
  old_value_json               JSON         NULL,
  new_value_json               JSON         NULL,
  ip_address                   VARCHAR(45)  NULL,
  user_agent                   VARCHAR(512) NULL,
  created_at                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_break_audit_entity (entity_type, entity_id),
  INDEX idx_break_audit_employee (employee_id),
  INDEX idx_break_audit_action (action),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (kiosk_device_id) REFERENCES break_kiosk_devices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO break_settings (
  id,
  branch_id,
  process_id,
  mini_break_max_minutes,
  long_break_min_minutes,
  active_break_alert_minutes,
  daily_total_allowed_minutes,
  max_long_break_count,
  escalation_after_minutes,
  auto_close_on_biometric_punch_out,
  allow_break_without_biometric,
  require_exception_reason,
  alert_reporting_manager,
  alert_hr,
  alert_wfm
)
SELECT
  UUID(),
  NULL,
  NULL,
  29,
  30,
  30,
  60,
  2,
  10,
  1,
  0,
  1,
  1,
  0,
  0
WHERE NOT EXISTS (
  SELECT 1 FROM break_settings WHERE branch_id IS NULL AND process_id IS NULL
);

INSERT INTO break_kiosk_devices (
  id,
  kiosk_code,
  kiosk_name,
  branch_id,
  process_id,
  token_hash,
  is_active,
  created_at,
  updated_at
)
SELECT
  UUID(),
  'NOIDA-FLOOR-1',
  'Noida Floor 1 Security Desk',
  NULL,
  NULL,
  SHA2('SECURE_TOKEN', 256),
  1,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM break_kiosk_devices WHERE kiosk_code = 'NOIDA-FLOOR-1'
);
