-- 408_ats_candidate_assessment_engine.sql
-- Additive pre-employment assessment engine.
-- IMPORTANT: This migration does not modify candidate, queue, interview, offer,
-- onboarding, BGV, provisioning, or employee lifecycle statuses.

CREATE TABLE IF NOT EXISTS ats_assessment_template (
  id CHAR(36) NOT NULL PRIMARY KEY,
  template_code VARCHAR(100) NOT NULL,
  template_name VARCHAR(255) NOT NULL,
  process_key ENUM('inbound','outbound','backoffice','document','email') NOT NULL,
  role_key ENUM('executive','team_leader','quality_auditor') NOT NULL,
  experience_level ENUM('any','fresher','experienced') NOT NULL DEFAULT 'any',
  difficulty_level ENUM('basic','intermediate','advanced') NOT NULL DEFAULT 'intermediate',
  duration_minutes INT UNSIGNED NOT NULL DEFAULT 30,
  passing_percentage DECIMAL(5,2) NOT NULL DEFAULT 60.00,
  gate_mode ENUM('advisory','soft_gate','hard_gate') NOT NULL DEFAULT 'advisory',
  template_version INT UNSIGNED NOT NULL DEFAULT 1,
  content_hash CHAR(64) NOT NULL,
  config_json JSON NOT NULL,
  source_type ENUM('built_in','custom') NOT NULL DEFAULT 'built_in',
  active_status TINYINT(1) NOT NULL DEFAULT 1,
  effective_from DATETIME NULL,
  effective_to DATETIME NULL,
  created_by CHAR(36) NULL,
  approved_by CHAR(36) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_assessment_template_version (template_code, template_version),
  UNIQUE KEY uq_assessment_template_hash (template_code, content_hash),
  INDEX idx_assessment_template_lookup (process_key, role_key, experience_level, active_status),
  INDEX idx_assessment_template_active (active_status, effective_from, effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ats_assessment_mapping (
  id CHAR(36) NOT NULL PRIMARY KEY,
  mapping_name VARCHAR(255) NOT NULL,
  branch_name VARCHAR(255) NULL,
  process_match VARCHAR(255) NULL,
  role_match VARCHAR(255) NULL,
  experience_match VARCHAR(100) NULL,
  vacancy_id CHAR(36) NULL,
  template_id CHAR(36) NOT NULL,
  priority INT NOT NULL DEFAULT 100,
  mandatory_flag TINYINT(1) NOT NULL DEFAULT 0,
  active_status TINYINT(1) NOT NULL DEFAULT 1,
  effective_from DATETIME NULL,
  effective_to DATETIME NULL,
  created_by CHAR(36) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_assessment_mapping_match (active_status, branch_name, process_match, role_match, priority),
  INDEX idx_assessment_mapping_template (template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ats_candidate_assessment (
  id CHAR(36) NOT NULL PRIMARY KEY,
  candidate_id CHAR(36) NOT NULL,
  queue_token_id CHAR(36) NULL,
  cycle_key VARCHAR(120) NOT NULL,
  q_token_snapshot VARCHAR(100) NULL,
  template_id CHAR(36) NOT NULL,
  template_version INT UNSIGNED NOT NULL DEFAULT 1,
  public_token_hash CHAR(64) NOT NULL,
  status ENUM(
    'assigned','in_progress','submitted_pending_scoring','manual_review',
    'completed','technical_error','expired','cancelled','skipped'
  ) NOT NULL DEFAULT 'assigned',
  attempt_no TINYINT UNSIGNED NOT NULL DEFAULT 1,
  typing_attempts_used TINYINT UNSIGNED NOT NULL DEFAULT 0,
  assignment_source ENUM('automatic','mapping','manual','kiosk') NOT NULL DEFAULT 'automatic',
  assigned_by CHAR(36) NULL,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  submitted_at DATETIME NULL,
  completed_at DATETIME NULL,
  expires_at DATETIME NULL,
  overall_score DECIMAL(8,2) NULL,
  max_score DECIMAL(8,2) NULL,
  percentage DECIMAL(5,2) NULL,
  result ENUM('pass','fail','pending_review') NULL,
  manual_review_required TINYINT(1) NOT NULL DEFAULT 0,
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME NULL,
  review_remarks VARCHAR(2000) NULL,
  section_scores JSON NULL,
  recommendation_json JSON NULL,
  integrity_flags JSON NULL,
  client_meta JSON NULL,
  failure_reason VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_candidate_assessment_cycle (candidate_id, cycle_key, template_id, attempt_no),
  UNIQUE KEY uq_candidate_assessment_public_hash (public_token_hash),
  INDEX idx_candidate_assessment_candidate (candidate_id, status),
  INDEX idx_candidate_assessment_queue (queue_token_id),
  INDEX idx_candidate_assessment_cycle (cycle_key),
  INDEX idx_candidate_assessment_status (status, assigned_at),
  INDEX idx_candidate_assessment_review (manual_review_required, status, submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ats_assessment_response (
  id CHAR(36) NOT NULL PRIMARY KEY,
  assessment_id CHAR(36) NOT NULL,
  question_id VARCHAR(120) NOT NULL,
  section_key VARCHAR(100) NOT NULL,
  question_type ENUM('single','multi','text') NOT NULL,
  question_snapshot JSON NOT NULL,
  answer_json JSON NULL,
  answer_text LONGTEXT NULL,
  marks_awarded DECIMAL(8,2) NULL,
  max_marks DECIMAL(8,2) NOT NULL DEFAULT 0,
  evaluation_mode ENUM('auto','keyword','manual') NOT NULL DEFAULT 'auto',
  evaluation_notes VARCHAR(2000) NULL,
  time_taken_seconds INT UNSIGNED NULL,
  answered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME NULL,
  review_remarks VARCHAR(2000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_assessment_question (assessment_id, question_id),
  INDEX idx_assessment_response_section (assessment_id, section_key),
  INDEX idx_assessment_response_review (assessment_id, evaluation_mode, reviewed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ats_typing_test_attempt (
  id CHAR(36) NOT NULL PRIMARY KEY,
  assessment_id CHAR(36) NOT NULL,
  attempt_no TINYINT UNSIGNED NOT NULL,
  reference_text LONGTEXT NOT NULL,
  typed_text LONGTEXT NULL,
  duration_limit_seconds INT UNSIGNED NOT NULL DEFAULT 180,
  elapsed_seconds INT UNSIGNED NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_at DATETIME NULL,
  gross_wpm DECIMAL(8,2) NULL,
  net_wpm DECIMAL(8,2) NULL,
  accuracy_percentage DECIMAL(5,2) NULL,
  edit_distance INT UNSIGNED NULL,
  correct_characters INT UNSIGNED NULL,
  incorrect_characters INT UNSIGNED NULL,
  missing_characters INT UNSIGNED NULL,
  extra_characters INT UNSIGNED NULL,
  correct_words INT UNSIGNED NULL,
  incorrect_words INT UNSIGNED NULL,
  backspace_count INT UNSIGNED NOT NULL DEFAULT 0,
  paste_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  score_percentage DECIMAL(5,2) NULL,
  passed_benchmark TINYINT(1) NULL,
  result_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_typing_assessment_attempt (assessment_id, attempt_no),
  INDEX idx_typing_assessment (assessment_id, submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ats_assessment_audit_log (
  id CHAR(36) NOT NULL PRIMARY KEY,
  assessment_id CHAR(36) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  event_payload JSON NULL,
  actor_type ENUM('candidate','system','recruiter','hr','admin') NOT NULL DEFAULT 'system',
  actor_id VARCHAR(100) NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_assessment_audit (assessment_id, created_at),
  INDEX idx_assessment_audit_event (event_type, created_at),
  INDEX idx_assessment_audit_actor (actor_type, actor_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'ATS candidate assessment engine migration 408 completed' AS status;
