CREATE TABLE IF NOT EXISTS report_identity_source_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_system VARCHAR(64) NOT NULL,
  source_record_key VARCHAR(128) NOT NULL,
  source_employee_code VARCHAR(64) NULL,
  source_agent_id VARCHAR(64) NULL,
  source_name VARCHAR(255) NULL,
  source_lob VARCHAR(128) NULL,
  source_role VARCHAR(128) NULL,
  source_designation VARCHAR(128) NULL,
  source_manager VARCHAR(128) NULL,
  source_status VARCHAR(64) NULL,
  match_key VARCHAR(128) NULL,
  matched_employee_id CHAR(36) NULL,
  matched_employee_code VARCHAR(64) NULL,
  match_status ENUM('matched','unmatched','ambiguous') NOT NULL DEFAULT 'unmatched',
  snapshot_run_id CHAR(36) NOT NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 1,
  captured_at DATETIME NOT NULL,
  source_updated_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_identity_source_record (source_system, source_record_key),
  KEY idx_identity_current_status (is_current, match_status, source_system),
  KEY idx_identity_source_employee_code (source_employee_code),
  KEY idx_identity_source_agent_id (source_agent_id),
  KEY idx_identity_matched_employee (matched_employee_id),
  KEY idx_identity_snapshot_run (snapshot_run_id)
);
