-- 600_role_dashboard_page_grants.sql
-- GENERATED by scripts/generate-dashboard-page-grants.ts — do not edit by hand.
-- Regenerate after changing allowedRoleKeys in shared/dashboardAccessRegistry.ts.
--
-- Purpose: align role_page_access (enforced by WorkforcePageGate) with the dashboard
-- access registry (enforced by ProtectedRoute and requireDashboardEntitlement). Both
-- gates must pass; they had drifted until 14 of 27 roles disagreed and several roles —
-- branch_head among them — could open no dashboard at all.
--
-- Additive and idempotent: upserts on uq_role_page (role_key, page_code).
-- Grants only. Revokes nothing, deletes nothing, and touches no page outside the
-- 12 role-dashboard page codes.
--
-- Covers 73 (role, page) pairs for 28 assignable roles.
--
-- NOT EXECUTED AUTOMATICALLY. Review, then run against the target schema.

-- can_export is intentionally untouched: this migration decides VIEW access only.
INSERT INTO role_page_access (id, role_key, page_code, can_view, active_status)
VALUES
  (UUID(), 'accounts_head', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'accounts_head', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'admin', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'assistant_manager', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'assistant_manager', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'branch_admin', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'branch_head', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'branch_head', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'branch_head', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'branch_head', 'QUALITY_DASHBOARD', 1, 1),
  (UUID(), 'branch_it', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'branch_it', 'IT_MANAGER_DASHBOARD', 1, 1),
  (UUID(), 'ceo', 'CEO_DASHBOARD', 1, 1),
  (UUID(), 'ceo', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'ceo', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'ceo', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'ceo', 'QUALITY_DASHBOARD', 1, 1),
  (UUID(), 'employee', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'finance', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'finance', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'finance_head', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'finance_head', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'hr', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'hr', 'HR_DASHBOARD', 1, 1),
  (UUID(), 'hr', 'RECRUITER_DASHBOARD', 1, 1),
  (UUID(), 'hr', 'WFM_ATTENDANCE_DASHBOARD', 1, 1),
  (UUID(), 'interviewer', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'it', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'it', 'IT_MANAGER_DASHBOARD', 1, 1),
  (UUID(), 'it_head', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'it_head', 'IT_MANAGER_DASHBOARD', 1, 1),
  (UUID(), 'manager', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'manager', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'manager', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'payroll', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'payroll', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'payroll_admin', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'payroll_admin', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'payroll_head', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'payroll_head', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'payroll_hr', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'payroll_hr', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'process_manager', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'process_manager', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'process_manager', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'qa', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'qa', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'qa', 'QUALITY_DASHBOARD', 1, 1),
  (UUID(), 'recruiter', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'recruiter', 'RECRUITER_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'CEO_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'HR_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'IT_MANAGER_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'PAYROLL_HR_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'QUALITY_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'RECRUITER_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'SUPER_ADMIN_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'WFM_ATTENDANCE_DASHBOARD', 1, 1),
  (UUID(), 'super_admin', 'WFM_DASHBOARD', 1, 1),
  (UUID(), 'team_leader', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'team_leader', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'tl', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'tl', 'MANAGEMENT_DASHBOARD', 1, 1),
  (UUID(), 'tq_head', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'tq_head', 'OPERATIONS_DASHBOARD', 1, 1),
  (UUID(), 'tq_head', 'QUALITY_DASHBOARD', 1, 1),
  (UUID(), 'trainer', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'wfm', 'EMPLOYEE_SELF_DASHBOARD', 1, 1),
  (UUID(), 'wfm', 'WFM_ATTENDANCE_DASHBOARD', 1, 1),
  (UUID(), 'wfm', 'WFM_DASHBOARD', 1, 1)
ON DUPLICATE KEY UPDATE
  can_view      = VALUES(can_view),
  active_status = VALUES(active_status);
