/**
 * Mira coaching layer — self scope.
 *
 * Every judgement here is computed in TypeScript from live HRMS rows; nothing is
 * generated by a language model and nothing payroll-related is read. The coach
 * speaks in four voices (performance, discipline, wellbeing, growth) but each one
 * is backed by a number the employee can verify on their own dashboard.
 *
 * Thin data is stated, never smoothed over: a KPI whose feed has fewer rows than
 * kpi_metric_master.minimum_sample_size is reported as "not enough data yet"
 * rather than scored, because a confident verdict on a sparse feed is worse than
 * no verdict at all.
 */

export type CoachTone = 'celebrate' | 'steady' | 'watch' | 'act';

export interface CoachPoint {
  lens: 'performance' | 'discipline' | 'wellbeing' | 'growth';
  tone: CoachTone;
  headline: string;
  detail: string;
}

export interface AttendanceWindow {
  presentDays: number;
  lateMarks: number;
  absentDays: number;
  lwpDays: number;
  workingDays: number;
}

export interface KpiSnapshot {
  metricName: string;
  unit: string | null;
  direction: string | null;
  targetValue: number | null;
  averageActual: number | null;
  sampleCount: number;
  minimumSampleSize: number | null;
  /** Readings there would be if the feed covered every working day in the window. */
  expectedSampleCount: number | null;
}

/**
 * Below this share of the working days in the window, a KPI feed is treated as
 * too patchy to score. kpi_metric_master.minimum_sample_size is frequently NULL
 * in practice, which left a feed covering a quarter of the days being reported
 * as a hard miss against target — a number that contradicted the employee's own
 * attendance record and would have read as an alarm.
 */
export const MIN_KPI_COVERAGE = 0.6;

export interface LeaveSnapshot {
  leaveName: string;
  allocated: number;
  used: number;
  available: number;
}

/** Share of working days that carried a late mark, 0 when nothing was worked. */
export function lateRate(window: AttendanceWindow): number {
  if (window.workingDays <= 0) return 0;
  return window.lateMarks / window.workingDays;
}

/** Share of working days actually attended. */
export function attendanceRate(window: AttendanceWindow): number {
  if (window.workingDays <= 0) return 0;
  return window.presentDays / window.workingDays;
}

/**
 * Compare a recent window against the one before it. Returns null when either
 * window is too thin to carry a trend — five working days is the floor, below
 * which a single late mark swings the rate enough to be meaningless.
 */
export function punctualityTrend(
  recent: AttendanceWindow,
  previous: AttendanceWindow,
): { direction: 'improving' | 'slipping' | 'steady'; deltaPct: number } | null {
  const MIN_DAYS = 5;
  if (recent.workingDays < MIN_DAYS || previous.workingDays < MIN_DAYS) return null;

  const delta = lateRate(recent) - lateRate(previous);
  const deltaPct = Math.round(delta * 1000) / 10;
  if (Math.abs(deltaPct) < 2) return { direction: 'steady', deltaPct };
  return { direction: delta < 0 ? 'improving' : 'slipping', deltaPct };
}

/**
 * Score a KPI against its target, respecting the metric's own minimum sample
 * size. `attainment` is the fraction of target reached, oriented so that higher
 * is always better regardless of the metric's direction.
 */
export function scoreKpi(kpi: KpiSnapshot): {
  status: 'on_track' | 'below_target' | 'insufficient_data';
  attainment: number | null;
} {
  const floor = kpi.minimumSampleSize ?? 1;
  if (kpi.sampleCount < floor || kpi.targetValue === null || kpi.averageActual === null) {
    return { status: 'insufficient_data', attainment: null };
  }
  if (
    kpi.expectedSampleCount !== null &&
    kpi.expectedSampleCount > 0 &&
    kpi.sampleCount / kpi.expectedSampleCount < MIN_KPI_COVERAGE
  ) {
    return { status: 'insufficient_data', attainment: null };
  }
  if (kpi.targetValue === 0) return { status: 'insufficient_data', attainment: null };

  const lowerIsBetter = (kpi.direction ?? '').toLowerCase().startsWith('lower');
  const attainment = lowerIsBetter
    ? kpi.targetValue / Math.max(kpi.averageActual, Number.EPSILON)
    : kpi.averageActual / kpi.targetValue;

  return { status: attainment >= 1 ? 'on_track' : 'below_target', attainment };
}

/**
 * Leave taken as a share of what was allocated. Used to spot both extremes:
 * someone burning through their year early, and someone who has not taken a
 * break at all.
 */
export function leaveBurn(rows: LeaveSnapshot[]): {
  allocated: number;
  used: number;
  burnRate: number;
  untouched: boolean;
} {
  const allocated = rows.reduce((sum, row) => sum + row.allocated, 0);
  const used = rows.reduce((sum, row) => sum + row.used, 0);
  const burnRate = allocated > 0 ? used / allocated : 0;
  return { allocated, used, burnRate, untouched: allocated > 0 && used === 0 };
}

/** Whole months between joining and now, floored at zero. */
export function tenureMonths(joinedAt: Date, now: Date): number {
  const months =
    (now.getFullYear() - joinedAt.getFullYear()) * 12 + (now.getMonth() - joinedAt.getMonth());
  const beforeAnniversaryDay = now.getDate() < joinedAt.getDate();
  return Math.max(0, beforeAnniversaryDay ? months - 1 : months);
}

/** The next round tenure milestone worth mentioning, or null if none is near. */
export function nextTenureMilestone(months: number): { label: string; monthsAway: number } | null {
  const milestones = [6, 12, 24, 36, 60, 120];
  for (const milestone of milestones) {
    if (months < milestone) {
      const monthsAway = milestone - months;
      if (monthsAway > 3) return null;
      const label = milestone % 12 === 0 ? `${milestone / 12} year` : `${milestone} month`;
      return { label, monthsAway };
    }
  }
  return null;
}

function pct(value: number): string {
  return `${Math.round(value * 1000) / 10}%`;
}

export function buildPerformancePoints(kpis: KpiSnapshot[]): CoachPoint[] {
  if (!kpis.length) {
    return [{
      lens: 'performance',
      tone: 'watch',
      headline: 'No KPI feed is reaching your record yet',
      detail: 'Nothing has been published against your employee id, so there is no performance trend to read. Your process manager owns the KPI mapping if you expect scores here.',
    }];
  }

  return kpis.map((kpi) => {
    const { status, attainment } = scoreKpi(kpi);
    const unit = kpi.unit === 'percent' ? '%' : kpi.unit ? ` ${kpi.unit}` : '';

    if (status === 'insufficient_data') {
      const coverage = kpi.expectedSampleCount && kpi.expectedSampleCount > 0
        ? ` — covering ${Math.round((kpi.sampleCount / kpi.expectedSampleCount) * 100)}% of your working days`
        : '';
      return {
        lens: 'performance' as const,
        tone: 'watch' as const,
        headline: `${kpi.metricName}: not enough data to score`,
        detail: `Only ${kpi.sampleCount} reading${kpi.sampleCount === 1 ? '' : 's'} have been published${coverage}. ` +
          'Scoring you on a feed this patchy would be misleading, so no verdict is given. Your process manager owns the KPI publication.',
      };
    }

    const attained = attainment as number;
    return {
      lens: 'performance' as const,
      tone: attained >= 1 ? 'celebrate' : attained >= 0.9 ? 'steady' : 'act',
      headline: `${kpi.metricName}: ${pct(attained)} of target`,
      detail: `You are averaging ${kpi.averageActual}${unit} against a target of ${kpi.targetValue}${unit}, across ${kpi.sampleCount} readings.` +
        (attained >= 1
          ? ' That is at or above target — keep the pattern that got you here.'
          : ' Closing this gap is the single clearest lever you have right now.'),
    };
  });
}

export function buildDisciplinePoints(
  recent: AttendanceWindow,
  previous: AttendanceWindow,
): CoachPoint[] {
  const points: CoachPoint[] = [];
  const rate = lateRate(recent);

  if (recent.workingDays === 0) {
    return [{
      lens: 'discipline',
      tone: 'watch',
      headline: 'No attendance records in the recent window',
      detail: 'There is nothing logged for the last 30 days, so punctuality cannot be assessed.',
    }];
  }

  points.push({
    lens: 'discipline',
    tone: rate === 0 ? 'celebrate' : rate <= 0.1 ? 'steady' : 'act',
    headline: rate === 0
      ? 'No late marks in the last 30 days'
      : `${recent.lateMarks} late mark${recent.lateMarks === 1 ? '' : 's'} in ${recent.workingDays} working days`,
    detail: rate === 0
      ? 'Clean punctuality record for the window. This is the kind of consistency that shows up in appraisals.'
      : `That is ${pct(rate)} of your working days. Attendance percentage feeds your KPI, so punctuality and performance move together here.`,
  });

  if (recent.lwpDays > 0) {
    points.push({
      lens: 'discipline',
      tone: 'act',
      headline: `${recent.lwpDays} day${recent.lwpDays === 1 ? '' : 's'} marked loss of pay`,
      detail: 'LWP days reduce payable days directly. If any of these were approved leave recorded wrongly, raise a regularisation before the payroll cut-off.',
    });
  }

  const trend = punctualityTrend(recent, previous);
  if (trend && trend.direction !== 'steady') {
    points.push({
      lens: 'discipline',
      tone: trend.direction === 'improving' ? 'celebrate' : 'watch',
      headline: trend.direction === 'improving'
        ? `Punctuality improving — late rate down ${Math.abs(trend.deltaPct)} points`
        : `Punctuality slipping — late rate up ${Math.abs(trend.deltaPct)} points`,
      detail: 'Measured against the previous 30-day window.',
    });
  }

  return points;
}

export function buildWellbeingPoints(leave: LeaveSnapshot[]): CoachPoint[] {
  const burn = leaveBurn(leave);
  if (burn.allocated === 0) {
    return [{
      lens: 'wellbeing',
      tone: 'watch',
      headline: 'No leave allocation found for this year',
      detail: 'Without an allocation there is nothing to plan against. HR owns the leave ledger if this looks wrong.',
    }];
  }

  const points: CoachPoint[] = [];
  if (burn.untouched) {
    points.push({
      lens: 'wellbeing',
      tone: 'watch',
      headline: 'You have not taken a single day off this year',
      detail: `All ${burn.allocated} allocated days are still unused. Rest is not a reward for finishing the work — plan a break before the year-end rush.`,
    });
  } else if (burn.burnRate >= 0.85) {
    points.push({
      lens: 'wellbeing',
      tone: 'act',
      headline: `${pct(burn.burnRate)} of your leave is already used`,
      detail: `${Math.round((burn.allocated - burn.used) * 10) / 10} days remain for the rest of the year. Worth planning the remainder deliberately.`,
    });
  } else {
    points.push({
      lens: 'wellbeing',
      tone: 'steady',
      headline: `Leave balance is healthy — ${Math.round((burn.allocated - burn.used) * 10) / 10} days available`,
      detail: `You have used ${burn.used} of ${burn.allocated} allocated days.`,
    });
  }

  const lowest = leave
    .filter((row) => row.allocated > 0)
    .sort((a, b) => a.available - b.available)[0];
  if (lowest && lowest.available <= 0) {
    points.push({
      lens: 'wellbeing',
      tone: 'watch',
      headline: `${lowest.leaveName} is exhausted`,
      detail: 'Further absence under this type will fall to another bucket or to loss of pay.',
    });
  }

  return points;
}

export function buildGrowthPoints(months: number): CoachPoint[] {
  const years = Math.floor(months / 12);
  const remainder = months % 12;
  const served = years > 0
    ? `${years} year${years === 1 ? '' : 's'}${remainder ? ` ${remainder} month${remainder === 1 ? '' : 's'}` : ''}`
    : `${months} month${months === 1 ? '' : 's'}`;

  const points: CoachPoint[] = [{
    lens: 'growth',
    tone: 'steady',
    headline: `${served} with MAS Callnet`,
    detail: 'Tenure is the backdrop every other number is read against.',
  }];

  const milestone = nextTenureMilestone(months);
  if (milestone) {
    points.push({
      lens: 'growth',
      tone: 'celebrate',
      headline: `${milestone.label} milestone is ${milestone.monthsAway} month${milestone.monthsAway === 1 ? '' : 's'} away`,
      detail: 'A good moment to have the growth conversation with your reporting manager.',
    });
  }

  return points;
}

const TONE_PREFIX: Record<CoachTone, string> = {
  celebrate: '🟢',
  steady: '🔵',
  watch: '🟡',
  act: '🔴',
};

/** Render the coaching points as the message body Mira returns. */
export function renderCoachReport(points: CoachPoint[]): string {
  const order: CoachPoint['lens'][] = ['performance', 'discipline', 'wellbeing', 'growth'];
  const titles: Record<CoachPoint['lens'], string> = {
    performance: 'Performance',
    discipline: 'Attendance and discipline',
    wellbeing: 'Wellbeing',
    growth: 'Growth',
  };

  const sections = order
    .map((lens) => {
      const forLens = points.filter((point) => point.lens === lens);
      if (!forLens.length) return null;
      const lines = forLens
        .map((point) => `${TONE_PREFIX[point.tone]} **${point.headline}**\n   ${point.detail}`)
        .join('\n');
      return `**${titles[lens]}**\n${lines}`;
    })
    .filter(Boolean);

  return sections.join('\n\n');
}
