import {
  Activity, BarChart3, Bell, Briefcase, Building2, Calendar,
  CalendarDays, ClipboardList, Clock, CreditCard, FileCheck,
  FileText, GraduationCap, Heart, Home, Landmark,
  Network, Package, Server, Settings, Settings2, ShieldCheck, Sparkles,
  Target, TrendingUp, User, UserMinus, UserPlus, Users, Wallet,
  Zap,
} from "lucide-react";
import type { NavGroup } from "./SidebarNav";

export const navGroups: NavGroup[] = [
  {
    title: "Overview",
    items: [
      { label: "Dashboard",    href: "/dashboard",    icon: <Home className="h-[15px] w-[15px]" />,         description: "Workspace" },
      { label: "My Modules",   href: "/modules",      icon: <Package className="h-[15px] w-[15px]" />,      description: "All allowed pages" },
      { label: "Notifications",href: "/notifications",icon: <Bell className="h-[15px] w-[15px]" />,         description: "Personal updates" },
      { label: "Work Inbox",   href: "/work-inbox",   icon: <ClipboardList className="h-[15px] w-[15px]" />,pageCode: "WORK_INBOX", description: "Pending actions" },
      { label: "Reports",      href: "/reports",      icon: <BarChart3 className="h-[15px] w-[15px]" />,    roles: ["admin","hr","manager","ceo","branch_head"], description: "Reports" },
    ],
  },
  {
    title: "My Space",
    items: [
      { label: "Profile",                   href: "/profile",                        icon: <User className="h-[15px] w-[15px]" />,         description: "Profile" },
      { label: "Attendance",                href: "/attendance",                     icon: <Clock className="h-[15px] w-[15px]" />,         description: "Attendance" },
      { label: "Attendance Regularization", href: "/attendance/regularizations",     icon: <Clock className="h-[15px] w-[15px]" />,         pageCode: "ATTENDANCE_REGULARIZATION", description: "Regularize attendance" },
      { label: "Attendance Disputes",       href: "/attendance/disputes",            icon: <ClipboardList className="h-[15px] w-[15px]" />,  description: "Dispute requests" },
      { label: "Leaves",                    href: "/leaves",                         icon: <CalendarDays className="h-[15px] w-[15px]" />,   description: "Leave" },
      { label: "My Roster",                 href: "/my-roster",                      icon: <Calendar className="h-[15px] w-[15px]" />,       description: "Roster" },
      { label: "Week-off Preference",       href: "/week-off-preferences",           icon: <CalendarDays className="h-[15px] w-[15px]" />,   description: "Week-off" },
      { label: "Payslips",                  href: "/profile?tab=payslips",           icon: <CreditCard className="h-[15px] w-[15px]" />,     description: "Payslips" },
      { label: "Payslip Center",            href: "/payroll/payslips",               icon: <CreditCard className="h-[15px] w-[15px]" />,     pageCode: "PAYROLL_PAYSLIPS", description: "Download payslips" },
      { label: "Tax Declaration",           href: "/payroll/tax-declaration",        icon: <Landmark className="h-[15px] w-[15px]" />,       description: "Tax" },
      { label: "Calendar",                  href: "/calendar",                       icon: <Calendar className="h-[15px] w-[15px]" />,       description: "Company calendar" },
      { label: "Notification Preferences",  href: "/notification-preferences",       icon: <Bell className="h-[15px] w-[15px]" />,           description: "Alert settings" },
      { label: "Comm. Preferences",         href: "/communication/preferences",      icon: <Bell className="h-[15px] w-[15px]" />,           description: "Comm preferences" },
      { label: "Engagement",                href: "/engagement",                     icon: <Sparkles className="h-[15px] w-[15px]" />,       description: "Engagement" },
      { label: "Leaderboard",               href: "/engagement/leaderboard",         icon: <TrendingUp className="h-[15px] w-[15px]" />,     description: "Leaderboard" },
      { label: "People Experience",         href: "/people-experience/command-center",icon: <Users className="h-[15px] w-[15px]" />,         description: "People ops" },
      { label: "Roster Preference",         href: "/roster-preference",              icon: <Calendar className="h-[15px] w-[15px]" />,       pageCode: "WFM_ROSTER", description: "Roster preferences" },
    ],
  },
  {
    title: "People & Hiring",
    items: [
      { label: "Employees",             href: "/employees",                    icon: <Users className="h-[15px] w-[15px]" />,        roles: ["admin","hr","manager","branch_head","process_manager"], description: "Directory" },
      { label: "Departments",           href: "/departments",                  icon: <Building2 className="h-[15px] w-[15px]" />,    roles: ["admin","hr","manager","ceo","branch_head"], description: "Departments" },
      { label: "Onboarding",            href: "/onboarding",                   icon: <UserPlus className="h-[15px] w-[15px]" />,     roles: ["admin","hr"], description: "Onboarding" },
      { label: "Document Verification", href: "/document-verification",        icon: <FileCheck className="h-[15px] w-[15px]" />,    roles: ["admin","hr"], description: "Documents" },
      { label: "Bulk Upload",           href: "/bulk-upload",                  icon: <Package className="h-[15px] w-[15px]" />,      pageCode: "EMPLOYEE_MANAGEMENT", roles: ["admin","hr"], description: "Bulk data import" },
      { label: "BGV Reports",           href: "/ats/bgv-report",               icon: <FileCheck className="h-[15px] w-[15px]" />,    roles: ["admin","hr"], description: "BGV" },
      { label: "BGV Verification",      href: "/ats/bgv",                      icon: <FileCheck className="h-[15px] w-[15px]" />,    pageCode: "ATS_BGV", roles: ["admin","hr"], description: "BGV center" },
      { label: "Employee Journey",      href: "/employee-stat-card",           icon: <Users className="h-[15px] w-[15px]" />,        description: "Journey" },
      { label: "Employee Lifecycle",    href: "/employee-lifecycle",           icon: <Users className="h-[15px] w-[15px]" />,        pageCode: "EMPLOYEE_LIFECYCLE", roles: ["admin","hr"], description: "Lifecycle" },
      { label: "Career Planning",       href: "/career-planning",              icon: <TrendingUp className="h-[15px] w-[15px]" />,   pageCode: "CAREER_PLANNING", description: "Career paths" },
      { label: "Offer Letters",         href: "/offer-letter",                 icon: <FileText className="h-[15px] w-[15px]" />,     pageCode: "ATS_OFFER", roles: ["admin","hr"], description: "Generate offers" },
      { label: "ATS Command",           href: "/ats/command-center",           icon: <Briefcase className="h-[15px] w-[15px]" />,    pageCode: "ATS_DASHBOARD", description: "ATS" },
      { label: "ATS Sourcing",          href: "/ats/sourcing-analysis",        icon: <BarChart3 className="h-[15px] w-[15px]" />,    pageCode: "ATS_DASHBOARD", roles: ["admin","hr"], description: "Sourcing analytics" },
      { label: "Candidate Master",      href: "/ats/candidate-master",         icon: <Users className="h-[15px] w-[15px]" />,        pageCode: "ATS_CANDIDATE_MASTER", description: "Candidate DB" },
      { label: "Onboarding Bridge",     href: "/ats/onboarding-bridge",        icon: <UserPlus className="h-[15px] w-[15px]" />,     pageCode: "ATS_ONBOARDING_BRIDGE", roles: ["admin","hr"], description: "Bridge" },
      { label: "Onboarding Requests",   href: "/ats/onboarding-requests",      icon: <ClipboardList className="h-[15px] w-[15px]" />,pageCode: "ATS_ONBOARDING_BRIDGE", roles: ["admin","hr"], description: "HR onboarding" },
      { label: "Offer Approvals",       href: "/ats/offer-approvals",          icon: <FileCheck className="h-[15px] w-[15px]" />,    pageCode: "ATS_OFFER", roles: ["admin","hr"], description: "Offer approvals" },
      { label: "Walk-in Queue",         href: "/ats/walkin-queue",             icon: <Users className="h-[15px] w-[15px]" />,        pageCode: "ATS_WAITING_QUEUE", description: "Queue" },
      { label: "My Candidates",         href: "/ats/recruiter/my-candidates",  icon: <ClipboardList className="h-[15px] w-[15px]" />,pageCode: "ATS_RECRUITER_QUEUE", description: "Candidates" },
      { label: "Jobs Portal",           href: "/jobs",                         icon: <Briefcase className="h-[15px] w-[15px]" />,    pageCode: "JOBS_PORTAL", description: "Jobs" },
    ],
  },
  {
    title: "Workforce",
    items: [
      { label: "My Learning",            href: "/lms/my-learning",           icon: <GraduationCap className="h-[15px] w-[15px]" />, pageCode: "LMS_MY_LEARNING", description: "LMS" },
      { label: "LMS Coordinator",        href: "/lms/coordinator",           icon: <Users className="h-[15px] w-[15px]" />,         pageCode: "LMS_COORDINATOR", description: "Training" },
      { label: "LMS Admin",              href: "/lms/admin",                 icon: <GraduationCap className="h-[15px] w-[15px]" />, pageCode: "LMS_ADMIN", description: "LMS admin" },
      { label: "Roster Planning",        href: "/wfm/roster",                icon: <Clock className="h-[15px] w-[15px]" />,         pageCode: "WFM_ROSTER", description: "Roster" },
      { label: "Auto Roster",            href: "/wfm/auto-roster",           icon: <Calendar className="h-[15px] w-[15px]" />,      pageCode: "WFM_AUTO_ROSTER", description: "Auto roster" },
      { label: "RTA Board",              href: "/rta-board",                 icon: <Activity className="h-[15px] w-[15px]" />,      pageCode: "RTA_BOARD", description: "RTA" },
      { label: "WFM Tracker",            href: "/wfm/live-tracker",          icon: <Clock className="h-[15px] w-[15px]" />,         pageCode: "WFM_LIVE_TRACKER", description: "Live" },
      { label: "Attendance Exceptions",  href: "/wfm/attendance-exceptions", icon: <Clock className="h-[15px] w-[15px]" />,         pageCode: "WFM_LIVE_TRACKER", description: "Exception engine" },
      { label: "COSEC Monitoring",       href: "/wfm/cosec-monitoring",      icon: <Activity className="h-[15px] w-[15px]" />,      pageCode: "WFM_LIVE_TRACKER", description: "Biometric sync" },
      { label: "WFM Planning Rules",     href: "/wfm/planning-rules",        icon: <Settings2 className="h-[15px] w-[15px]" />,     roles: ["admin","hr","wfm","manager","super_admin"], description: "Shift planning rules" },
      { label: "Slot Requirements",      href: "/wfm/slot-requirements",     icon: <Calendar className="h-[15px] w-[15px]" />,      roles: ["admin","hr","wfm","manager","super_admin"], description: "Slot capacity" },
      { label: "Week-off Day Rules",     href: "/wfm/weekoff-day-rules",     icon: <CalendarDays className="h-[15px] w-[15px]" />,  roles: ["admin","hr","wfm","manager","super_admin"], description: "Day-level rules" },
      { label: "Roster Dispute Queue",   href: "/wfm/roster-dispute-queue",  icon: <ClipboardList className="h-[15px] w-[15px]" />, roles: ["admin","hr","wfm","manager","branch_head","super_admin"], description: "Roster disputes" },
      { label: "Roster Master Builder",  href: "/roster-master-builder",     icon: <Calendar className="h-[15px] w-[15px]" />,      pageCode: "ROSTER_MASTER", description: "Build roster masters" },
      { label: "Roster Capacity Config", href: "/roster-capacity-config",    icon: <Settings2 className="h-[15px] w-[15px]" />,     pageCode: "ROSTER_MASTER", description: "Capacity settings" },
      { label: "Workforce Planning",     href: "/workforce-planning",        icon: <Users className="h-[15px] w-[15px]" />,         pageCode: "WFM_AUTO_ROSTER", description: "Headcount planning" },
    ],
  },
  {
    title: "Operations",
    items: [
      { label: "Performance",             href: "/performance",                    icon: <Target className="h-[15px] w-[15px]" />,      description: "Performance" },
      { label: "Performance Command",     href: "/performance/command-center",     icon: <Target className="h-[15px] w-[15px]" />,      pageCode: "WORKFORCE_COMMAND_CENTER", description: "Perf command" },
      { label: "Reviews Management",      href: "/reviews-management",             icon: <ClipboardList className="h-[15px] w-[15px]" />,pageCode: "WORKFORCE_COMMAND_CENTER", description: "Reviews" },
      { label: "Goals & Appraisal",       href: "/goals",                          icon: <Target className="h-[15px] w-[15px]" />,      description: "Goals" },
      { label: "PIP Management",          href: "/pip-management",                 icon: <ClipboardList className="h-[15px] w-[15px]" />,pageCode: "PIP_MANAGEMENT", description: "PIP" },
      { label: "Payroll",                 href: "/payroll",                        icon: <CreditCard className="h-[15px] w-[15px]" />,  roles: ["admin","hr","finance","payroll"], description: "Payroll" },
      { label: "Payroll Readiness",       href: "/payroll/readiness",              icon: <CreditCard className="h-[15px] w-[15px]" />,  pageCode: "PAYROLL", roles: ["admin","hr","finance","payroll"], description: "Payroll readiness" },
      { label: "Full & Final",            href: "/payroll/full-final",             icon: <Zap className="h-[15px] w-[15px]" />,         roles: ["admin","hr","finance","payroll"], description: "F&F" },
      { label: "Salary Packages",         href: "/payroll/salary-packages",        icon: <Wallet className="h-[15px] w-[15px]" />,      roles: ["admin","finance"], description: "Pay matrix" },
      { label: "KPI Config",              href: "/kpi-config",                     icon: <Target className="h-[15px] w-[15px]" />,      pageCode: "KPI_CONFIG", roles: ["admin","hr","manager","process_manager"], description: "KPI" },
      { label: "Operations KPI",          href: "/operations-kpi",                 icon: <Target className="h-[15px] w-[15px]" />,      pageCode: "OPERATIONS_KPI", description: "Ops KPI" },
      { label: "Management",              href: "/management/dashboard",           icon: <BarChart3 className="h-[15px] w-[15px]" />,   pageCode: "MANAGEMENT_DASHBOARD", description: "Management" },
      { label: "CEO Command Center",      href: "/management/ceo-command-center",  icon: <BarChart3 className="h-[15px] w-[15px]" />,   roles: ["admin","hr","ceo","finance","process_manager","manager"], description: "CEO dashboard" },
      { label: "Business Command Center", href: "/business-command-center",        icon: <Briefcase className="h-[15px] w-[15px]" />,   roles: ["admin","ceo","hr","manager","process_manager"], description: "Business ops center" },
      { label: "Business Actions",        href: "/business-actions",               icon: <ClipboardList className="h-[15px] w-[15px]" />,roles: ["admin","ceo","hr","manager","process_manager","team_leader","tl"], description: "Action queue" },
      { label: "Payroll Att. Overrides",  href: "/payroll/attendance-overrides",   icon: <Settings2 className="h-[15px] w-[15px]" />,   roles: ["admin","super_admin","payroll_head","payroll_admin"], description: "Override attendance for payroll" },
      { label: "Master Reports",          href: "/master-reports",                 icon: <BarChart3 className="h-[15px] w-[15px]" />,   pageCode: "ADVANCED_REPORTS", description: "Master reports" },
      { label: "Advanced Reports",        href: "/advanced-reports",               icon: <BarChart3 className="h-[15px] w-[15px]" />,   pageCode: "ADVANCED_REPORTS", description: "Advanced reports" },
      { label: "Enterprise Reports",      href: "/reports/enterprise",             icon: <BarChart3 className="h-[15px] w-[15px]" />,   pageCode: "ADVANCED_REPORTS", description: "Enterprise reports" },
      { label: "Attendance Rules",        href: "/attendance-rules-master",        icon: <Settings2 className="h-[15px] w-[15px]" />,   roles: ["admin","hr"], description: "Attendance rules" },
      { label: "Control Tower",           href: "/control-tower",                  icon: <Activity className="h-[15px] w-[15px]" />,    pageCode: "CONTROL_TOWER", description: "Control tower" },
      { label: "Operations Dashboard",    href: "/operations/dashboard",           icon: <Target className="h-[15px] w-[15px]" />,      pageCode: "OPERATIONS_DASHBOARD", description: "Ops dashboard" },
      { label: "Quality Dashboard",       href: "/quality/dashboard",              icon: <BarChart3 className="h-[15px] w-[15px]" />,   pageCode: "QUALITY_DASHBOARD", description: "Quality dashboard" },
      { label: "Agent Performance",       href: "/agent-performance",              icon: <Activity className="h-[15px] w-[15px]" />,    roles: ["admin","hr","ceo","qa","analyst","manager","process_manager","branch_head"], description: "Cross-source KPI" },
    ],
  },
  {
    title: "Engage & Support",
    items: [
      { label: "Kudos Wall",           href: "/engagement/kudos",                    icon: <Heart className="h-[15px] w-[15px]" />,         description: "Kudos" },
      { label: "Badges",               href: "/engagement/badges",                   icon: <ShieldCheck className="h-[15px] w-[15px]" />,   description: "Badges" },
      { label: "Surveys",              href: "/engagement/surveys",                  icon: <ClipboardList className="h-[15px] w-[15px]" />,  description: "Surveys" },
      { label: "Helpdesk",             href: "/helpdesk",                            icon: <ShieldCheck className="h-[15px] w-[15px]" />,   description: "Helpdesk" },
      { label: "Support Command",      href: "/support/command-center",              icon: <ShieldCheck className="h-[15px] w-[15px]" />,   pageCode: "SUPPORT_COMMAND_CENTER", description: "Support ops" },
      { label: "Grievance Center",     href: "/support/grievance-command-center",    icon: <ClipboardList className="h-[15px] w-[15px]" />,  pageCode: "GRIEVANCE_COMMAND_CENTER", description: "Grievances" },
      { label: "Benefits & Claims",    href: "/benefits",                            icon: <ShieldCheck className="h-[15px] w-[15px]" />,   description: "Benefits" },
      { label: "Letters",              href: "/letters",                             icon: <FileText className="h-[15px] w-[15px]" />,       pageCode: "LETTERS", roles: ["admin","hr"], description: "HR letters" },
      { label: "Feedback",             href: "/performance-feedback/my-reports",     icon: <FileText className="h-[15px] w-[15px]" />,       description: "Feedback" },
      { label: "Feedback Assignments", href: "/performance-feedback/assignments",    icon: <ClipboardList className="h-[15px] w-[15px]" />,  description: "Feedback tasks" },
      { label: "Dev. Plans",           href: "/performance-feedback/development-plan",icon: <Target className="h-[15px] w-[15px]" />,        description: "Dev plans" },
      { label: "Team Reports",         href: "/performance-feedback/team-reports",   icon: <BarChart3 className="h-[15px] w-[15px]" />,      roles: ["admin","hr","manager"], description: "Team feedback" },
    ],
  },
  {
    title: "Admin",
    items: [
      { label: "Access Control",       href: "/settings/access-control",        icon: <Settings className="h-[15px] w-[15px]" />,    pageCode: "ACCESS_CONTROL", roles: ["admin"], description: "Access" },
      { label: "Page Access",          href: "/super-admin/page-access",        icon: <ShieldCheck className="h-[15px] w-[15px]" />, roles: ["admin"], description: "Page access" },
      { label: "Settings",             href: "/settings",                       icon: <Settings className="h-[15px] w-[15px]" />,    description: "Settings" },
      { label: "Comm. Config",         href: "/settings/communication-config",  icon: <Settings2 className="h-[15px] w-[15px]" />,  roles: ["admin"], description: "Email/SMS" },
      { label: "Call Centre Config",   href: "/settings/call-centre-config",    icon: <Settings2 className="h-[15px] w-[15px]" />,  roles: ["admin"], description: "Call centre" },
      { label: "Org Masters",          href: "/org-masters",                    icon: <Building2 className="h-[15px] w-[15px]" />,   roles: ["admin","hr"], description: "Masters" },
      { label: "Location & Policies",  href: "/org-masters/locations-policies", icon: <Building2 className="h-[15px] w-[15px]" />,   pageCode: "ORG_MASTERS", roles: ["admin","hr"], description: "Locations" },
      { label: "Process Config",       href: "/process-config",                 icon: <Network className="h-[15px] w-[15px]" />,     roles: ["admin","hr","process_manager"], description: "Process" },
      { label: "Leave Types",          href: "/leave-types",                    icon: <CalendarDays className="h-[15px] w-[15px]" />,roles: ["admin","hr"], description: "Leave types" },
      { label: "Statutory Config",     href: "/payroll/statutory-config",       icon: <Landmark className="h-[15px] w-[15px]" />,    roles: ["admin","hr","finance"], description: "Statutory" },
      { label: "Compliance",           href: "/compliance/statutory",           icon: <Landmark className="h-[15px] w-[15px]" />,    roles: ["admin","hr","finance"], description: "Compliance" },
      { label: "Labour Compliance",    href: "/compliance/labour",              icon: <Landmark className="h-[15px] w-[15px]" />,    pageCode: "LABOUR_COMPLIANCE", roles: ["admin","hr","finance"], description: "Labour" },
      { label: "DPDP / Privacy",       href: "/compliance/dpdp",                icon: <ShieldCheck className="h-[15px] w-[15px]" />, roles: ["admin","hr"], description: "DPDP" },
      { label: "Client Master",        href: "/client-master",                  icon: <Users className="h-[15px] w-[15px]" />,       roles: ["admin","hr"], description: "Clients" },
      { label: "Integration Hub",      href: "/integration-hub",                icon: <Network className="h-[15px] w-[15px]" />,     roles: ["admin"], description: "Integration" },
      { label: "LMS Integration",      href: "/lms/integration",                icon: <Network className="h-[15px] w-[15px]" />,     pageCode: "LMS_INTEGRATION", roles: ["admin"], description: "LMS integration" },
      { label: "Workflow Admin",        href: "/workflow-admin",                 icon: <Network className="h-[15px] w-[15px]" />,     pageCode: "WORKFLOW_ADMIN", description: "Workflows" },
      { label: "Customization",         href: "/customization",                  icon: <Settings2 className="h-[15px] w-[15px]" />,   pageCode: "CUSTOMIZATION_MANAGER", description: "Customization rules" },
      { label: "Assets",                href: "/assets",                         icon: <Package className="h-[15px] w-[15px]" />,     description: "Assets" },
      { label: "Assets Manager",        href: "/assets-manager",                 icon: <Package className="h-[15px] w-[15px]" />,     pageCode: "ASSETS_MANAGER", description: "Asset management" },
      { label: "Mobility",              href: "/mobility",                       icon: <Users className="h-[15px] w-[15px]" />,       pageCode: "MOBILITY", description: "Mobility" },
      { label: "ERP",                   href: "/erp",                            icon: <Server className="h-[15px] w-[15px]" />,      pageCode: "ERP", description: "ERP" },
      { label: "Portal Data Manager",   href: "/portal-data-manager",            icon: <Server className="h-[15px] w-[15px]" />,      pageCode: "PORTAL_DATA_MANAGER", description: "Portal data" },
      { label: "Migration Console",     href: "/migration-console",              icon: <Server className="h-[15px] w-[15px]" />,      roles: ["admin"], description: "Data migration" },
      { label: "Exit Command Center",   href: "/exit/command-center",            icon: <UserMinus className="h-[15px] w-[15px]" />,   pageCode: "EXIT_COMMAND_CENTER", description: "Exit ops" },
      { label: "Exit Management",       href: "/exit-management",                icon: <UserMinus className="h-[15px] w-[15px]" />,   roles: ["admin","hr"], description: "Exit" },
      { label: "Maternity Leave",       href: "/maternity-leave",                icon: <Heart className="h-[15px] w-[15px]" />,       roles: ["admin","hr"], description: "Maternity" },
      { label: "Comm. Templates",       href: "/communication/templates",        icon: <FileText className="h-[15px] w-[15px]" />,    roles: ["admin","hr"], description: "Message templates" },
      { label: "Comm. Dispatch",        href: "/communication/dispatch",         icon: <Bell className="h-[15px] w-[15px]" />,        roles: ["admin","hr"], description: "Send messages" },
      { label: "Comm. History",         href: "/communication/history",          icon: <FileText className="h-[15px] w-[15px]" />,    roles: ["admin","hr"], description: "Dispatch history" },
      { label: "Audit Log",             href: "/audit-log",                      icon: <FileText className="h-[15px] w-[15px]" />,    roles: ["admin","super_admin","payroll_head","hr","wfm"], description: "System audit trail" },
      { label: "WFM Extensions",        href: "/wfm/extensions",                 icon: <Settings2 className="h-[15px] w-[15px]" />,   pageCode: "WFM_EXTENSIONS", description: "WFM extensions" },
    ],
  },
];
