import { beforeEach, describe, expect, it, vi } from "vitest";

/**
 * Part A is the half of a salary TDS certificate that a payroll system cannot
 * produce: tax deposited, challan and BSR codes, TRACES verification. It is
 * generated by TRACES from the quarterly return. A system that generated its
 * own would be issuing a document nobody can verify.
 *
 * So the rules under test are about honesty, not arithmetic. An absent Part A
 * must read as absent rather than as an error. An unverified one must not reach
 * the employee. And the form number must follow the year the certificate covers
 * — Form 16 before 1 April 2026, Form 130 after.
 */

const { execute } = vi.hoisted(() => ({ execute: vi.fn() }));
vi.mock("../../../db/mysql.js", () => ({ db: { execute } }));

import {
  getPartAAvailability,
  recordPartA,
  verifyPartA,
} from "../tds-certificate-part-a.service.js";

describe("Part A availability", () => {
  beforeEach(() => execute.mockReset());

  it("reports a missing certificate as not uploaded, not as a failure", () => {
    // Normal for most of a year: TRACES only issues it once the quarterly
    // returns are filed. Treating it as an error would deny an employee their
    // Part B figures over a document that does not exist yet.
    execute.mockResolvedValue([[], []]);
    return getPartAAvailability("emp-1", 2026).then((a) => {
      expect(a.status).toBe("not_uploaded");
      expect(a.present).toBe(false);
      expect(a.verified).toBe(false);
      expect(a.message).toMatch(/TRACES/);
      expect(a.message).toMatch(/FY 2026-27/);
    });
  });

  it("withholds the document until it is verified", async () => {
    execute.mockResolvedValue([[{
      id: "pa-1", certificate_number: "ABCDE1234F", vault_document_id: "vault-9",
      stored_filename: "abc.pdf", storage_category: "tds-certificates",
      covers_quarters: "Q1-Q4", verified_at: null, form_number: "130",
    }], []]);

    const a = await getPartAAvailability("emp-1", 2026);

    expect(a.present).toBe(true);
    expect(a.verified).toBe(false);
    expect(a.status).toBe("awaiting_verification");
    // The vault id is the means of downloading it, so it is withheld until
    // someone has confirmed the document matches this employee and year.
    expect(a.vaultDocumentId).toBeNull();
    // The path is withheld too — an unverified certificate must be unreachable,
    // not merely unadvertised.
    expect(a.downloadPath).toBeNull();
  });

  it("releases the document once verified", async () => {
    execute.mockResolvedValue([[{
      id: "pa-1", certificate_number: "ABCDE1234F", vault_document_id: "vault-9",
      stored_filename: "abc.pdf", storage_category: "tds-certificates",
      covers_quarters: "Q1-Q4", verified_at: "2027-06-10 10:00:00", form_number: "130",
    }], []]);

    const a = await getPartAAvailability("emp-1", 2026);

    expect(a.status).toBe("verified");
    expect(a.verified).toBe(true);
    expect(a.vaultDocumentId).toBe("vault-9");
    expect(a.certificateNumber).toBe("ABCDE1234F");
    expect(a.downloadPath).toBe("/api/files/tds-certificates/abc.pdf");
  });

  it("names the form the year is actually issued under", async () => {
    execute.mockResolvedValue([[], []]);

    // FY 2025-26 predates the Income-tax Act, 2025.
    expect((await getPartAAvailability("emp-1", 2025)).expectedFormNumber).toBe("16");
    // FY 2026-27 is the first year under it.
    expect((await getPartAAvailability("emp-1", 2026)).expectedFormNumber).toBe("130");
  });

  it("degrades to not_uploaded when the table does not exist yet", async () => {
    // Migration 1032 unapplied. Part B is still useful; an outage here must not
    // deny an employee their salary figures.
    // Scoped to this one call. A broad mockRejectedValue leaves a rejected
    // promise for any later call to pick up, which vitest reports as an
    // unhandled rejection even though the service catches its own.
    execute.mockImplementationOnce(() =>
      Promise.reject(new Error("Table 'tds_certificate_part_a' doesn't exist")),
    );

    await expect(getPartAAvailability("emp-1", 2026)).resolves.toMatchObject({
      status: "not_uploaded",
      present: false,
      verified: false,
    });
  });

  it("rejects a malformed year rather than guessing one", async () => {
    await expect(getPartAAvailability("emp-1", 26 as number)).rejects.toThrow(/four-digit/);
    expect(execute).not.toHaveBeenCalled();
  });
});

describe("recording and verifying Part A", () => {
  beforeEach(() => execute.mockReset());

  it("stamps the form number from the year, not from today", async () => {
    execute.mockResolvedValue([{ affectedRows: 1 }, []]);

    const older = await recordPartA({
      employeeId: "emp-1", financialYear: 2025,
      vaultDocumentId: "vault-1", storedFilename: "a.pdf", uploadedBy: "user-1",
    });
    expect(older.formNumber).toBe("16");

    const current = await recordPartA({
      employeeId: "emp-1", financialYear: 2026,
      vaultDocumentId: "vault-2", storedFilename: "b.pdf", uploadedBy: "user-1",
    });
    expect(current.formNumber).toBe("130");
  });

  it("does not mark a newly uploaded certificate as verified", async () => {
    execute.mockResolvedValue([{ affectedRows: 1 }, []]);

    await recordPartA({
      employeeId: "emp-1", financialYear: 2026,
      vaultDocumentId: "vault-1", storedFilename: "a.pdf", uploadedBy: "user-1",
    });

    const [sql] = execute.mock.calls[0] as [string, unknown[]];
    // Uploading is clerical; confirming the document belongs to this employee
    // and year is a payroll judgement. Conflating them lets a misfiled
    // certificate reach an employee.
    expect(sql).toContain("verified_by        = NULL");
    expect(sql).toContain("verified_at        = NULL");
  });

  it("replaces a reissued certificate instead of accumulating rivals", async () => {
    execute.mockResolvedValue([{ affectedRows: 2 }, []]);

    await recordPartA({
      employeeId: "emp-1", financialYear: 2026,
      vaultDocumentId: "vault-new", storedFilename: "c.pdf", uploadedBy: "user-1",
    });

    const [sql] = execute.mock.calls[0] as [string, unknown[]];
    expect(sql).toContain("ON DUPLICATE KEY UPDATE");
    // A replacement clears verification: a new document has not been checked
    // just because its predecessor was.
    expect(sql).toContain("verified_at        = NULL");
  });

  it("reports whether verification actually matched a row", async () => {
    execute.mockResolvedValue([{ affectedRows: 1 }, []]);
    expect(await verifyPartA("emp-1", 2026, "payroll-user")).toBe(true);

    execute.mockResolvedValue([{ affectedRows: 0 }, []]);
    expect(await verifyPartA("emp-missing", 2026, "payroll-user")).toBe(false);
  });
});
