import type {
  BpoMasterColumn,
  BpoMasterFormat,
  BpoMasterReportDefinition,
} from "./bpo-master-report-catalog.js";

const c = (
  key: string,
  format: BpoMasterFormat = "text",
  options: Omit<BpoMasterColumn, "key" | "label" | "format"> = {}
): BpoMasterColumn => ({ key, label: key, format, ...options });

const AUDIT_ROLES = [
  "super_admin", "admin", "ceo", "coo", "hr_head", "finance_head", "accounts_head",
  "payroll_head", "quality", "compliance", "compliance_head", "internal_auditor", "security_head",
];

const JOURNEY_ROLES = [
  "super_admin", "admin", "hr", "hr_head", "recruiter", "recruitment_head", "trainer", "training",
  "operations_manager", "process_manager", "manager", "quality", "payroll", "payroll_head", "branch_head",
];

export const BPO_MASTER_REPORT_EXTENSIONS: BpoMasterReportDefinition[] = [
  {
    code: "bpo-audit-compliance-control-master",
    name: "BPO AUDIT, COMPLIANCE, RISK & CONTROL MASTER REPORT",
    domain: "AUDIT / COMPLIANCE / CONTROL",
    description: "One control-evidence event ledger covering user actions, sensitive changes, approvals, policy evidence, privacy, statutory, security and remediation closure.",
    rowGrain: "ONE ROW PER AUDIT / CONTROL / APPROVAL / COMPLIANCE EVENT",
    primaryKey: ["SOURCE_TABLE", "SOURCE_RECORD_ID", "ACTIVITY_DATE_TIME"],
    viewRoles: AUDIT_ROLES,
    exportRoles: ["super_admin", "admin", "ceo", "coo", "compliance_head", "internal_auditor", "security_head"],
    dateStandard: "DD-MMM-YYYY",
    employeeCodePolicy: "MANDATORY",
    aggregateEmployeeCode: "AGGREGATE",
    columns: [
      c("EMPLOYEE_CODE"), c("REPORT_DATE", "date"), c("ACTIVITY_DATE_TIME"), c("EVENT_ID"),
      c("EVENT_SEQUENCE", "number"), c("AUDIT_CATEGORY"), c("CONTROL_DOMAIN"), c("MODULE"),
      c("ACTION_TYPE"), c("ACTION_STATUS", "status"), c("ENTITY_TYPE"), c("ENTITY_ID"),
      c("SOURCE_SCHEMA"), c("SOURCE_TABLE"), c("SOURCE_RECORD_ID"), c("REQUEST_ID"),
      c("ACTOR_USER_ID", "masked", { sensitive: true }), c("ACTOR_EMPLOYEE_CODE"), c("ACTOR_NAME"),
      c("ACTOR_ROLE"), c("ACTOR_BRANCH"), c("ACTOR_PROCESS"), c("SUBJECT_EMPLOYEE_CODE"),
      c("SUBJECT_EMPLOYEE_NAME"), c("SUBJECT_CANDIDATE_ID"), c("SUBJECT_CANDIDATE_NAME"),
      c("IP_ADDRESS", "masked", { sensitive: true }), c("USER_AGENT", "text", { sensitive: true }),
      c("OLD_VALUE", "text", { sensitive: true }), c("NEW_VALUE", "text", { sensitive: true }),
      c("CHANGE_SUMMARY", "text", { sensitive: true }), c("REASON"), c("REMARKS"),
      c("APPROVAL_WORKFLOW"), c("APPROVAL_STEP"), c("APPROVAL_DECISION", "status"),
      c("APPROVAL_DUE_DATE", "date"), c("APPROVAL_COMPLETED_DATE", "date"), c("SLA_STATUS", "status"),
      c("POLICY_CODE"), c("POLICY_VERSION"), c("STATUTORY_AREA"), c("DPDP_PURPOSE"),
      c("CONSENT_STATUS", "status"), c("DATA_CLASSIFICATION"), c("RISK_LEVEL", "status"),
      c("CONTROL_RESULT", "status"), c("EXCEPTION_FLAG", "boolean"), c("EXCEPTION_TYPE"),
      c("FINANCIAL_IMPACT", "currency", { sensitive: true }), c("CUSTOMER_IMPACT_FLAG", "boolean"),
      c("PRIVACY_IMPACT_FLAG", "boolean"), c("EVIDENCE_REFERENCE"), c("EVIDENCE_STATUS", "status"),
      c("CORRECTIVE_ACTION"), c("PREVENTIVE_ACTION"), c("ACTION_OWNER"), c("ACTION_DUE_DATE", "date"),
      c("ACTION_CLOSED_DATE", "date"), c("VERIFIED_BY"), c("VERIFICATION_STATUS", "status"),
      c("RECURRENCE_FLAG", "boolean"), c("DATA_SOURCE"), c("SOURCE_FRESHNESS"),
    ],
    sourceDomains: [
      "GENERAL AUDIT", "SENSITIVE AUDIT", "APPROVAL WORKFLOW", "SECURITY", "PRIVACY/DPDP",
      "STATUTORY", "QUALITY COMPLIANCE", "POLICY", "REMEDIATION",
    ],
    controlNotes: [
      "Every event must retain source schema, source table and source record ID.",
      "Old/new values and identity evidence are restricted and masked without export authority.",
      "Compliance exceptions require owner, due date, closure and independent verification evidence.",
      "Missing source columns are unavailable, never inferred from unrelated fields.",
    ],
  },
  {
    code: "bpo-interview-to-exit-journey-ledger",
    name: "BPO INTERVIEW-TO-EXIT EMPLOYEE JOURNEY & ACTIVITY LEDGER",
    domain: "END-TO-END EMPLOYEE JOURNEY",
    description: "Chronological event ledger from candidate creation and interview through onboarding, employment, payroll, performance, movement and final exit clearance.",
    rowGrain: "ONE ROW PER CANDIDATE / EMPLOYEE JOURNEY ACTIVITY EVENT",
    primaryKey: ["JOURNEY_PERSON_KEY", "ACTIVITY_DATE_TIME", "SOURCE_TABLE", "SOURCE_RECORD_ID"],
    viewRoles: JOURNEY_ROLES,
    exportRoles: ["super_admin", "admin", "hr", "hr_head", "recruitment_head", "branch_head"],
    dateStandard: "DD-MMM-YYYY",
    employeeCodePolicy: "MANDATORY",
    columns: [
      c("EMPLOYEE_CODE"), c("REPORT_DATE", "date"), c("JOURNEY_PERSON_KEY"), c("CANDIDATE_ID"),
      c("CANDIDATE_CODE"), c("EMPLOYEE_ID"), c("PERSON_NAME"), c("MOBILE_NUMBER", "phone", { sensitive: true }),
      c("EMAIL_ADDRESS", "email", { sensitive: true }), c("BRANCH"), c("PROCESS"), c("DEPARTMENT"),
      c("DESIGNATION"), c("REPORTING_MANAGER_CODE"), c("REPORTING_MANAGER_NAME"), c("JOURNEY_PHASE"),
      c("JOURNEY_STAGE"), c("JOURNEY_SUB_STAGE"), c("ACTIVITY_TYPE"), c("ACTIVITY_STATUS", "status"),
      c("ACTIVITY_DATE_TIME"), c("ACTIVITY_DATE", "date"), c("EVENT_SEQUENCE", "number"),
      c("DAYS_FROM_PREVIOUS_EVENT", "number"), c("STAGE_AGEING_DAYS", "number"), c("ACTIVITY_DESCRIPTION"),
      c("PREVIOUS_STAGE"), c("NEW_STAGE"), c("PREVIOUS_VALUE", "text", { sensitive: true }),
      c("NEW_VALUE", "text", { sensitive: true }), c("ACTOR_USER_ID", "masked", { sensitive: true }),
      c("ACTOR_EMPLOYEE_CODE"), c("ACTOR_NAME"), c("ACTOR_ROLE"), c("APPROVER_USER_ID", "masked", { sensitive: true }),
      c("APPROVER_EMPLOYEE_CODE"), c("APPROVER_NAME"), c("APPROVAL_STATUS", "status"), c("REMARKS"),
      c("REASON"), c("REQUISITION_ID"), c("INTERVIEW_ROUND"), c("INTERVIEW_RESULT", "status"),
      c("OFFER_STATUS", "status"), c("OFFER_DATE", "date"), c("EXPECTED_JOINING_DATE", "date"),
      c("ACTUAL_JOINING_DATE", "date"), c("BGV_CHECK_TYPE"), c("BGV_STATUS", "status", { sensitive: true }),
      c("DOCUMENT_TYPE"), c("DOCUMENT_STATUS", "status"), c("TRAINING_BATCH_CODE"), c("TRAINING_STATUS", "status"),
      c("ASSESSMENT_SCORE", "percentage"), c("PRODUCTION_RELEASE_DATE", "date"), c("LIFECYCLE_EVENT_TYPE"),
      c("EFFECTIVE_DATE", "date"), c("PAYROLL_MONTH", "month"), c("PAYROLL_STATUS", "status"),
      c("PERFORMANCE_EVENT"), c("PIP_STATUS", "status"), c("EXIT_REQUEST_ID"), c("EXIT_STAGE"),
      c("EXIT_STATUS", "status"), c("LAST_WORKING_DATE", "date"), c("CLEARANCE_DEPARTMENT"),
      c("CLEARANCE_STATUS", "status"), c("FNF_STATUS", "status"), c("SOURCE_SCHEMA"), c("SOURCE_TABLE"),
      c("SOURCE_RECORD_ID"), c("EVIDENCE_REFERENCE"), c("DATA_SOURCE"), c("SOURCE_FRESHNESS"),
    ],
    sourceDomains: [
      "ATS", "INTERVIEW", "OFFER", "ONBOARDING", "BGV", "DOCUMENTS", "TRAINING", "EMPLOYEE MASTER",
      "LIFECYCLE", "ATTENDANCE/LEAVE", "PERFORMANCE", "PAYROLL", "EXIT/CLEARANCE",
    ],
    controlNotes: [
      "Pre-join events use PENDING EMPLOYEE CODE until the ATS onboarding bridge links an employee.",
      "Every activity preserves who performed it, when it occurred, source record ID and prior/new state.",
      "Chronology is calculated from event timestamps without replacing source timestamps.",
      "Restricted candidate, BGV and salary values require authorised export rights.",
    ],
  },
  {
    code: "bpo-report-data-lineage-reconciliation-master",
    name: "BPO REPORT DATA LINEAGE, RECONCILIATION & ACCURACY MASTER REPORT",
    domain: "DATA GOVERNANCE / REPORT ACCURACY",
    description: "Field-level report lineage and runtime source verification showing exact source columns, transformations, freshness, completeness, duplicates, orphan records and reconciliation status.",
    rowGrain: "ONE ROW PER MASTER REPORT FIELD PER SOURCE CONTRACT",
    primaryKey: ["REPORT_CODE", "REPORT_FIELD", "SOURCE_SCHEMA", "SOURCE_TABLE"],
    viewRoles: ["super_admin", "admin", "ceo", "coo", "internal_auditor", "compliance_head", "it_manager", "finance_head", "hr_head"],
    exportRoles: ["super_admin", "admin", "internal_auditor", "compliance_head", "it_manager"],
    dateStandard: "DD-MMM-YYYY",
    employeeCodePolicy: "MANDATORY",
    aggregateEmployeeCode: "AGGREGATE",
    columns: [
      c("EMPLOYEE_CODE"), c("REPORT_DATE", "date"), c("REPORT_CODE"), c("REPORT_NAME"), c("REPORT_DOMAIN"),
      c("REPORT_GRAIN"), c("REPORT_PRIMARY_KEY"), c("REPORT_FIELD"), c("FIELD_FORMAT"), c("SENSITIVE_FLAG", "boolean"),
      c("SOURCE_SCHEMA"), c("SOURCE_TABLE"), c("SOURCE_COLUMN"), c("SOURCE_DATA_TYPE"), c("SOURCE_STATUS", "status"),
      c("COLUMN_STATUS", "status"), c("SOURCE_OF_TRUTH_FLAG", "boolean"), c("TRANSFORMATION_RULE"),
      c("AGGREGATION_RULE"), c("FILTER_RULE"), c("JOIN_RULE"), c("NULL_POLICY"), c("ZERO_POLICY"),
      c("DATE_STANDARD"), c("EMPLOYEE_CODE_POLICY"), c("SOURCE_ROW_COUNT", "number"),
      c("REPORT_ROW_COUNT", "number"), c("DISTINCT_GRAIN_COUNT", "number"), c("DUPLICATE_GRAIN_COUNT", "number"),
      c("NULL_VALUE_COUNT", "number"), c("NULL_VALUE_PERCENTAGE", "percentage"), c("INVALID_VALUE_COUNT", "number"),
      c("ORPHAN_EMPLOYEE_COUNT", "number"), c("ORPHAN_BRANCH_COUNT", "number"), c("ORPHAN_PROCESS_COUNT", "number"),
      c("SOURCE_TOTAL", "number"), c("REPORT_TOTAL", "number"), c("RECONCILIATION_VARIANCE", "number"),
      c("RECONCILIATION_VARIANCE_PERCENTAGE", "percentage"), c("RECONCILIATION_STATUS", "status"),
      c("SOURCE_MAX_UPDATED_AT"), c("SOURCE_FRESHNESS_MINUTES", "number"), c("FRESHNESS_STATUS", "status"),
      c("DATA_COMPLETENESS_PERCENTAGE", "percentage"), c("DATA_ACCURACY_STATUS", "status"),
      c("LAST_VALIDATED_AT"), c("VALIDATED_BY"), c("VALIDATION_METHOD"), c("EXCEPTION_COUNT", "number"),
      c("EXCEPTION_SEVERITY", "status"), c("EXCEPTION_DETAIL"), c("REMEDIATION_OWNER"), c("REMEDIATION_DUE_DATE", "date"),
      c("REMEDIATION_STATUS", "status"), c("UAT_STATUS", "status"), c("BUSINESS_OWNER_SIGNOFF"),
      c("TECHNICAL_OWNER_SIGNOFF"), c("DATA_SOURCE"),
    ],
    sourceDomains: [
      "INFORMATION SCHEMA", "REPORT CATALOG", "SOURCE CONTRACT", "ROW GRAIN", "DATA QUALITY",
      "RECONCILIATION", "FRESHNESS", "UAT", "BUSINESS SIGN-OFF",
    ],
    controlNotes: [
      "A field is available only when its exact runtime source column exists.",
      "Report totals must reconcile to source totals at the declared grain before sign-off.",
      "Missing, stale, duplicate and orphan data are reported separately and never converted to zero.",
      "100% accuracy can be claimed only after runtime reconciliation and business-owner sign-off.",
    ],
  },
];
