-- 1306_client_billing_cutover_addendum_columns.sql
--
-- Client Billing Historical Cutover — design addendum (2026-08-19) A3/A4 columns.
-- (docs/superpowers/specs/2026-08-19-client-billing-cutover-addendum.md,
--  docs/superpowers/plans/2026-08-19-client-billing-cutover.md)
--
-- Adds two nullable CHAR(36) columns to the two throwaway *_migration_staging
-- tables created by 1304/1305, to hold this addendum's own resolution results:
--
-- - client_invoice_migration_staging.target_cost_centre_id (A3): the resolved
--   cost_centre_master.id for a row whose src_cost_center matched, so a later
--   load task does not have to redo that lookup. NULL for the 87 rows whose
--   legacy cost_center genuinely does not exist in cost_centre_master (A3's
--   own decision: excluded from this cutover pass, not force-mapped).
-- - client_credit_note_migration_staging.target_cost_centre_id (A3): same,
--   mirrored on the credit-note staging table (all 144 rows resolve cleanly,
--   re-confirmed live — this column exists for symmetry/future-proofing, not
--   because any row needs it today).
-- - client_credit_note_migration_staging.target_invoice_id (A4): the resolved
--   client_invoice_migration_staging.target_id (the future client_invoice.id
--   a later load task will actually insert) for the 53 of 144 credit notes
--   whose proforma_bill_no matches exactly one staged invoice's bill_no, with
--   agreeing cost centres. NULL for the other 91 (86 ambiguous + 5 missing
--   proforma_bill_no) — never force-guessed.
--
-- target_id already exists on both staging tables (1304/1305) but is reserved
-- for a different purpose: the row's OWN future primary key, pre-generated by
-- extract.ts so a later load step (and this addendum's A4 matching) can refer
-- to a not-yet-loaded row's eventual id. target_cost_centre_id/target_invoice_id
-- are separate columns, not a repurposing of target_id, to keep that meaning
-- unambiguous.
--
-- ── Why the information_schema-guarded PREPARE/EXECUTE idiom ───────────────
-- MySQL 8 does not support `ALTER TABLE ... ADD COLUMN IF NOT EXISTS` as a
-- single clause without this getting recorded as applied even when it silently
-- didn't (this repo's own migration-safety history, e.g. 431/1241/1242/1304).
-- information_schema.COLUMNS checked first, the real ALTER built as a string
-- only when the column does not already exist, then PREPARE/EXECUTE/DEALLOCATE.
-- Naturally idempotent; safe to re-run.
--
-- ── Safety ───────────────────────────────────────────────────────────────────
-- Three ALTER TABLEs, each adding one nullable CHAR(36) column to a throwaway
-- staging table that is not client_invoice/client_credit_note/client_invoice_line/
-- client_credit_note_line (0 rows in all four as of this commit) and holds no
-- FK to anything, so no default-backfill cost and no referential-integrity risk.
-- No DROP, no DELETE, no data migration (that is this addendum's own
-- validate.ts UPDATE step, a separate script, never this file).
--
-- Rollback:
--   ALTER TABLE client_credit_note_migration_staging DROP COLUMN target_invoice_id;
--   ALTER TABLE client_credit_note_migration_staging DROP COLUMN target_cost_centre_id;
--   ALTER TABLE client_invoice_migration_staging DROP COLUMN target_cost_centre_id;

SET @add_cims_target_cc = (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE client_invoice_migration_staging ADD COLUMN target_cost_centre_id CHAR(36) NULL AFTER target_id',
    'SELECT 1 -- client_invoice_migration_staging.target_cost_centre_id already exists'
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'client_invoice_migration_staging' AND COLUMN_NAME = 'target_cost_centre_id'
);
PREPARE _stmt FROM @add_cims_target_cc;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @add_ccnms_target_cc = (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE client_credit_note_migration_staging ADD COLUMN target_cost_centre_id CHAR(36) NULL AFTER target_id',
    'SELECT 1 -- client_credit_note_migration_staging.target_cost_centre_id already exists'
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'client_credit_note_migration_staging' AND COLUMN_NAME = 'target_cost_centre_id'
);
PREPARE _stmt FROM @add_ccnms_target_cc;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @add_ccnms_target_invoice = (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE client_credit_note_migration_staging ADD COLUMN target_invoice_id CHAR(36) NULL AFTER target_cost_centre_id',
    'SELECT 1 -- client_credit_note_migration_staging.target_invoice_id already exists'
  )
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'client_credit_note_migration_staging' AND COLUMN_NAME = 'target_invoice_id'
);
PREPARE _stmt FROM @add_ccnms_target_invoice;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;
