-- 2113: more screening facts per candidate, mostly from portal exports (WorkIndia / Naukri / Apna ...): education status,
-- stream, last salary, previous industry, state, address. Side table only (he_lead stays narrow). Guarded, additive.
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'education_status') = 0, "ALTER TABLE he_lead_profile ADD COLUMN education_status ENUM('completed','pursuing','dropped') NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'stream') = 0, 'ALTER TABLE he_lead_profile ADD COLUMN stream VARCHAR(30) NULL', 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'last_salary') = 0, 'ALTER TABLE he_lead_profile ADD COLUMN last_salary INT UNSIGNED NULL', 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'prev_industry') = 0, 'ALTER TABLE he_lead_profile ADD COLUMN prev_industry VARCHAR(30) NULL', 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'state') = 0, 'ALTER TABLE he_lead_profile ADD COLUMN state VARCHAR(60) NULL', 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'address') = 0, 'ALTER TABLE he_lead_profile ADD COLUMN address VARCHAR(300) NULL', 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'he_lead_profile' AND COLUMN_NAME = 'dob') = 0, 'ALTER TABLE he_lead_profile ADD COLUMN dob DATE NULL', 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
