-- 2134: Qualified follow-up live sender. Per-channel attempt counters and error text, the WhatsApp message id, the missing-detail list,
-- the sending-claim timestamp, the 'test' row tag and the calling-file index. Additive and re-runnable (each ALTER guarded through
-- information_schema + PREPARE; MODIFY of the enum is idempotent).
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'email_attempts') = 0, "ALTER TABLE qualified_followup ADD COLUMN email_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'wa_attempts') = 0, "ALTER TABLE qualified_followup ADD COLUMN wa_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'call_attempts') = 0, "ALTER TABLE qualified_followup ADD COLUMN call_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'email_error') = 0, "ALTER TABLE qualified_followup ADD COLUMN email_error VARCHAR(255) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'call_error') = 0, "ALTER TABLE qualified_followup ADD COLUMN call_error VARCHAR(255) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'wa_message_id') = 0, "ALTER TABLE qualified_followup ADD COLUMN wa_message_id CHAR(36) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'missing_details') = 0, "ALTER TABLE qualified_followup ADD COLUMN missing_details VARCHAR(100) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'step_claimed_at') = 0, "ALTER TABLE qualified_followup ADD COLUMN step_claimed_at DATETIME NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

ALTER TABLE qualified_followup MODIFY mode_at_enqueue ENUM('dry_run','live','test') NOT NULL;

SET @s = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND INDEX_NAME = 'idx_qfu_callfile') = 0, "ALTER TABLE qualified_followup ADD INDEX idx_qfu_callfile (call_state, call_file_batch_id)", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
