-- 2137: Calling-file batches every 2 hours with one file per slot. qualified_followup_call_batch gets the row tag, the IST slot it ran
-- for, a slot claim (unique per tag; cleared when a batch fails so the slot can be retried) and a JSON summary of counts (rows, by
-- drive type, by branch, skipped duplicates by reason) for the 08:30 report. Additive and re-runnable (information_schema-guarded).
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup_call_batch' AND COLUMN_NAME = 'mode_tag') = 0, "ALTER TABLE qualified_followup_call_batch ADD COLUMN mode_tag VARCHAR(10) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup_call_batch' AND COLUMN_NAME = 'slot_key') = 0, "ALTER TABLE qualified_followup_call_batch ADD COLUMN slot_key VARCHAR(16) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup_call_batch' AND COLUMN_NAME = 'slot_claim') = 0, "ALTER TABLE qualified_followup_call_batch ADD COLUMN slot_claim VARCHAR(16) NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup_call_batch' AND COLUMN_NAME = 'summary') = 0, "ALTER TABLE qualified_followup_call_batch ADD COLUMN summary JSON NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup_call_batch' AND INDEX_NAME = 'uq_qfcb_slot') = 0, "ALTER TABLE qualified_followup_call_batch ADD UNIQUE KEY uq_qfcb_slot (mode_tag, slot_claim)", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup_call_batch' AND INDEX_NAME = 'idx_qfcb_tag_created') = 0, "ALTER TABLE qualified_followup_call_batch ADD INDEX idx_qfcb_tag_created (mode_tag, created_at)", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND INDEX_NAME = 'idx_qfu_mobile_batch') = 0, "ALTER TABLE qualified_followup ADD INDEX idx_qfu_mobile_batch (mobile10, mode_at_enqueue, call_file_batch_id)", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
