-- 2148: Final integration of the unified follow-up with the selection criteria and WS3 shortlisting.
-- qualified_followup.shortlist_id: the shortlist_candidate row a person was enrolled from (criteria_version_id comes with 2145 and is
-- added here only where 2145 skipped it). shortlist_run.trigger_kind (manual | evening | arrival) and evening_date with a unique key, so
-- the evening preview worker makes at most one run per requisition x source x IST day even when two processes race (NULL = not evening).
-- Additive and re-runnable (information_schema-guarded), no foreign keys.
SET @s = IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup') = 1 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'shortlist_id') = 0, "ALTER TABLE qualified_followup ADD COLUMN shortlist_id BIGINT UNSIGNED NULL COMMENT 'shortlist_candidate.id the person was enrolled from'", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup') = 1 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'qualified_followup' AND COLUMN_NAME = 'criteria_version_id') = 0, "ALTER TABLE qualified_followup ADD COLUMN criteria_version_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'shortlist_run') = 1 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'shortlist_run' AND COLUMN_NAME = 'trigger_kind') = 0, "ALTER TABLE shortlist_run ADD COLUMN trigger_kind VARCHAR(10) NOT NULL DEFAULT 'manual' COMMENT 'manual | evening | arrival'", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'shortlist_run') = 1 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'shortlist_run' AND COLUMN_NAME = 'evening_date') = 0, "ALTER TABLE shortlist_run ADD COLUMN evening_date DATE NULL COMMENT 'IST day of an evening run; NULL otherwise'", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s = IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'shortlist_run') = 1 AND (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'shortlist_run' AND INDEX_NAME = 'uq_slr_evening') = 0, "ALTER TABLE shortlist_run ADD UNIQUE KEY uq_slr_evening (requisition_id, source_kind, evening_date)", 'SELECT 1'); PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
