import type { RowDataPacket } from "mysql2/promise";
import { db } from "../../db/mysql.js";
import { statutoryRegimeForFinancialYear } from "./statutory-regime.js";

/**
 * Part A of the salary TDS certificate — the half a payroll system cannot make.
 *
 * Part B (salary breakup, deductions, tax computed) is produced here from the
 * year's actual payroll lines. Part A (tax deposited, challan and BSR codes,
 * TRACES verification) is generated by TRACES from the quarterly return and
 * downloaded by the employer. An HRMS that generated its own "Part A" would be
 * issuing a document nobody can verify, so this ingests one instead.
 *
 * Until a verified Part A exists for a year, that year's certificate is
 * incomplete and must be described that way rather than presented as if it were
 * a full certificate.
 */

export interface PartARecord {
  id: string;
  employee_id: string;
  financial_year: number;
  form_number: string;
  certificate_number: string | null;
  vault_document_id: string;
  stored_filename: string;
  storage_category: string;
  covers_quarters: string | null;
  uploaded_by: string;
  uploaded_at: string;
  verified_by: string | null;
  verified_at: string | null;
}

export interface PartAAvailability {
  financialYear: number;
  /** Form the certificate for this year is issued as — "16" or "130". */
  expectedFormNumber: string;
  /** A record exists, whether or not anyone has verified it. */
  present: boolean;
  /** Verified by someone with payroll authority. Only these may be shown to an employee. */
  verified: boolean;
  certificateNumber: string | null;
  vaultDocumentId: string | null;
  /** Path the file is served from, present only once verified. */
  downloadPath: string | null;
  coversQuarters: string | null;
  /** Plain-language state, safe to show a finance user or an employee. */
  status: "verified" | "awaiting_verification" | "not_uploaded";
  message: string;
}

function assertFinancialYear(year: number): void {
  if (!Number.isInteger(year) || year < 1900 || year > 2999) {
    throw new Error(`A four-digit financial year start is required, received "${year}"`);
  }
}

/**
 * Whether an employee's Part A for a year exists and may be shown to them.
 *
 * Returns a verdict rather than throwing when absent: a missing Part A is a
 * normal state for most of the year — TRACES only issues it once the quarterly
 * returns are filed — not an error.
 */
export async function getPartAAvailability(
  employeeId: string,
  financialYear: number,
): Promise<PartAAvailability> {
  assertFinancialYear(financialYear);
  const expectedFormNumber = statutoryRegimeForFinancialYear(financialYear).salaryCertificateForm;

  let rows: RowDataPacket[] = [];
  try {
    const [result] = await db.execute<RowDataPacket[]>(
      `SELECT id, certificate_number, vault_document_id, stored_filename,
              storage_category, covers_quarters, verified_at, form_number
         FROM tds_certificate_part_a
        WHERE employee_id = ? AND financial_year = ?
        LIMIT 1`,
      [employeeId, financialYear],
    );
    rows = result;
  } catch {
    // Migration 1032 not applied yet. Report it as "not uploaded" rather than
    // failing the whole certificate request — Part B is still useful, and an
    // outage here should not deny an employee their salary figures.
    return {
      financialYear,
      expectedFormNumber,
      present: false,
      verified: false,
      certificateNumber: null,
      vaultDocumentId: null,
      downloadPath: null,
      coversQuarters: null,
      status: "not_uploaded",
      message:
        `Part A has not been uploaded for FY ${financialYear}-${String(financialYear + 1).slice(2)}. ` +
        `It is issued by TRACES once the quarterly returns for the year are filed.`,
    };
  }

  const row = rows[0] as (RowDataPacket & PartARecord) | undefined;
  const fyLabel = `FY ${financialYear}-${String(financialYear + 1).slice(2)}`;

  if (!row) {
    return {
      financialYear,
      expectedFormNumber,
      present: false,
      verified: false,
      certificateNumber: null,
      vaultDocumentId: null,
      downloadPath: null,
      coversQuarters: null,
      status: "not_uploaded",
      message:
        `Part A has not been uploaded for ${fyLabel}. It is issued by TRACES once ` +
        `the quarterly returns for the year are filed, and cannot be generated here.`,
    };
  }

  const verified = Boolean(row.verified_at);
  return {
    financialYear,
    expectedFormNumber,
    present: true,
    verified,
    certificateNumber: row.certificate_number ?? null,
    vaultDocumentId: verified ? row.vault_document_id : null,
    // Withheld until verified, exactly like the vault id: an unverified
    // certificate must not be reachable, not merely unadvertised.
    downloadPath: verified
      ? `/api/files/${row.storage_category ?? "tds-certificates"}/${row.stored_filename}`
      : null,
    coversQuarters: row.covers_quarters ?? null,
    status: verified ? "verified" : "awaiting_verification",
    message: verified
      ? `Part A for ${fyLabel} is verified and available for download.`
      : `Part A for ${fyLabel} has been uploaded but not yet verified, so it is not ` +
        `available to the employee. Payroll must confirm it matches this employee and year.`,
  };
}

/**
 * Record an uploaded TRACES Part A against an employee and year.
 *
 * The file itself must already be in document_vault_inventory — the vault owns
 * access level, download tokens and access logging, which a tax certificate
 * needs and a bare file path does not provide.
 *
 * Deliberately NOT verified on insert. Uploading is a clerical act; confirming
 * the document belongs to this employee and this year is a payroll judgement,
 * and conflating them would let a misfiled certificate reach an employee.
 */
export async function recordPartA(input: {
  employeeId: string;
  financialYear: number;
  vaultDocumentId: string;
  storedFilename: string;
  storageCategory?: string;
  uploadedBy: string;
  certificateNumber?: string | null;
  coversQuarters?: string | null;
  notes?: string | null;
}): Promise<{ id: string; formNumber: string }> {
  assertFinancialYear(input.financialYear);
  const formNumber = statutoryRegimeForFinancialYear(input.financialYear).salaryCertificateForm;

  const { randomUUID } = await import("crypto");
  const id = randomUUID();

  // A reissue replaces rather than accumulating rows that later disagree about
  // which certificate is authentic. Replacing clears the previous verification:
  // a new document has not been checked just because its predecessor was.
  await db.execute(
    `INSERT INTO tds_certificate_part_a
       (id, employee_id, financial_year, form_number, certificate_number,
        vault_document_id, stored_filename, storage_category, covers_quarters, uploaded_by, notes)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON DUPLICATE KEY UPDATE
       form_number        = VALUES(form_number),
       certificate_number = VALUES(certificate_number),
       vault_document_id  = VALUES(vault_document_id),
       stored_filename    = VALUES(stored_filename),
       storage_category   = VALUES(storage_category),
       covers_quarters    = VALUES(covers_quarters),
       uploaded_by        = VALUES(uploaded_by),
       uploaded_at        = NOW(),
       notes              = VALUES(notes),
       verified_by        = NULL,
       verified_at        = NULL`,
    [
      id,
      input.employeeId,
      input.financialYear,
      formNumber,
      input.certificateNumber ?? null,
      input.vaultDocumentId,
      input.storedFilename,
      input.storageCategory ?? "tds-certificates",
      input.coversQuarters ?? null,
      input.uploadedBy,
      input.notes ?? null,
    ],
  );

  return { id, formNumber };
}

/** Confirm an uploaded Part A belongs to the employee and year it is filed under. */
export async function verifyPartA(
  employeeId: string,
  financialYear: number,
  verifiedBy: string,
): Promise<boolean> {
  assertFinancialYear(financialYear);
  const [result] = await db.execute(
    `UPDATE tds_certificate_part_a
        SET verified_by = ?, verified_at = NOW()
      WHERE employee_id = ? AND financial_year = ?`,
    [verifiedBy, employeeId, financialYear],
  );
  return Number((result as { affectedRows?: number }).affectedRows ?? 0) > 0;
}

export const tdsCertificatePartAService = {
  getPartAAvailability,
  recordPartA,
  verifyPartA,
};
