import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Building2, CheckCircle2, IndianRupee, Plus, Save, Send, ShieldCheck, Trash2, XCircle } from "lucide-react";
import { toast } from "sonner";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { calculateBudgetLine, type BranchBudgetLineInput, useBranchBudgets } from "@/hooks/useBranchBudget";
import { hrmsApi } from "@/lib/hrmsApi";

const HEADS=["Business Promotion Expenses","Communication & Connectivity","Contract Fees Facilities","CONTRACT FEES","Donation-Charitable Trust","Electricity","Fee & Subscription","Hiring Charges","Insurance Expenses","Legal/Consultancy Charges","Office Rent","Office Maintenance A/c","Printing & Stationery Expenses","Repairs & Maintenance","Security Service Charges","Spot/Floor/Field Incentive","Staff Welfare","Staff Training & Recruitment","Tours, Travelling & Conveyance","Tour Expenses"];
const UNITS=["Nos","Seat","User","Month","Candidate","Service","Sq. Ft.","Connection","Device","Litre","Unit"];
const GST_RATES=[0,5,12,18,28];
function periodNow(){const n=new Date();return`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}`}
function fyFromPeriod(p:string){const[y,m]=p.split("-").map(Number);return m>=4?`${y}-${String(y+1).slice(-2)}`:`${y-1}-${String(y).slice(-2)}`}
function money(v:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(v||0)}
function blankLine():BranchBudgetLineInput{return{head:"",subHead:"",itemName:"",quantity:1,unit:"Nos",unitRate:0,taxTreatment:"exclusive",gstRate:18,gstType:"cgst_sgst",recoverableTaxPct:100,allocationDriver:"agent_headcount",justification:""}}

export default function BranchBudgetManagementPage(){
 const[period,setPeriod]=useState(periodNow());const[branchId,setBranchId]=useState("");const[lines,setLines]=useState<BranchBudgetLineInput[]>([blankLine()]);const[savedBudgetId,setSavedBudgetId]=useState<string|null>(null);const[remarks,setRemarks]=useState("");
 const{budgetsQuery,saveBudget,submitBudget,reviewBudget}=useBranchBudgets({period,branchId:branchId||undefined});
 const{data:branchResponse}=useQuery({queryKey:["budget-branches"],queryFn:()=>hrmsApi.get<any>("/api/org/branches?limit=200")});
 const{data:processResponse}=useQuery({queryKey:["budget-processes"],queryFn:()=>hrmsApi.get<any>("/api/org/processes?limit=500")});
 const{data:costCentreResponse}=useQuery({queryKey:["budget-cost-centres"],queryFn:()=>hrmsApi.get<any>("/api/org/cost-centres?limit=500")});
 const{data:vendorResponse}=useQuery({queryKey:["budget-vendors"],queryFn:()=>hrmsApi.get<any>("/api/erp/vendors?limit=500")});
 const branches:any[]=branchResponse?.data??branchResponse??[];const processes:any[]=(processResponse?.data??processResponse??[]).filter((x:any)=>!branchId||x.branch_id===branchId);const costCentres:any[]=(costCentreResponse?.data??costCentreResponse??[]).filter((x:any)=>!branchId||x.branch_id===branchId);const vendors:any[]=vendorResponse?.data??vendorResponse??[];
 const totals=useMemo(()=>lines.reduce((a,l)=>{const v=calculateBudgetLine(l);a.base+=v.base;a.tax+=v.tax;a.gross+=v.gross;a.pnl+=v.pnlCost;return a},{base:0,tax:0,gross:0,pnl:0}),[lines]);
 const updateLine=(i:number,p:Partial<BranchBudgetLineInput>)=>setLines(c=>c.map((l,n)=>n===i?{...l,...p}:l));
 async function save(submit=false){try{if(!branchId)throw new Error("Select branch");lines.forEach((l,i)=>{if(!l.head||!l.itemName||!l.unit||!l.justification)throw new Error(`Complete mandatory details in line ${i+1}`)});const result:any=await saveBudget.mutateAsync({id:savedBudgetId||undefined,branchId,periodCode:period,financialYear:fyFromPeriod(period),lines});const id=result?.id??result?.data?.id??savedBudgetId;if(id)setSavedBudgetId(id);if(submit&&id)await submitBudget.mutateAsync(id);toast.success(submit?"Budget submitted to Branch Head":"Budget draft saved")}catch(e){toast.error(e instanceof Error?e.message:"Budget could not be saved")}}
 async function review(id:string,decision:"approve"|"reject"|"revision"){try{await reviewBudget.mutateAsync({id,decision,remarks:remarks||undefined});toast.success(decision==="approve"?"Budget advanced to the next approval stage":"Budget decision recorded");setRemarks("")}catch(e){toast.error(e instanceof Error?e.message:"Budget review failed")}}
 return <DashboardLayout><div className="min-h-screen bg-[radial-gradient(circle_at_top_right,_rgba(16,185,129,0.14),_transparent_26%),linear-gradient(180deg,_#f8fafc_0%,_#ffffff_44%,_#f5f7fb_100%)]"><div className="mx-auto max-w-[1600px] space-y-6 px-4 py-6 sm:px-6 lg:px-8">
 <section className="overflow-hidden rounded-[32px] border border-slate-200 bg-slate-950 text-white shadow-[0_24px_80px_rgba(15,23,42,0.24)]"><div className="grid gap-8 p-6 lg:grid-cols-[1.5fr_0.8fr] lg:p-8"><div className="space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-emerald-200"><ShieldCheck className="h-3.5 w-3.5"/>Branch Budget Control</div><div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Approve every cost at line-item depth before GRN consumption.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300 sm:text-base">Branch → cost centre → process attribution, quantity, rate, GST recoverability and approval governance are captured together.</p></div><div className="flex flex-wrap gap-3"><Button onClick={()=>void save(false)} disabled={saveBudget.isPending}><Save className="mr-2 h-4 w-4"/>Save draft</Button><Button variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10" onClick={()=>void save(true)}><Send className="mr-2 h-4 w-4"/>Submit to Branch Head</Button><Button asChild variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10"><Link to="/finance/grn">Open GRN Management</Link></Button></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{[["Without tax",totals.base],["Tax budget",totals.tax],["With tax",totals.gross],["P&L cost",totals.pnl]].map(([l,v])=><Card key={String(l)} className="border-white/10 bg-white/5 text-white shadow-none"><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.18em] text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{money(Number(v))}</p></CardContent></Card>)}</div></div></section>
 <Tabs defaultValue="create" className="space-y-5"><TabsList className="h-auto flex-wrap rounded-2xl bg-white p-1 shadow-sm"><TabsTrigger value="create">Create budget</TabsTrigger><TabsTrigger value="queue">Approval queue</TabsTrigger></TabsList>
 <TabsContent value="create" className="space-y-5"><Card className="rounded-3xl border-slate-200 shadow-sm"><CardContent className="grid gap-4 p-5 md:grid-cols-3"><div className="space-y-2"><Label>Period</Label><Input type="month" value={period} onChange={e=>{setPeriod(e.target.value);setSavedBudgetId(null)}}/></div><div className="space-y-2"><Label>Branch</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={branchId} onChange={e=>{setBranchId(e.target.value);setSavedBudgetId(null)}}><option value="">Select branch</option>{branches.map((b:any)=><option key={b.id} value={b.id}>{b.branch_name??b.name}</option>)}</select></div><div className="space-y-2"><Label>Financial year</Label><Input value={fyFromPeriod(period)} readOnly/></div></CardContent></Card>
 <div className="space-y-4">{lines.map((line,index)=>{const calc=calculateBudgetLine(line);return <Card key={index} className="rounded-3xl border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Budget line {index+1}</CardTitle><Button variant="ghost" size="icon" onClick={()=>setLines(c=>c.length===1?c:c.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4 text-rose-500"/></Button></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
 <div className="space-y-2"><Label>Cost centre</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.costCentreId??""} onChange={e=>updateLine(index,{costCentreId:e.target.value||null})}><option value="">Branch/common</option>{costCentres.map((x:any)=><option key={x.id} value={x.id}>{x.cost_centre_name??x.name}</option>)}</select></div><div className="space-y-2"><Label>Process</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.processId??""} onChange={e=>updateLine(index,{processId:e.target.value||null})}><option value="">Shared/all processes</option>{processes.map((x:any)=><option key={x.id} value={x.id}>{x.process_name??x.name}</option>)}</select></div><div className="space-y-2"><Label>Head *</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.head} onChange={e=>updateLine(index,{head:e.target.value,subHead:""})}><option value="">Select head</option>{HEADS.map(h=><option key={h}>{h}</option>)}</select></div><div className="space-y-2"><Label>Sub-head</Label><Input value={line.subHead??""} onChange={e=>updateLine(index,{subHead:e.target.value})}/></div>
 <div className="space-y-2 xl:col-span-2"><Label>Item / service *</Label><Input value={line.itemName} onChange={e=>updateLine(index,{itemName:e.target.value})}/></div><div className="space-y-2"><Label>Preferred vendor</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.preferredVendorId??""} onChange={e=>updateLine(index,{preferredVendorId:e.target.value||null})}><option value="">Not fixed</option>{vendors.map((v:any)=><option key={v.id} value={v.id}>{v.vendor_name??v.name}</option>)}</select></div><div className="space-y-2"><Label>Allocation driver</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.allocationDriver??""} onChange={e=>updateLine(index,{allocationDriver:e.target.value})}>{[["agent_headcount","Agent headcount"],["total_manpower","Total manpower"],["revenue_share","Revenue share"],["seat_count","Seat count"],["device_count","Device count"],["floor_area","Floor area"],["direct_tagging","Direct tagging"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
 <div className="space-y-2"><Label>Quantity *</Label><Input type="number" min="0.0001" step="0.01" value={line.quantity} onChange={e=>updateLine(index,{quantity:Number(e.target.value)})}/></div><div className="space-y-2"><Label>Unit *</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.unit} onChange={e=>updateLine(index,{unit:e.target.value})}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></div><div className="space-y-2"><Label>Unit rate *</Label><Input type="number" min="0" step="0.01" value={line.unitRate} onChange={e=>updateLine(index,{unitRate:Number(e.target.value)})}/></div><div className="space-y-2"><Label>Tax treatment</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.taxTreatment} onChange={e=>updateLine(index,{taxTreatment:e.target.value as any})}><option value="exclusive">Tax exclusive</option><option value="inclusive">Tax inclusive</option><option value="exempt">Exempt</option><option value="reverse_charge">Reverse charge</option><option value="non_gst">Non-GST</option></select></div>
 <div className="space-y-2"><Label>GST rate</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.gstRate} onChange={e=>updateLine(index,{gstRate:Number(e.target.value)})}>{GST_RATES.map(r=><option key={r} value={r}>{r}%</option>)}</select></div><div className="space-y-2"><Label>GST type</Label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={line.gstType} onChange={e=>updateLine(index,{gstType:e.target.value as any})}><option value="cgst_sgst">CGST + SGST</option><option value="igst">IGST</option><option value="none">None</option></select></div><div className="space-y-2"><Label>Recoverable GST %</Label><Input type="number" min="0" max="100" value={line.recoverableTaxPct} onChange={e=>updateLine(index,{recoverableTaxPct:Number(e.target.value)})}/></div><div className="space-y-2"><Label>Line gross</Label><Input value={money(calc.gross)} readOnly/></div>
 <div className="space-y-2 md:col-span-2 xl:col-span-4"><Label>Justification *</Label><Textarea value={line.justification} onChange={e=>updateLine(index,{justification:e.target.value})}/></div><div className="md:col-span-2 xl:col-span-4 grid gap-3 sm:grid-cols-4">{[["Without tax",calc.base],["Tax",calc.tax],["With tax",calc.gross],["P&L cost",calc.pnlCost]].map(([l,v])=><div key={String(l)} className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{l}</p><p className="font-bold">{money(Number(v))}</p></div>)}</div>
 </CardContent></Card>})}</div><Button variant="outline" className="w-full rounded-2xl border-dashed py-6" onClick={()=>setLines(c=>[...c,blankLine()])}><Plus className="mr-2 h-4 w-4"/>Add budget line</Button></TabsContent>
 <TabsContent value="queue" className="space-y-4"><Card className="rounded-3xl border-slate-200 shadow-sm"><CardHeader><CardTitle>Budget approval queue</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-3"><Input placeholder="Approval remarks for reject/revision" value={remarks} onChange={e=>setRemarks(e.target.value)}/></div>{(budgetsQuery.data??[]).map(b=><div key={b.id} className="grid gap-3 rounded-2xl border border-slate-200 p-4 lg:grid-cols-[1.3fr_1fr_1fr_auto]"><div><p className="font-semibold">{b.budget_number}</p><p className="text-sm text-slate-500">{b.branch_name} · {b.period_code} · {b.line_count} lines</p></div><div><p className="text-xs text-slate-500">With tax / P&L</p><p className="font-semibold">{money(Number(b.gross_budget_amount))}</p></div><div><p className="text-xs text-slate-500">Reserved / consumed</p><p className="font-semibold">{money(Number(b.reserved_amount))} / {money(Number(b.consumed_amount))}</p></div><div className="flex flex-wrap items-center justify-end gap-2"><Badge variant="outline">{b.status.replaceAll("_"," ")}</Badge>{["submitted","branch_head_approved","finance_head_approved"].includes(b.status)&&<Button size="sm" onClick={()=>void review(b.id,"approve")}><CheckCircle2 className="mr-1 h-3.5 w-3.5"/>Approve</Button>}{["submitted","branch_head_approved","finance_head_approved"].includes(b.status)&&<Button size="sm" variant="outline" onClick={()=>void review(b.id,"revision")}><XCircle className="mr-1 h-3.5 w-3.5"/>Revision</Button>}</div></div>)}{!budgetsQuery.isLoading&&!(budgetsQuery.data??[]).length&&<div className="py-12 text-center text-slate-500"><Building2 className="mx-auto mb-3 h-10 w-10"/>No budget found.</div>}</CardContent></Card></TabsContent>
 </Tabs></div></div></DashboardLayout>;
}
