import { Router } from "express";
import type { Response, NextFunction } from "express";
import type { AuthenticatedRequest } from "../../middleware/authMiddleware.js";
import { requireAuth } from "../../middleware/authMiddleware.js";
import { requireRole } from "../../middleware/requireRole.js";
import { requireQueryScope } from "../../middleware/scopeMiddleware.js";
import { hasScopedAccess } from "../../shared/scopeAccess.js";
import { db } from "../../db/mysql.js";
import type { RowDataPacket } from "mysql2";
import {
  getEmployeeWfmCompliance,
  getBranchWfmCompliance,
} from "./wfm-compliance-analytics.service.js";

const router = Router();

router.use(requireAuth);

/**
 * Every query below read `roster_assignment`, which holds **0 rows**. The live roster is
 * `wfm_roster_assignment` (417,773) — it is where the spreadsheet import commits, where roster
 * generation and auto-roster write, and where publishing and manual edits land. Owner
 * confirmed 2026-08-28 that it is the single source of roster whether a roster is uploaded or
 * created through the UI.
 *
 * This was not a quiet emptiness. `compliancePct` falls back to `: 100` when total_shifts = 0,
 * so this endpoint reported **100% compliance with 0 violations** on every rule — a false
 * all-clear generated by the backend itself, not by the dashboard.
 *
 * ── Why the guard below ───────────────────────────────────────────────────────────────────
 * wfm_roster_assignment carries one synthetic cohort: 412,032 rows inserted in a single batch
 * on 2026-06-11, every one 09:00–18:00 with no assignment_type, no template, no cycle, no
 * import batch and NO WEEK-OFFS AT ALL. Measured against the whole table, any compliance
 * metric is dominated by it and confidently wrong — a week-off-fairness rule, for instance,
 * would find zero week-offs across 1,392 employees.
 *
 * The predicate excludes exactly those 412,032 and keeps exactly the 5,741 real rows (verified
 * by count on live data, both directions). It is written as "all four provenance columns are
 * null" rather than "cycle_id IS NOT NULL", because roster.service.ts sets cycle_id only when
 * a cycle is supplied — a manually created assignment can legitimately have neither cycle_id
 * nor import_batch_id, and the narrower filter would silently drop real UI-created rosters.
 *
 * The synthetic cohort also stops at roster_date 2026-03-31 while every real row starts
 * 2026-07-12, so a current-period query already excludes it by date. The guard is kept anyway
 * so a query over a historical month cannot quietly resurrect it.
 */
const realRoster = (alias: string) =>
  `NOT (${alias}.import_batch_id IS NULL AND ${alias}.cycle_id IS NULL ` +
  `AND ${alias}.assignment_type IS NULL AND ${alias}.shift_template_id IS NULL)`;

/**
 * Middleware to verify employee scope access for compliance queries.
 * branch_head/manager/operations_manager can only query employees in their assigned scope.
 */
async function verifyEmployeeScope(req: AuthenticatedRequest, res: Response, next: NextFunction) {
  try {
    const userId = req.authUser?.id;
    if (!userId) return res.status(401).json({ success: false, message: "Unauthorized" });

    const employeeId = req.query.employeeId as string;
    if (!employeeId) return next();

    // Get employee's branch/process to verify scope
    const [empRows] = await db.execute<RowDataPacket[]>(
      "SELECT branch_id, process_id FROM employees WHERE id = ? LIMIT 1",
      [employeeId]
    );
    const emp = empRows[0] as { branch_id?: string; process_id?: string } | undefined;
    if (!emp) return res.status(404).json({ success: false, message: "Employee not found" });

    // Verify caller has access to this employee's branch/process
    const hasAccess = await hasScopedAccess(
      userId,
      ["wfm", "manager", "branch_head", "operations_manager"],
      { branchId: emp.branch_id ?? null, processId: emp.process_id ?? null },
      { allowAdminBypass: true }
    );

    if (!hasAccess) {
      return res.status(403).json({
        success: false,
        message: "Forbidden: employee is outside your assigned branch/process scope",
      });
    }
    return next();
  } catch (err) {
    return next(err);
  }
}

/**
 * GET /api/wfm-compliance/employee
 * Query params: employeeId (required), period (YYYY-MM, optional)
 * Roles: hr | wfm | admin | super_admin | manager | branch_head | operations_manager
 * Scope: branch_head/manager/operations_manager can only query employees in their assigned scope
 */
router.get(
  "/employee",
  requireRole("hr", "wfm", "admin", "super_admin", "manager", "branch_head", "operations_manager"),
  verifyEmployeeScope,
  (req, res, next) => {
    getEmployeeWfmCompliance(req, res).catch(next);
  }
);

/**
 * GET /api/wfm-compliance/branch
 * Query params: branchId (required), period (YYYY-MM, optional), processId (optional)
 * Roles: hr | wfm | admin | super_admin | manager | branch_head | operations_manager
 * Scope: branch_head/manager/operations_manager can only query branches in their assigned scope
 */
router.get(
  "/branch",
  requireRole("hr", "wfm", "admin", "super_admin", "manager", "branch_head", "operations_manager"),
  requireQueryScope(
    ["wfm", "manager", "branch_head", "operations_manager"],
    ["admin", "hr", "super_admin", "ceo"]
  ),
  (req, res, next) => {
    getBranchWfmCompliance(req, res).catch(next);
  }
);

// ── Roster Compliance Summary (for RosterComplianceMonitor dashboard) ─────────

/**
 * GET /api/wfm-compliance/summary
 * Returns compliance summary with rule violation counts for the compliance dashboard
 */
router.get(
  "/summary",
  requireRole("hr", "wfm", "admin", "super_admin", "operations_manager", "ceo"),
  async (req, res, next) => {
    try {
      const branchId = req.query.branchId as string | undefined;
      const processId = req.query.processId as string | undefined;
      const period = (req.query.period as string) || new Date().toISOString().slice(0, 7);

      const periodStart = `${period}-01`;
      const periodEnd = `${period}-${new Date(+period.split('-')[0], +period.split('-')[1], 0).getDate().toString().padStart(2, '0')}`;

      let whereClause = `ra.roster_date BETWEEN ? AND ? AND ${realRoster('ra')}`;
      const params: (string | number)[] = [periodStart, periodEnd];

      if (branchId) {
        whereClause += ' AND e.branch_id = ?';
        params.push(branchId);
      }
      if (processId) {
        whereClause += ' AND e.process_id = ?';
        params.push(processId);
      }

      // Overall compliance score (attendance-based)
      const [compRows] = await db.execute<RowDataPacket[]>(
        `SELECT
           COUNT(DISTINCT ra.employee_id) AS total_employees,
           SUM(CASE WHEN ra.is_week_off = 0 AND COALESCE(adr.attendance_status,'') IN ('present','half_day') THEN 1 ELSE 0 END) AS compliant,
           SUM(CASE WHEN ra.is_week_off = 0 AND COALESCE(adr.attendance_status,'') NOT IN ('present','half_day') THEN 1 ELSE 0 END) AS violations,
           SUM(CASE WHEN ra.is_week_off = 0 THEN 1 ELSE 0 END) AS total_shifts
         FROM wfm_roster_assignment ra
         JOIN employees e ON ra.employee_id = e.id
         LEFT JOIN attendance_daily_record adr ON adr.employee_id = ra.employee_id AND adr.record_date = ra.roster_date
         WHERE ${whereClause}`,
        params
      );

      const compliancePct = compRows[0]?.total_shifts > 0
        ? Math.round((compRows[0].compliant / compRows[0].total_shifts) * 100)
        : 100;

      // Count by violation type (simulated WFM rules)
      // Rule 1: Minimum rest (< 11 hours between shifts)
      const [restRows] = await db.execute<RowDataPacket[]>(
        `SELECT COUNT(*) AS count FROM (
           SELECT ra1.employee_id, ra1.roster_date,
             TIMESTAMPDIFF(HOUR,
               CONCAT(ra1.roster_date, ' ', sm1.end_time),
               CONCAT(ra2.roster_date, ' ', sm2.start_time)
             ) AS rest_hours
           FROM wfm_roster_assignment ra1
           JOIN wfm_roster_assignment ra2 ON ra1.employee_id = ra2.employee_id
             AND ra2.roster_date = DATE_ADD(ra1.roster_date, INTERVAL 1 DAY)
           JOIN employees e ON ra1.employee_id = e.id
           JOIN wfm_shift_master sm1 ON ra1.shift_template_id = sm1.id
           JOIN wfm_shift_master sm2 ON ra2.shift_template_id = sm2.id
           WHERE ra1.roster_date BETWEEN ? AND DATE_SUB(?, INTERVAL 1 DAY)
             AND ${realRoster('ra1')} AND ${realRoster('ra2')}
             ${branchId ? 'AND e.branch_id = ?' : ''}
             ${processId ? 'AND e.process_id = ?' : ''}
           HAVING rest_hours < 11
         ) AS rest_violations`,
        branchId && processId
          ? [periodStart, periodEnd, branchId, processId]
          : branchId
            ? [periodStart, periodEnd, branchId]
            : processId
              ? [periodStart, periodEnd, processId]
              : [periodStart, periodEnd]
      );

      // Rule 2: Consecutive days (> 6 consecutive working days)
      const [consecRows] = await db.execute<RowDataPacket[]>(
        `SELECT COUNT(DISTINCT employee_id) AS count FROM (
           SELECT employee_id, roster_date,
             @seq := IF(@prev_emp = employee_id AND DATEDIFF(roster_date, @prev_date) = 1, @seq + 1, 1) AS consecutive,
             @prev_emp := employee_id,
             @prev_date := roster_date
           FROM wfm_roster_assignment ra
           JOIN employees e ON ra.employee_id = e.id,
             (SELECT @seq := 0, @prev_emp := '', @prev_date := NULL) AS vars
           WHERE ra.roster_date BETWEEN ? AND ? AND ${realRoster('ra')}
             AND ra.is_week_off = 0
             ${branchId ? 'AND e.branch_id = ?' : ''}
             ${processId ? 'AND e.process_id = ?' : ''}
           ORDER BY employee_id, roster_date
           HAVING consecutive > 6
         ) AS consec_violations`,
        branchId && processId
          ? [periodStart, periodEnd, branchId, processId]
          : branchId
            ? [periodStart, periodEnd, branchId]
            : processId
              ? [periodStart, periodEnd, processId]
              : [periodStart, periodEnd]
      );

      // Rule 3: Weekly off fairness (unfair distribution)
      const [weekoffRows] = await db.execute<RowDataPacket[]>(
        `SELECT COUNT(*) AS count FROM (
           SELECT e.id, COUNT(*) AS weekoffs
           FROM wfm_roster_assignment ra
           JOIN employees e ON ra.employee_id = e.id
           WHERE ra.roster_date BETWEEN ? AND ? AND ${realRoster('ra')}
             AND ra.is_week_off = 1
             ${branchId ? 'AND e.branch_id = ?' : ''}
             ${processId ? 'AND e.process_id = ?' : ''}
           GROUP BY e.id
           HAVING weekoffs < 4
         ) AS weekoff_violations`,
        branchId && processId
          ? [periodStart, periodEnd, branchId, processId]
          : branchId
            ? [periodStart, periodEnd, branchId]
            : processId
              ? [periodStart, periodEnd, processId]
              : [periodStart, periodEnd]
      );

      // Rule 4: Max hours/week (> 48 hours) - simplified count
      const [hoursRows] = await db.execute<RowDataPacket[]>(
        `SELECT COUNT(DISTINCT employee_id) AS count FROM (
           SELECT ra.employee_id, WEEK(ra.roster_date) AS wk,
             SUM(COALESCE(sm.required_minutes, 480)) / 60 AS weekly_hours
           FROM wfm_roster_assignment ra
           JOIN employees e ON ra.employee_id = e.id
           LEFT JOIN wfm_shift_master sm ON ra.shift_template_id = sm.id
           WHERE ra.roster_date BETWEEN ? AND ? AND ${realRoster('ra')}
             AND ra.is_week_off = 0
             ${branchId ? 'AND e.branch_id = ?' : ''}
             ${processId ? 'AND e.process_id = ?' : ''}
           GROUP BY ra.employee_id, WEEK(ra.roster_date)
           HAVING weekly_hours > 48
         ) AS hours_violations`,
        branchId && processId
          ? [periodStart, periodEnd, branchId, processId]
          : branchId
            ? [periodStart, periodEnd, branchId]
            : processId
              ? [periodStart, periodEnd, processId]
              : [periodStart, periodEnd]
      );

      // Rule 5: Night shift limit (> 5 consecutive night shifts)
      const [nightRows] = await db.execute<RowDataPacket[]>(
        `SELECT COUNT(DISTINCT employee_id) AS count FROM (
           SELECT ra.employee_id, COUNT(*) AS night_count
           FROM wfm_roster_assignment ra
           JOIN employees e ON ra.employee_id = e.id
           JOIN wfm_shift_master sm ON ra.shift_template_id = sm.id
           WHERE ra.roster_date BETWEEN ? AND ? AND ${realRoster('ra')}
             AND (HOUR(sm.start_time) >= 20 OR HOUR(sm.start_time) < 6)
             ${branchId ? 'AND e.branch_id = ?' : ''}
             ${processId ? 'AND e.process_id = ?' : ''}
           GROUP BY ra.employee_id, WEEK(ra.roster_date)
           HAVING night_count > 5
         ) AS night_violations`,
        branchId && processId
          ? [periodStart, periodEnd, branchId, processId]
          : branchId
            ? [periodStart, periodEnd, branchId]
            : processId
              ? [periodStart, periodEnd, processId]
              : [periodStart, periodEnd]
      );

      const rules = [
        {
          ruleId: 'MIN_REST',
          ruleName: 'Minimum Rest Period',
          description: 'Less than 11 hours between shifts',
          threshold: '11 hours',
          violationCount: Number(restRows[0]?.count ?? 0),
          severity: 'high' as const,
        },
        {
          ruleId: 'CONSECUTIVE_DAYS',
          ruleName: 'Consecutive Working Days',
          description: 'More than 6 consecutive working days',
          threshold: '6 days max',
          violationCount: Number(consecRows[0]?.count ?? 0),
          severity: 'high' as const,
        },
        {
          ruleId: 'WEEKOFF_FAIRNESS',
          ruleName: 'Week-off Fairness',
          description: 'Less than 4 week-offs in month',
          threshold: '4 per month',
          violationCount: Number(weekoffRows[0]?.count ?? 0),
          severity: 'medium' as const,
        },
        {
          ruleId: 'MAX_HOURS',
          ruleName: 'Maximum Weekly Hours',
          description: 'More than 48 hours in a week',
          threshold: '48 hours/week',
          violationCount: Number(hoursRows[0]?.count ?? 0),
          severity: 'high' as const,
        },
        {
          ruleId: 'NIGHT_SHIFT_LIMIT',
          ruleName: 'Night Shift Limit',
          description: 'More than 5 consecutive night shifts',
          threshold: '5 nights max',
          violationCount: Number(nightRows[0]?.count ?? 0),
          severity: 'medium' as const,
        },
      ];

      const totalViolations = rules.reduce((s, r) => s + r.violationCount, 0);

      res.json({
        period,
        compliancePct,
        totalEmployees: Number(compRows[0]?.total_employees ?? 0),
        totalViolations,
        rules,
        trend: 0,
      });
    } catch (err) {
      next(err);
    }
  }
);

/**
 * GET /api/wfm-compliance/violations
 * Returns list of specific violations for the compliance dashboard
 */
router.get(
  "/violations",
  requireRole("hr", "wfm", "admin", "super_admin", "operations_manager"),
  async (req, res, next) => {
    try {
      const branchId = req.query.branchId as string | undefined;
      const ruleId = req.query.ruleId as string | undefined;
      const period = (req.query.period as string) || new Date().toISOString().slice(0, 7);
      const limit = Math.min(parseInt(req.query.limit as string) || 50, 200);

      const periodStart = `${period}-01`;
      const periodEnd = `${period}-${new Date(+period.split('-')[0], +period.split('-')[1], 0).getDate().toString().padStart(2, '0')}`;

      // Get violations by type (simplified - mainly adherence violations)
      const params: (string | number)[] = [periodStart, periodEnd];
      let branchFilter = '';
      if (branchId) {
        branchFilter = 'AND e.branch_id = ?';
        params.push(branchId);
      }
      params.push(limit);

      const [rows] = await db.execute<RowDataPacket[]>(
        `SELECT
           ra.id AS violation_id,
           ra.roster_date AS date,
           e.id AS employee_id,
           e.employee_code,
           e.full_name AS employee_name,
           p.process_name,
           b.branch_name,
           CASE
             WHEN adr.attendance_status IS NULL OR adr.attendance_status = 'absent' THEN 'ABSENT_NO_CALL'
             WHEN adr.clock_in_time IS NOT NULL AND sm.start_time IS NOT NULL
               AND TIMESTAMPDIFF(MINUTE, CONCAT(ra.roster_date, ' ', sm.start_time), adr.clock_in_time) > 5 THEN 'LATE_ARRIVAL'
             ELSE 'ADHERENCE'
           END AS rule_id,
           CASE
             WHEN adr.attendance_status IS NULL OR adr.attendance_status = 'absent' THEN 'Absent Without Notification'
             WHEN adr.clock_in_time IS NOT NULL AND sm.start_time IS NOT NULL
               AND TIMESTAMPDIFF(MINUTE, CONCAT(ra.roster_date, ' ', sm.start_time), adr.clock_in_time) > 5 THEN 'Late Arrival'
             ELSE 'Adherence Violation'
           END AS rule_name,
           CASE
             WHEN adr.attendance_status IS NULL OR adr.attendance_status = 'absent' THEN 'RED'
             WHEN adr.clock_in_time IS NOT NULL AND sm.start_time IS NOT NULL
               AND TIMESTAMPDIFF(MINUTE, CONCAT(ra.roster_date, ' ', sm.start_time), adr.clock_in_time) > 5 THEN 'AMBER'
             ELSE 'AMBER'
           END AS severity,
           sm.shift_name,
           CASE WHEN ra.is_week_off = 1 THEN 'WEEK_OFF' ELSE 'WORKING' END AS status
         FROM wfm_roster_assignment ra
         JOIN employees e ON ra.employee_id = e.id
         LEFT JOIN process_master p ON e.process_id = p.id
         LEFT JOIN branch_master b ON e.branch_id = b.id
         LEFT JOIN wfm_shift_master sm ON ra.shift_template_id = sm.id
         LEFT JOIN attendance_daily_record adr ON adr.employee_id = ra.employee_id AND adr.record_date = ra.roster_date
         WHERE ra.roster_date BETWEEN ? AND ? AND ${realRoster('ra')}
           AND ra.is_week_off = 0
           AND COALESCE(adr.attendance_status,'') NOT IN ('present','half_day')
           ${branchFilter}
         ORDER BY ra.roster_date DESC
         LIMIT ?`,
        params
      );

      res.json({
        period,
        violations: rows.map((r: RowDataPacket) => ({
          violationId: r.violation_id,
          date: r.date,
          employeeId: r.employee_id,
          employeeCode: r.employee_code,
          employeeName: r.employee_name,
          processName: r.process_name,
          branchName: r.branch_name,
          ruleId: r.rule_id,
          ruleName: r.rule_name,
          severity: r.severity === 'RED' ? 'high' : r.severity === 'AMBER' ? 'medium' : 'low',
          shiftName: r.shift_name,
          status: r.status,
        })),
        totalCount: rows.length,
      });
    } catch (err) {
      next(err);
    }
  }
);

/**
 * GET /api/wfm-compliance/trend
 * Returns compliance trend over past 6 months
 */
router.get(
  "/trend",
  requireRole("hr", "wfm", "admin", "super_admin", "ceo"),
  async (req, res, next) => {
    try {
      const branchId = req.query.branchId as string | undefined;

      let branchFilter = '';
      const params: string[] = [];
      if (branchId) {
        branchFilter = 'AND e.branch_id = ?';
        params.push(branchId);
      }

      const [rows] = await db.execute<RowDataPacket[]>(
        `SELECT
           DATE_FORMAT(ra.roster_date, '%Y-%m') AS month,
           SUM(CASE WHEN ra.is_week_off = 0 THEN 1 ELSE 0 END) AS total_shifts,
           SUM(CASE WHEN ra.is_week_off = 0 AND COALESCE(adr.attendance_status,'') IN ('present','half_day') THEN 1 ELSE 0 END) AS compliant,
           SUM(CASE WHEN ra.is_week_off = 0 AND COALESCE(adr.attendance_status,'') NOT IN ('present','half_day') THEN 1 ELSE 0 END) AS violations
         FROM wfm_roster_assignment ra
         JOIN employees e ON ra.employee_id = e.id
         LEFT JOIN attendance_daily_record adr ON adr.employee_id = ra.employee_id AND adr.record_date = ra.roster_date
         WHERE ra.roster_date >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH)
           AND ${realRoster('ra')}
           ${branchFilter}
         GROUP BY DATE_FORMAT(ra.roster_date, '%Y-%m')
         ORDER BY month`,
        params
      );

      const trend = rows.map((r: RowDataPacket) => ({
        month: r.month,
        compliancePct: r.total_shifts > 0 ? Math.round((r.compliant / r.total_shifts) * 100) : 100,
        totalShifts: r.total_shifts,
        violations: r.violations,
      }));

      res.json({ trend });
    } catch (err) {
      next(err);
    }
  }
);

export const wfmComplianceAnalyticsRouter = router;
